/*
   ejs.cache.local.slots.h -- Native property slot definitions for the "ejs.cache.local" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsCacheLocalSlots
#define _h_SLOTS_EjsCacheLocalSlots 1


/*
   Slots for the "ejs.cache.local" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "LocalCache" type 
 */
#define ES_ejs_cache_local_LocalCache_NUM_CLASS_PROP                   0

/*
   Prototype (instance) slots for "LocalCache" type 
 */
#define ES_ejs_cache_local_LocalCache_destroy                          0
#define ES_ejs_cache_local_LocalCache_expire                           1
#define ES_ejs_cache_local_LocalCache_limits                           2
#define ES_ejs_cache_local_LocalCache_read                             3
#define ES_ejs_cache_local_LocalCache_remove                           4
#define ES_ejs_cache_local_LocalCache_setLimits                        5
#define ES_ejs_cache_local_LocalCache_write                            6
#define ES_ejs_cache_local_LocalCache_NUM_INSTANCE_PROP                7
#define ES_ejs_cache_local_LocalCache_NUM_INHERITED_PROP               0

#define _ES_CHECKSUM_ejs_cache_local   15554

#endif
