/*
   ejs.web.slots.h -- Native property slot definitions for the "ejs.web" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsWebSlots
#define _h_SLOTS_EjsWebSlots 1


/*
   Slots for the "ejs.web" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_ejs_web_Cascade_apps                                        0
#define ES_ejs_web_CommonLog_app                                       0
#define ES_ejs_web_CommonLog_logger                                    1
#define ES_ejs_web_ContentType_app                                     0
#define ES_ejs_web_ContentType_options                                 1
#define ES_ejs_web_DirApp_request                                      0
#define ES_ejs_web_DirBuilder_request                                  0
#define ES_ejs_web_Head_app                                            0
#define ES_ejs_web_MethodOverride_app                                  0
#define ES_ejs_web_Middleware_app                                      0
#define ES_ejs_web_Middleware_middleware                               1
#define ES_ejs_web_MvcBuilder_request                                  0
#define ES_ejs_web_toOrdinal_number                                    0
#define ES_ejs_web_toPlural_word                                       0
#define ES_ejs_web_toSingular_plural                                   0
#define ES_ejs_web_ScriptBuilder_request                               0
#define ES_ejs_web_ShowExceptions_app                                  0
#define ES_ejs_web_StaticApp_request                                   0
#define ES_ejs_web_StaticBuilder_request                               0
#define ES_ejs_web_TemplateFilter_app                                  0
#define ES_ejs_web_TemplateApp_request                                 0
#define ES_ejs_web_TemplateBuilder_request                             0
#define ES_ejs_web_TemplateBuilder_options                             1
#define ES_ejs_web_UrlMap_map                                          0
#define ES_ejs_web_UrlMap_options                                      1
#define ES_ejs_web_errorBody_title                                     0
#define ES_ejs_web_errorBody_msg                                       1
#define ES_ejs_web_parseCookies_cookieHeader                           0
#define ES_ejs_web_escapeHtml_str                                      0
#define ES_ejs_web_html_args                                           0
#define ES_ejs_web_unescapeHtml_s                                      0
#define ES_ejs_web_CommonLogBuilder_NUM_CLASS_PROP                     0

/*
   Prototype (instance) slots for "CommonLogBuilder" type 
 */
#define ES_ejs_web_CommonLogBuilder_app                                0
#define ES_ejs_web_CommonLogBuilder_logger                             1
#define ES_ejs_web_CommonLogBuilder_run                                2
#define ES_ejs_web_CommonLogBuilder_NUM_INSTANCE_PROP                  3
#define ES_ejs_web_CommonLogBuilder_NUM_INHERITED_PROP                 0


/*
    Class property slots for the "Controller" type 
 */
#define ES_ejs_web_Controller__initRequest                             0
#define ES_ejs_web_Controller_ejs_web_create                           1
#define ES_ejs_web_Controller_NUM_CLASS_PROP                           2

/*
   Prototype (instance) slots for "Controller" type 
 */
#define ES_ejs_web_Controller__afterCheckers                           0
#define ES_ejs_web_Controller__beforeCheckers                          1
#define ES_ejs_web_Controller_ejs_web_actionName                       2
#define ES_ejs_web_Controller_ejs_web_config                           3
#define ES_ejs_web_Controller_ejs_web_controllerName                   4
#define ES_ejs_web_Controller_ejs_web_log                              5
#define ES_ejs_web_Controller_ejs_web_params                           6
#define ES_ejs_web_Controller_ejs_web_request                          7
#define ES_ejs_web_Controller_ejs_web_absHome                          8
#define ES_ejs_web_Controller_ejs_web_home                             9
#define ES_ejs_web_Controller_ejs_web_pathInfo                         10
#define ES_ejs_web_Controller_ejs_web_session                          11
#define ES_ejs_web_Controller_ejs_web_uri                              12
#define ES_ejs_web_Controller_ejs_web_after                            13
#define ES_ejs_web_Controller_ejs_web_app                              14
#define ES_ejs_web_Controller_ejs_web_autoFinalize                     15
#define ES_ejs_web_Controller_ejs_web_autoFinalizing                   16
#define ES_ejs_web_Controller_ejs_web_before                           17
#define ES_ejs_web_Controller_ejs_web_dontAutoFinalize                 18
#define ES_ejs_web_Controller_ejs_web_error                            19
#define ES_ejs_web_Controller_ejs_web_finalize                         20
#define ES_ejs_web_Controller_ejs_web_finalized                        21
#define ES_ejs_web_Controller_ejs_web_flash                            22
#define ES_ejs_web_Controller_ejs_web_flush                            23
#define ES_ejs_web_Controller_ejs_web_header                           24
#define ES_ejs_web_Controller_ejs_web_inform                           25
#define ES_ejs_web_Controller_ejs_web_link                             26
#define ES_ejs_web_Controller_action_missing                           27
#define ES_ejs_web_Controller_ejs_web_notify                           28
#define ES_ejs_web_Controller_ejs_web_on                               29
#define ES_ejs_web_Controller_ejs_web_read                             30
#define ES_ejs_web_Controller_ejs_web_redirect                         31
#define ES_ejs_web_Controller_ejs_web_removeCheckers                   32
#define ES_ejs_web_Controller_ejs_web_setHeader                        33
#define ES_ejs_web_Controller_ejs_web_setHeaders                       34
#define ES_ejs_web_Controller_ejs_web_setStatus                        35
#define ES_ejs_web_Controller_ejs_web_write                            36
#define ES_ejs_web_Controller_ejs_web_writeContent                     37
#define ES_ejs_web_Controller_ejs_web_writeError                       38
#define ES_ejs_web_Controller_ejs_web_writeFile                        39
#define ES_ejs_web_Controller_ejs_web_writePartialTemplate             40
#define ES_ejs_web_Controller_ejs_web_writeView                        41
#define ES_ejs_web_Controller_ejs_web_writeTemplate                    42
#define ES_ejs_web_Controller_ejs_web_writeTemplateLiteral             43
#define ES_ejs_web_Controller_ejs_web_warn                             44
#define ES_ejs_web_Controller_checkSecurityToken                       45
#define ES_ejs_web_Controller_openDatabase                             46
#define ES_ejs_web_Controller_runCheckers                              47
#define ES_ejs_web_Controller_viewExists                               48
#define ES_ejs_web_Controller_NUM_INSTANCE_PROP                        49
#define ES_ejs_web_Controller_NUM_INHERITED_PROP                       0

/*
    Local slots for methods in type "Controller" 
 */
#define ES_ejs_web_Controller_ejs_web_create_request                   0
#define ES_ejs_web_Controller_ejs_web_create_cname                     1


/*
    Class property slots for the "HtmlViewConnector" type 
 */
#define ES_HtmlViewConnector__initializer___HtmlViewConnector_         0
#define ES_HtmlViewConnector_htmlOptions                               1
#define ES_HtmlViewConnector_defaultStylesheets                        2
#define ES_HtmlViewConnector_defaultScripts                            3
#define ES_HtmlViewConnector_NUM_CLASS_PROP                            4

/*
   Prototype (instance) slots for "HtmlViewConnector" type 
 */
#define ES_HtmlViewConnector_request                                   0
#define ES_HtmlViewConnector_view                                      1
#define ES_HtmlViewConnector_lastDomID                                 2
#define ES_HtmlViewConnector_ejs_web_alert                             3
#define ES_HtmlViewConnector_ejs_web_anchor                            4
#define ES_HtmlViewConnector_ejs_web_button                            5
#define ES_HtmlViewConnector_ejs_web_buttonLink                        6
#define ES_HtmlViewConnector_ejs_web_chart                             7
#define ES_HtmlViewConnector_ejs_web_checkbox                          8
#define ES_HtmlViewConnector_ejs_web_div                               9
#define ES_HtmlViewConnector_ejs_web_endform                           10
#define ES_HtmlViewConnector_ejs_web_flash                             11
#define ES_HtmlViewConnector_ejs_web_form                              12
#define ES_HtmlViewConnector_ejs_web_icon                              13
#define ES_HtmlViewConnector_ejs_web_image                             14
#define ES_HtmlViewConnector_ejs_web_label                             15
#define ES_HtmlViewConnector_ejs_web_list                              16
#define ES_HtmlViewConnector_ejs_web_mail                              17
#define ES_HtmlViewConnector_ejs_web_progress                          18
#define ES_HtmlViewConnector_ejs_web_radio                             19
#define ES_HtmlViewConnector_ejs_web_script                            20
#define ES_HtmlViewConnector_ejs_web_securityToken                     21
#define ES_HtmlViewConnector_ejs_web_stylesheet                        22
#define ES_HtmlViewConnector_ejs_web_table                             23
#define ES_HtmlViewConnector_ejs_web_tabs                              24
#define ES_HtmlViewConnector_ejs_web_text                              25
#define ES_HtmlViewConnector_ejs_web_textarea                          26
#define ES_HtmlViewConnector_ejs_web_tree                              27
#define ES_HtmlViewConnector_emitFormErrors                            28
#define ES_HtmlViewConnector_buildLink                                 29
#define ES_HtmlViewConnector_getAttributes                             30
#define ES_HtmlViewConnector_getCellRowAtt                             31
#define ES_HtmlViewConnector_getKeyAtt                                 32
#define ES_HtmlViewConnector_getTableLink                              33
#define ES_HtmlViewConnector_mapAttributes                             34
#define ES_HtmlViewConnector_getColumns                                35
#define ES_HtmlViewConnector_getTextKind                               36
#define ES_HtmlViewConnector_getNextID                                 37
#define ES_HtmlViewConnector_write                                     38
#define ES_HtmlViewConnector_append                                    39
#define ES_HtmlViewConnector_NUM_INSTANCE_PROP                         40
#define ES_HtmlViewConnector_NUM_INHERITED_PROP                        0


/*
    Class property slots for the "HttpServer" type 
 */
#define ES_ejs_web_HttpServer__initializer___HttpServer_               0
#define ES_ejs_web_HttpServer_indicies                                 1
#define ES_ejs_web_HttpServer_NUM_CLASS_PROP                           2

/*
   Prototype (instance) slots for "HttpServer" type 
 */
#define ES_ejs_web_HttpServer_address                                  0
#define ES_ejs_web_HttpServer_async                                    1
#define ES_ejs_web_HttpServer_documentRoot                             2
#define ES_ejs_web_HttpServer_isSecure                                 3
#define ES_ejs_web_HttpServer_limits                                   4
#define ES_ejs_web_HttpServer_name                                     5
#define ES_ejs_web_HttpServer_port                                     6
#define ES_ejs_web_HttpServer_serverRoot                               7
#define ES_ejs_web_HttpServer_sessions                                 8
#define ES_ejs_web_HttpServer_software                                 9
#define ES_ejs_web_HttpServer_accept                                   10
#define ES_ejs_web_HttpServer_close                                    11
#define ES_ejs_web_HttpServer_listen                                   12
#define ES_ejs_web_HttpServer_on                                       13
#define ES_ejs_web_HttpServer_removeObserver                           14
#define ES_ejs_web_HttpServer_secure                                   15
#define ES_ejs_web_HttpServer_setPipeline                              16
#define ES_ejs_web_HttpServer_setLimits                                17
#define ES_ejs_web_HttpServer_trace                                    18
#define ES_ejs_web_HttpServer_verifyClients                            19
#define ES_ejs_web_HttpServer_NUM_INSTANCE_PROP                        20
#define ES_ejs_web_HttpServer_NUM_INHERITED_PROP                       0


/*
    Class property slots for the "Mvc" type 
 */
#define ES_Mvc__initializer___Mvc_                                     0
#define ES_Mvc_apps                                                    1
#define ES_Mvc_defaultConfig                                           2
#define ES_Mvc_loaded                                                  3
#define ES_Mvc_EJSRC                                                   4
#define ES_Mvc_NUM_CLASS_PROP                                          5

/*
   Prototype (instance) slots for "Mvc" type 
 */
#define ES_Mvc_loadConfig                                              0
#define ES_Mvc_init                                                    1
#define ES_Mvc_rebuildComponent                                        2
#define ES_Mvc_loadComponent                                           3
#define ES_Mvc_NUM_INSTANCE_PROP                                       4
#define ES_Mvc_NUM_INHERITED_PROP                                      0


/*
    Class property slots for the "Inflector" type 
 */
#define ES_ejs_web_Inflector__initializer___Inflector_                 0
#define ES_ejs_web_Inflector_plural                                    1
#define ES_ejs_web_Inflector_singular                                  2
#define ES_ejs_web_Inflector_irregular                                 3
#define ES_ejs_web_Inflector_uncountable                               4
#define ES_ejs_web_Inflector_toOrdinal                                 5
#define ES_ejs_web_Inflector_toPlural                                  6
#define ES_ejs_web_Inflector_toSingular                                7
#define ES_ejs_web_Inflector_NUM_CLASS_PROP                            8

/*
   Prototype (instance) slots for "Inflector" type 
 */
#define ES_ejs_web_Inflector_NUM_INSTANCE_PROP                         0
#define ES_ejs_web_Inflector_NUM_INHERITED_PROP                        0

/*
    Local slots for methods in type "Inflector" 
 */
#define ES_ejs_web_Inflector_toOrdinal_number                          0
#define ES_ejs_web_Inflector_toPlural_word                             0
#define ES_ejs_web_Inflector_toSingular_word                           0


/*
    Class property slots for the "Request" type 
 */
#define ES_ejs_web_Request__initializer___Request_                     0
#define ES_ejs_web_Request_SecurityTokenName                           1
#define ES_ejs_web_Request_jsgi                                        2
#define ES_ejs_web_Request_NUM_CLASS_PROP                              3

/*
   Prototype (instance) slots for "Request" type 
 */
#define ES_ejs_web_Request_lastFlash                                   0
#define ES_ejs_web_Request_absHome                                     1
#define ES_ejs_web_Request_authGroup                                   2
#define ES_ejs_web_Request_authType                                    3
#define ES_ejs_web_Request_authUser                                    4
#define ES_ejs_web_Request_autoFinalizing                              5
#define ES_ejs_web_Request_config                                      6
#define ES_ejs_web_Request_controller                                  7
#define ES_ejs_web_Request_contentLength                               8
#define ES_ejs_web_Request_contentType                                 9
#define ES_ejs_web_Request_cookies                                     10
#define ES_ejs_web_Request_dir                                         11
#define ES_ejs_web_Request_encoding                                    12
#define ES_ejs_web_Request_errorMessage                                13
#define ES_ejs_web_Request_files                                       14
#define ES_ejs_web_Request_filename                                    15
#define ES_ejs_web_Request_flash                                       16
#define ES_ejs_web_Request_headers                                     17
#define ES_ejs_web_Request_home                                        18
#define ES_ejs_web_Request_host                                        19
#define ES_ejs_web_Request_isSecure                                    20
#define ES_ejs_web_Request_limits                                      21
#define ES_ejs_web_Request_localAddress                                22
#define ES_ejs_web_Request_log                                         23
#define ES_ejs_web_Request_method                                      24
#define ES_ejs_web_Request_originalMethod                              25
#define ES_ejs_web_Request_originalUri                                 26
#define ES_ejs_web_Request_params                                      27
#define ES_ejs_web_Request_pathInfo                                    28
#define ES_ejs_web_Request_port                                        29
#define ES_ejs_web_Request_protocol                                    30
#define ES_ejs_web_Request_query                                       31
#define ES_ejs_web_Request_reference                                   32
#define ES_ejs_web_Request_referrer                                    33
#define ES_ejs_web_Request_remoteAddress                               34
#define ES_ejs_web_Request_responded                                   35
#define ES_ejs_web_Request_responseHeaders                             36
#define ES_ejs_web_Request_route                                       37
#define ES_ejs_web_Request_scheme                                      38
#define ES_ejs_web_Request_scriptName                                  39
#define ES_ejs_web_Request_server                                      40
#define ES_ejs_web_Request_session                                     41
#define ES_ejs_web_Request_sessionID                                   42
#define ES_ejs_web_Request_status                                      43
#define ES_ejs_web_Request_uri                                         44
#define ES_ejs_web_Request_async                                       45
#define ES_ejs_web_Request_autoFinalize                                46
#define ES_ejs_web_Request_close                                       47
#define ES_ejs_web_Request_checkSecurityToken                          48
#define ES_ejs_web_Request_createSession                               49
#define ES_ejs_web_Request_dontAutoFinalize                            50
#define ES_ejs_web_Request_destroySession                              51
#define ES_ejs_web_Request_error                                       52
#define ES_ejs_web_Request_extension                                   53
#define ES_ejs_web_Request_finalize                                    54
#define ES_ejs_web_Request_finalized                                   55
#define ES_ejs_web_Request_finalizeFlash                               56
#define ES_ejs_web_Request_flush                                       57
#define ES_ejs_web_Request_header                                      58
#define ES_ejs_web_Request_inform                                      59
#define ES_ejs_web_Request_link                                        60
#define ES_ejs_web_Request_makeUriHash                                 61
#define ES_ejs_web_Request_matchContent                                62
#define ES_ejs_web_Request_notify                                      63
#define ES_ejs_web_Request_on                                          64
#define ES_ejs_web_Request_read                                        65
#define ES_ejs_web_Request_redirect                                    66
#define ES_ejs_web_Request_removeObserver                              67
#define ES_ejs_web_Request_securityToken                               68
#define ES_ejs_web_Request_setCookie                                   69
#define ES_ejs_web_Request_setHeader                                   70
#define ES_ejs_web_Request_setHeaders                                  71
#define ES_ejs_web_Request_setLimits                                   72
#define ES_ejs_web_Request_setLocation                                 73
#define ES_ejs_web_Request_setStatus                                   74
#define ES_ejs_web_Request_setupFlash                                  75
#define ES_ejs_web_Request_show                                        76
#define ES_ejs_web_Request_trace                                       77
#define ES_ejs_web_Request_warn                                        78
#define ES_ejs_web_Request_write                                       79
#define ES_ejs_web_Request_writeContent                                80
#define ES_ejs_web_Request_writeError                                  81
#define ES_ejs_web_Request_writeFile                                   82
#define ES_ejs_web_Request_sendFile                                    83
#define ES_ejs_web_Request_writeResponse                               84
#define ES_ejs_web_Request_sendResponse                                85
#define ES_ejs_web_Request_writeSafe                                   86
#define ES_ejs_web_Request_written                                     87
#define ES_ejs_web_Request_env                                         88
#define ES_ejs_web_Request_input                                       89
#define ES_ejs_web_Request_queryString                                 90
#define ES_ejs_web_Request_serverPort                                  91
#define ES_ejs_web_Request_cache                                       92
#define ES_ejs_web_Request_NUM_INSTANCE_PROP                           93
#define ES_ejs_web_Request_NUM_INHERITED_PROP                          0


/*
    Class property slots for the "Router" type 
 */
#define ES_ejs_web_Router__initializer___Router_                       0
#define ES_ejs_web_Router_Restful                                      1
#define ES_ejs_web_Router_Direct                                       2
#define ES_ejs_web_Router_Handlers                                     3
#define ES_ejs_web_Router_Default                                      4
#define ES_ejs_web_Router_isDir                                        5
#define ES_ejs_web_Router_NUM_CLASS_PROP                               6

/*
   Prototype (instance) slots for "Router" type 
 */
#define ES_ejs_web_Router_routes                                       0
#define ES_ejs_web_Router_runners                                      1
#define ES_ejs_web_Router_addCatchall                                  2
#define ES_ejs_web_Router_addDirect                                    3
#define ES_ejs_web_Router_addHome                                      4
#define ES_ejs_web_Router_addResource                                  5
#define ES_ejs_web_Router_addResources                                 6
#define ES_ejs_web_Router_addRestful                                   7
#define ES_ejs_web_Router_addDefault                                   8
#define ES_ejs_web_Router_addHandlers                                  9
#define ES_ejs_web_Router_addBuilder                                   10
#define ES_ejs_web_Router_lookupRunners                                11
#define ES_ejs_web_Router_insertRoute                                  12
#define ES_ejs_web_Router_add                                          13
#define ES_ejs_web_Router_lookup                                       14
#define ES_ejs_web_Router_replace                                      15
#define ES_ejs_web_Router_remove                                       16
#define ES_ejs_web_Router_makeApp                                      17
#define ES_ejs_web_Router_route                                        18
#define ES_ejs_web_Router_show                                         19
#define ES_ejs_web_Router_showRoute                                    20
#define ES_ejs_web_Router_NUM_INSTANCE_PROP                            21
#define ES_ejs_web_Router_NUM_INHERITED_PROP                           0

/*
    Local slots for methods in type "Router" 
 */
#define ES_ejs_web_Router_isDir_request                                0


/*
    Class property slots for the "Route" type 
 */
#define ES_ejs_web_Route__initializer___Route_                         0
#define ES_ejs_web_Route_nameSeed                                      1
#define ES_ejs_web_Route_NUM_CLASS_PROP                                2

/*
   Prototype (instance) slots for "Route" type 
 */
#define ES_ejs_web_Route_limits                                        0
#define ES_ejs_web_Route_location                                      1
#define ES_ejs_web_Route_method                                        2
#define ES_ejs_web_Route_middleware                                    3
#define ES_ejs_web_Route_name                                          4
#define ES_ejs_web_Route_moduleName                                    5
#define ES_ejs_web_Route_params                                        6
#define ES_ejs_web_Route_rewrite                                       7
#define ES_ejs_web_Route_redirect                                      8
#define ES_ejs_web_Route_router                                        9
#define ES_ejs_web_Route_routeSetName                                  10
#define ES_ejs_web_Route_run                                           11
#define ES_ejs_web_Route_subroute                                      12
#define ES_ejs_web_Route_template                                      13
#define ES_ejs_web_Route_threaded                                      14
#define ES_ejs_web_Route_tokens                                        15
#define ES_ejs_web_Route_trace                                         16
#define ES_ejs_web_Route_match                                         17
#define ES_ejs_web_Route_pattern                                       18
#define ES_ejs_web_Route_splitter                                      19
#define ES_ejs_web_Route_getTemplate                                   20
#define ES_ejs_web_Route_inheritRoutes                                 21
#define ES_ejs_web_Route_compileTemplate                               22
#define ES_ejs_web_Route_matchAndSplit                                 23
#define ES_ejs_web_Route_matchRegExp                                   24
#define ES_ejs_web_Route_makeParams                                    25
#define ES_ejs_web_Route_parseOptions                                  26
#define ES_ejs_web_Route_setName                                       27
#define ES_ejs_web_Route_setRouteProperties                            28
#define ES_ejs_web_Route_NUM_INSTANCE_PROP                             29
#define ES_ejs_web_Route_NUM_INHERITED_PROP                            0
#define ES_ejs_web_Session_NUM_CLASS_PROP                              0

/*
   Prototype (instance) slots for "Session" type 
 */
#define ES_ejs_web_Session_NUM_INSTANCE_PROP                           0
#define ES_ejs_web_Session_NUM_INHERITED_PROP                          0
#define ES_ejs_web_UploadFile_NUM_CLASS_PROP                           0

/*
   Prototype (instance) slots for "UploadFile" type 
 */
#define ES_ejs_web_UploadFile_clientFilename                           0
#define ES_ejs_web_UploadFile_contentType                              1
#define ES_ejs_web_UploadFile_filename                                 2
#define ES_ejs_web_UploadFile_name                                     3
#define ES_ejs_web_UploadFile_size                                     4
#define ES_ejs_web_UploadFile_NUM_INSTANCE_PROP                        5
#define ES_ejs_web_UploadFile_NUM_INHERITED_PROP                       0


/*
    Class property slots for the "View" type 
 */
#define ES_ejs_web_View_dateFormatter                                  0
#define ES_ejs_web_View_plainFormatter                                 1
#define ES_ejs_web_View_NUM_CLASS_PROP                                 2

/*
   Prototype (instance) slots for "View" type 
 */
#define ES_ejs_web_View_connectors                                     0
#define ES_ejs_web_View_currentRecord                                  1
#define ES_ejs_web_View_formats                                        2
#define ES_ejs_web_View_config                                         3
#define ES_ejs_web_View_controller                                     4
#define ES_ejs_web_View_params                                         5
#define ES_ejs_web_View_request                                        6
#define ES_ejs_web_View_ejs_web_render                                 7
#define ES_ejs_web_View_ejs_web_alert                                  8
#define ES_ejs_web_View_ejs_web_anchor                                 9
#define ES_ejs_web_View_ejs_web_button                                 10
#define ES_ejs_web_View_ejs_web_buttonLink                             11
#define ES_ejs_web_View_ejs_web_chart                                  12
#define ES_ejs_web_View_ejs_web_checkbox                               13
#define ES_ejs_web_View_ejs_web_div                                    14
#define ES_ejs_web_View_ejs_web_endform                                15
#define ES_ejs_web_View_ejs_web_flash                                  16
#define ES_ejs_web_View_ejs_web_form                                   17
#define ES_ejs_web_View_ejs_web_icon                                   18
#define ES_ejs_web_View_ejs_web_image                                  19
#define ES_ejs_web_View_ejs_web_input                                  20
#define ES_ejs_web_View_ejs_web_label                                  21
#define ES_ejs_web_View_ejs_web_list                                   22
#define ES_ejs_web_View_ejs_web_mail                                   23
#define ES_ejs_web_View_ejs_web_progress                               24
#define ES_ejs_web_View_ejs_web_radio                                  25
#define ES_ejs_web_View_ejs_web_script                                 26
#define ES_ejs_web_View_ejs_web_securityToken                          27
#define ES_ejs_web_View_ejs_web_stylesheet                             28
#define ES_ejs_web_View_ejs_web_table                                  29
#define ES_ejs_web_View_ejs_web_tabs                                   30
#define ES_ejs_web_View_ejs_web_text                                   31
#define ES_ejs_web_View_ejs_web_textarea                               32
#define ES_ejs_web_View_ejs_web_tree                                   33
#define ES_ejs_web_View_ejs_web_view                                   34
#define ES_ejs_web_View_ejs_web_link                                   35
#define ES_ejs_web_View_ejs_web_redirect                               36
#define ES_ejs_web_View_ejs_web_session                                37
#define ES_ejs_web_View_ejs_web_setHeader                              38
#define ES_ejs_web_View_ejs_web_setHeaders                             39
#define ES_ejs_web_View_ejs_web_setStatus                              40
#define ES_ejs_web_View_ejs_web_show                                   41
#define ES_ejs_web_View_ejs_web_toplink                                42
#define ES_ejs_web_View_ejs_web_write                                  43
#define ES_ejs_web_View_ejs_web_writeSafe                              44
#define ES_ejs_web_View_ejs_web_formatValue                            45
#define ES_ejs_web_View_getConnector                                   46
#define ES_ejs_web_View_getFieldName                                   47
#define ES_ejs_web_View_getOptions                                     48
#define ES_ejs_web_View_ejs_web_getValue                               49
#define ES_ejs_web_View_pivot                                          50
#define ES_ejs_web_View_ejs_web_formatters                             51
#define ES_ejs_web_View_ejs_web_date                                   52
#define ES_ejs_web_View_ejs_web_currency                               53
#define ES_ejs_web_View_ejs_web_number                                 54
#define ES_ejs_web_View_NUM_INSTANCE_PROP                              55
#define ES_ejs_web_View_NUM_INHERITED_PROP                             0

/*
    Local slots for methods in type "View" 
 */
#define ES_ejs_web_View_dateFormatter_view                             0
#define ES_ejs_web_View_dateFormatter_value                            1
#define ES_ejs_web_View_dateFormatter_options                          2
#define ES_ejs_web_View_plainFormatter_view                            0
#define ES_ejs_web_View_plainFormatter_value                           1
#define ES_ejs_web_View_plainFormatter_options                         2


/*
    Class property slots for the "Web" type 
 */
#define ES_ejs_web_Web__initializer___Web_                             0
#define ES_ejs_web_Web_config                                          1
#define ES_ejs_web_Web_defaultConfig                                   2
#define ES_ejs_web_Web_init                                            3
#define ES_ejs_web_Web_serve                                           4
#define ES_ejs_web_Web_worker                                          5
#define ES_ejs_web_Web_workerHelper                                    6
#define ES_ejs_web_Web_processBody                                     7
#define ES_ejs_web_Web_process                                         8
#define ES_ejs_web_Web_start                                           9
#define ES_ejs_web_Web_run                                             10
#define ES_ejs_web_Web_NUM_CLASS_PROP                                  11

/*
   Prototype (instance) slots for "Web" type 
 */
#define ES_ejs_web_Web_NUM_INSTANCE_PROP                               0
#define ES_ejs_web_Web_NUM_INHERITED_PROP                              0

/*
    Local slots for methods in type "Web" 
 */
#define ES_ejs_web_Web_serve_request                                   0
#define ES_ejs_web_Web_serve_router                                    1
#define ES_ejs_web_Web_worker_app                                      0
#define ES_ejs_web_Web_worker_request                                  1
#define ES_ejs_web_Web_workerHelper_app                                0
#define ES_ejs_web_Web_workerHelper_request                            1
#define ES_ejs_web_Web_processBody_request                             0
#define ES_ejs_web_Web_processBody_body                                1
#define ES_ejs_web_Web_process_app                                     0
#define ES_ejs_web_Web_process_request                                 1
#define ES_ejs_web_Web_process_finalize                                2
#define ES_ejs_web_Web_start_address                                   0
#define ES_ejs_web_Web_start_documentRoot                              1
#define ES_ejs_web_Web_start_serverRoot                                2
#define ES_ejs_web_Web_start_routes                                    3
#define ES_ejs_web_Web_run_address                                     0
#define ES_ejs_web_Web_run_documentRoot                                1
#define ES_ejs_web_Web_run_serverRoot                                  2

#define _ES_CHECKSUM_ejs_web   806304

#endif
