/*
   ejs.store.local.slots.h -- Native property slot definitions for the "ejs.store.local" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsStoreLocalSlots
#define _h_SLOTS_EjsStoreLocalSlots 1


/*
   Slots for the "ejs.store.local" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Local" type 
 */
#define ES_ejs_store_local_Local_NUM_CLASS_PROP                        0

/*
   Prototype (instance) slots for "Local" type 
 */
#define ES_ejs_store_local_Local_destroy                               0
#define ES_ejs_store_local_Local_expire                                1
#define ES_ejs_store_local_Local_limits                                2
#define ES_ejs_store_local_Local_read                                  3
#define ES_ejs_store_local_Local_remove                                4
#define ES_ejs_store_local_Local_setLimits                             5
#define ES_ejs_store_local_Local_write                                 6
#define ES_ejs_store_local_Local_NUM_INSTANCE_PROP                     7
#define ES_ejs_store_local_Local_NUM_INHERITED_PROP                    0

#define _ES_CHECKSUM_ejs_store_local   14675

#endif
