#
#	Makefile for master includes
#
#	Copyright (c) Embedthis Software LLC, 2003-2010. All Rights Reserved.
#

include 		.makedep

import:
	@for f in *slots* ; do \
		echo cp ../$$f . ; \
		cp ../$$f . ; \
	done

