/*
    bit.h -- Build It Configuration Header for solaris-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

/* Settings */
#define BIT_BUILD_NUMBER "0"
#define BIT_COMPANY "Embedthis"
#define BIT_DEPTH 1
#define BIT_HAS_DOUBLE_BRACES 1
#define BIT_HAS_DYN_LOAD 1
#define BIT_HAS_LIB_EDIT 0
#define BIT_HAS_MMU 1
#define BIT_HAS_MTUNE 1
#define BIT_HAS_PAM 0
#define BIT_HAS_STACK_PROTECTOR 1
#define BIT_HAS_SYNC 0
#define BIT_HAS_SYNC_CAS 0
#define BIT_HAS_UNNAMED_UNIONS 1
#define BIT_MANAGER "ejsman"
#define BIT_MINIMAL "doxygen,dsi,man,man2html,ssl,zlib"
#define BIT_OPTIONAL "doxygen,dsi,man,man2html,openssl,matrixssl,pmaker,sqlite,ssl,zlib,zip"
#define BIT_PACKS "bits/packs"
#define BIT_PLATFORMS "local"
#define BIT_PRODUCT "ejs"
#define BIT_REQUIRED "compiler,link,pcre"
#define BIT_SYNC "http,mpr,pcre,sqlite"
#define BIT_TITLE "Embedthis Ejscript"
#define BIT_VERSION "2.0.1"
#define BIT_WARN64TO32 0
#define BIT_WARN_UNUSED 0

/* Prefixes */
#define BIT_CFG_PREFIX "/etc/ejs"
#define BIT_BIN_PREFIX "/usr/lib/ejs/2.0.1/bin"
#define BIT_INC_PREFIX "/usr/lib/ejs/2.0.1/inc"
#define BIT_LOG_PREFIX "/var/log/ejs"
#define BIT_PRD_PREFIX "/usr/lib/ejs"
#define BIT_SPL_PREFIX "/var/spool/ejs"
#define BIT_SRC_PREFIX "/usr/src/ejs-2.0.1"
#define BIT_VER_PREFIX "/usr/lib/ejs/2.0.1"
#define BIT_WEB_PREFIX "/var/www/ejs-default"

/* Suffixes */
#define BIT_EXE ""
#define BIT_SHLIB ".so"
#define BIT_SHOBJ ".so"
#define BIT_LIB ".a"
#define BIT_OBJ ".o"

/* Profile */
#define BIT_EJS_PRODUCT 1
#define BIT_PROFILE "debug"
#define BIT_CONFIG_CMD "bit -d -q -platform solaris-x86 -without all -configure . -gen sh,make"

/* Miscellaneous */
#define BIT_MAJOR_VERSION 2
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 1
#define BIT_VNUM 200000001

/* Packs */
#define BIT_PACK_CC 1
#define BIT_PACK_DOXYGEN 0
#define BIT_PACK_DSI 0
#define BIT_PACK_LINK 1
#define BIT_PACK_MAN 0
#define BIT_PACK_MAN2HTML 0
#define BIT_PACK_MATRIXSSL 0
#define BIT_PACK_OPENSSL 0
#define BIT_PACK_PCRE 1
#define BIT_PACK_PMAKER 1
#define BIT_PACK_SQLITE 1
#define BIT_PACK_SSL 0
#define BIT_PACK_ZIP 1
#define BIT_PACK_ZLIB 0
