  
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/ejscript/">Ejscript Site</a>
                    <a class="item" href="http://goo.gl/dGRDl4">Ejscript News</a>
                    <a class="item" href="https://github.com/embedthis/ejs">Repository</a>
                    <a class="item" href="https://embedthis.com/blog/">Blog</a>
                    <a class="item" href="https://twitter.com/mobstream">Twitter</a>
