
                    <a class="item" href="https://www.embedthis.com/">Embedthis</a>
                    <a class="item" href="https://www.embedthis.com/ejscript/">Ejscript Site</a>
                    <span class="desktop-only">
                        <a class="item" href="https://www.embedthis.com/blog/categories/Ejscript/">Ejscript News</a>
                        <a class="item" href="https://github.com/embedthis/ejs">Repository</a>
                        <a class="item" href="https://www.embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/embedthat">Twitter</a>
                    </span>
