str = '{
  "bin": "/Users/mob/hg/mpr/bin",
  "dir": ".",
  "depth": 1,
  "lib": "/Users/mob/hg/mpr/lib",
  "os": "MACOSX",
  "top": "/Users/mob/hg/mpr",
  "verbosity": 1,
  "session": {
  },
  "config": {
    "assert": 1,
    "cmd": 1,
    "complete_native": 1,
    "complete_cross": 0,
    "doc": 1,
    "device": "PocketPC2003",
    "floating_point": 1,
    "legacy_api": 0,
    "multithread": 1,
    "num_type": ",
    "poll": 1,
    "samples": 1,
    "test": 1,
    "vmalloc": 1,
    "static": 0,
    "decimal": 0,
    "http": 1,
    "http_client": 1,
    "romfs": 0,
    "xml": 1,
    "ar": 1,
    "cc": 1,
    "make": 1,
    "nm": 1,
    "ranlib": 1,
    "doxygen": 1,
    "mpr": 1,
    "regexp": 1,
    "matrixssl": 1,
    "openssl": 1,
    "ssl": 1,
  },
  "setup": {
  },
}'
