/*
   composite.slots.h -- Native property slot definitions for the "composite" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_CompositeSlots
#define _h_SLOTS_CompositeSlots 1


/*
   Slots for the "composite" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Square" type 
 */
#define ES_composite_Square_NUM_CLASS_PROP                             0

/*
   Prototype (instance) slots for "Square" type 
 */
#define ES_composite_Square_x                                          0
#define ES_composite_Square_y                                          1
#define ES_composite_Square_height                                     2
#define ES_composite_Square_width                                      3
#define ES_composite_Square_area                                       4
#define ES_composite_Square_moveTo                                     5
#define ES_composite_Square_NUM_INSTANCE_PROP                          6
#define ES_composite_Square_NUM_INHERITED_PROP                         0

#define _ES_CHECKSUM_composite   8009

#endif
