<!DOCTYPE html>
<html lang="eng">
<head>
<title>Ejs Man Page</title>
</head>
<HTML>
<BODY>
<PRE>
<!-- Manpage converted by man2html 3.0.1 -->


</PRE>
<H2>SYNOPSIS</H2><PRE>
       <B>ejs</B>
           <B>--class</B> <B>className</B>
           <B>--cmd</B> <B>literalScript</B>
           <B>--debug</B>
           <B>--files</B> <B>"files..."</B>
           <B>--log</B> <B>logSpec</B>
           <B>--method</B> <B>methodName</B>
           <B>--nodebug</B>
           <B>--optimize</B> <B>level</B>
           <B>--search</B> <B>ejsPath</B>
           <B>--standard</B>
           <B>--stats</B>
           <B>--strict</B>
           <B>--use</B> <B>'module,</B> <B>...'</B>
           <B>--version</B>
           <B>--warn</B> <B>level</B>
           <B>file</B> <B>[arguments</B> <B>...]</B>


</PRE>
<H2>DESCRIPTION</H2><PRE>
       The <B>ejs</B> command is an Ejscript command shell that can interpret and run
       JavaScript programs.

       Ejscript  is  an enhanced implementation of the JavaScript language for
       use in embedded applications such as web servers, embedded devices  and
       mobile  phones. It is especially well suited for Server-Side JavaScript
       web applications.


</PRE>
<H2>INVOCATION</H2><PRE>
       The <B>ejs</B> command can be used as a shell to interactively interpret  com-
       mands typed at the console or to run script files. When invoked with no
       files on the command line, <B>ejs</B> runs in interactive mode.   In  interac-
       tive  mode,  <B>ejs</B>  reads  input from the console and parses and executes
       script code as it is entered. In this mode, <B>ejs</B> command will read input
       until  it has a complete block of code and will then execute the block.
       The last result value computed will be echoed to the console. For exam-
       ple:

       ejs-0&gt;; if (true) {
       ejs-2&gt;;     print("Hello World");
       ejs-2&gt;; }
       Hello World

       ejs-0&gt;;

       Note:  the  input prompt includes a level of nest indicator starting at
       zero and increasing upward as commands nest. This is a hint as to  when
       you  have  closed sufficient braces for <B>ejs</B> to execute your command. As
       this is an internal compiler nest value, it  will  sometimes  increment
       more than 1 for each brace.

       The  <B>ejs</B>  command  can also invoke a specific static method on startup.
       If either the --class or --method switches are supplied, then <B>ejs</B>  will
       run  the requested static method after the input file script statements
       have been executed.


</PRE>
<H2>COMPLIANCE</H2><PRE>
       Ejscript is fully compliant with the JavaScript  (ECMA-262  3.X)  stan-
       dards,  but  it also offers a set of enhancements and fixes designed to
       improve the language and correct some  longstanding  JavaScript  design
       issues.



</PRE>
<H2>OPTIONS</H2><PRE>
       <B>--class</B> <B>className</B>
              Use  the  given  className when searching for the startup method
              specified via --method or "main" by default.

       <B>--cmd</B> <B>literalCommand</B>
              Evaluate a literal command string.

       <B>--debug</B>
              Run in debug mode and  generate  symbolic  stack  backtraces  if
              required.

       <B>--files</B> <B>"files</B> <B>..."</B>
              Specifies  an extra set of files to be compiled. The <B>ejs</B> command
              normally takes just one script file on the  command  line.   The
              --files switch allows extra script to be compiled after the pri-
              mary script, but before the scripts are run.

       <B>--log</B> <B>logName[:logLevel]</B>
              Specify a file to log internal execution messages. Ejs will  log
              execution related trace to the log file. The log level specifies
              the desired verbosity of output. Level 0 is  the  least  verbose
              and  level  9  is  the  most. Level 2 will include trace of each
              source statement and assembler  instruction  executed  (provided
              --nodebug is not specifiec).

       <B>---method</B> <B>methodName</B>
              Set the startup method name. Defaults to "main" if a --className
              is specified and --method is not.

       <B>--nodebug</B>
              Run the script without debug information. This  will  result  in
              exceptions not having symbolic stack backtraces.

       <B>--optimize</B> <B>level</B>
              Set  the code optimization level. Level values must be between 0
              (least) and 9 (most). Default is level 9.

       <B>--search</B> <B>ejsPath</B>
              Set the module search path. The module search path is a  set  of

              1. Search for a module file named "a.b.c.mod"

              2. Search for a module file named "a/b/c.mod"

              3. Search for a module file named "a.b.c.mod" in the search path

              4. Search for a module file named c.mod in the search path

       <B>--standard</B>
              Run  scripts  in  standard  mode.  Ejscript supports two parsing
              modes: strict and standard. Standard mode does not require vari-
              ables be declared and typed before use.

       <B>--stats</B>
              Print various statistics on exit.

       <B>--strict</B>
              Run  scripts  in  standard  mode.  Ejscript supports two parsing
              modes: strict and standard. Strict mode requires that all  vari-
              ables be declared and typed.

       <B>--use</B> <B>'module,</B> <B>...'</B>
              List of modules to preload before compiling input files.

       <B>--warn</B> <B>level</B>
              Set  the  compiler warning verbosity level. Level values must be
              between 0 (least verbose) and 9 (most). Default is 0.

       <B>--version</B>
              Print the <B>ejs</B> command version and exit.



</PRE>
<H2>REPORTING BUGS</H2><PRE>
       Report bugs to dev@embedthis.com.


</PRE>
<H2>COPYRIGHT</H2><PRE>
       Copyright (C) Embedthis Software. Ejscript is a trademark of  Embedthis
       Software.


</PRE>
<H2>SEE ALSO</H2><PRE>
       ejsc, ejsmod



ejs                               March 2014                            <B>EJS(1)</B>
</PRE>
<HR>
<ADDRESS>
Man(1) output converted with
<a href="http://www.oac.uci.edu/indiv/ehood/man2html.html">man2html</a>
</ADDRESS>
</BODY>
</HTML>
</html>