<!DOCTYPE html>
<html lang="eng">
<head>
<title>Manager Man Page</title>
</head>
<HTML>
<BODY>
<PRE>
<!-- Manpage converted by man2html 3.0.1 -->

</PRE>
<H2>SYNOPSIS</H2><PRE>
       <B>manager</B> <B>[options]</B> <B>[commands]</B>
              [<I>--args</I> <I>arguments</I>] [<I>--console</I>] [<I>--daemon</I>] [<I>--heartBeat</I> <I>interval</I>]
              [<I>--home</I> <I>directory</I>] [<I>--log</I> <I>logFile:level</I>] [<I>--name</I>  <I>Service</I>  <I>name</I>]
              [<I>--pidfile</I> <I>path</I>] [<I>--program</I> <I>Service</I> <I>program</I>]


</PRE>
<H2>DESCRIPTION</H2><PRE>
       The manager program is used to configure the running of system services
       (daemons).   Manager  provides  a  generic  way  to  install/uninstall,
       enable/disable,  start/stop, and run a service, regardless of the oper-
       ating system. When used to run a service, it  starts  the  service  and
       then  watches  over it, to restart it should it fail. Manager also pro-
       vides general management commands to enable, disable, start,  and  stop
       appweb.


</PRE>
<H2>COMMANDS</H2><PRE>
       <B>disable</B>
              Disable  the service from automatically starting when the system
              is booted.

       <B>enable</B> Enable the service to start automatically on system boot.

       <B>install</B>
              Install the service.

       <B>run</B>    Run the service and monitor its execution. Manager will automat-
              ically  restart  the service should it fail.  Manager will block
              unless it is invoked with --daemon.

       <B>start</B>  Start the service.

       <B>stop</B>   Stop the service.

       <B>uninstall</B>
              Uninstall the service.


</PRE>
<H2>OPTIONS</H2><PRE>
       <B>--args</B> <B>arguments</B>
              Arguments to use for the service program command  line  when  it
              starts.

       <B>--console</B>
              Windows specific option to allow the manager process to interact
              with the users desktop.

       <B>--daemon</B>
              Run the manager as a daemon process. This causes the manager  to
              detach from the current shell and run in the background.

       <B>--heartBeat</B> <B>interval</B>
              Windows  specific option to set the frequency in seconds for the
              manager to check on service.  This period should be short enough
              Number of times to restart the service per hour.

       <B>-v</B>     Output the product version number.



</PRE>
<H2>REPORTING BUGS</H2><PRE>
       Report bugs to dev@embedthis.com.


</PRE>
<H2>COPYRIGHT</H2><PRE>
       Copyright (C) Embedthis Software.


</PRE>
<H2>SEE ALSO</H2><PRE>
       appweb



manager                          November 2014                      <B>MANAGER(1)</B>
</PRE>
<HR>
<ADDRESS>
Man(1) output converted with
<a href="http://www.oac.uci.edu/indiv/ehood/man2html.html">man2html</a>
</ADDRESS>
</BODY>
</HTML>
</html>