#!/bin/sh
# 	postinst -- Post installation script for Ejscript
#
#	Copyright (c) Embedthis Software LLC, 2003-2012. All Rights Reserved.
#

BLD_PRODUCT=${settings.product}
BLD_NAME="${settings.title}
BLD_BIN_PREFIX="${prefixes.bin}"

###############################################################################
#
#	Main
#

cd /
action=$1

case $action in
	configure)							# when new
        "$BLD_BIN_PREFIX/linkup" Install /
        echo
		echo "$BLD_NAME installation successful."
		;;
	abort-upgrade)						# when old
		;;
	abort-remove)
		# 	sometimes conflictor's-postinst abort-remove in-favor package new-version
		;;
esac
exit 0
