#!/bin/sh
# 	prerm -- Pre removal script for Ejscript
#
#	Copyright (c) Embedthis Software LLC, 2003-2012. All Rights Reserved.
#

BLD_PRODUCT=${settings.product}
BLD_NAME="${settings.title}"
BLD_BIN_PREFIX="${prefixes.bin}"
BLD_CFG_PREFIX="${prefixes.config}"

###############################################################################
#
#	Main
#
cd /
action=$1
case $action in
	remove)					# when new
        "$BLD_BIN_PREFIX/linkup" Remove /
		;;
	upgrade)				# when old
        "$BLD_BIN_PREFIX/linkup" Remove /
		;;
	failed-upgrade)			# when new
		oldVersion=$2
		;;
	deconfigure)			# when old
		# 	deconfigure in-favor package-being-installed version removing 
		#	conflicting-package version
esac
exit 0
