compile:
	ejsc --out modules/sample.mod src/*.es

all: compile build install

build:
	../../jem create

install:
	cp sample.jem ../../local

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4
#
