#
#	Clean assist for Xcode
#
DIR			:= 

include 	.makedep

all:

cleanExtra:
	rm -fr */build 

#rm -f $(DIR)/*.mod $(DIR)/ejsweb $(DIR)/ejspage $(DIR)/jem

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4
#
