#
#	Makefile for the Ejscript Compiler library
#
#	Copyright (c) Embedthis Software LLC, 2003-2010. All Rights Reserved.
#

include 		.makedep

#	EC_LIB			+= $(BLD_LIB_DIR)/libec$(BLD_LIB)
#	ifeq	($(BUILDING_CROSS),1)
#		ifeq	($(BLD_FEATURE_EJS_CROSS_COMPILER),1)
#			TARGETS	+= $(EC_LIB)
#		endif
#	else
#		TARGETS		+= $(EC_LIB)
#	endif
#	
#	compileExtra: 	$(TARGETS)
#	
#	$(EC_LIB): $(OBJECTS)
#		bld --library $(EC_LIB) --search "$(BLD_EJS_LIBPATHS) $(BLD_EJS_WITHPATHS)" \
#			--libs "$(BLD_EJS_LIBS) $(BLD_EJS_WITHLIBS)" $(OBJECTS)
