#!/bin/bash
#
#	postflight -- Post flight script for documentation
#	Copyright (c) Embedthis Software LLC, 2003-2010. All Rights Reserved.
#
###############################################################################

PKG_DIR="$1"
INS_DIR="$2"
NAME="!!BLD_DOC_PREFIX!!"
BIN="!!ORIG_BLD_BIN_PREFIX!!"
path="${INS_DIR}${NAME}"

${BIN}/linkup Install

if [ -z "$COMMAND_LINE_INSTALL" ] ; then
    if [ -f "$path/index.html" ] ; then
        open "$path/index.html"
    fi
fi
exit 0
