/*
   default.slots.h -- Native property slot definitions for the "default" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.3.3.
 */

#ifndef _h_SLOTS_DefaultSlots
#define _h_SLOTS_DefaultSlots 1


/*
   Slots for the "default" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

#define _ES_CHECKSUM_default   2363

#endif
