/*
   ejs.web.slots.h -- Native property slot definitions for the "ejs.web" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.2.0.
 */

#ifndef _h_SLOTS_EjsWebSlots
#define _h_SLOTS_EjsWebSlots 1


/*
   Slots for the "ejs.web" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_ejs_web_Cascade_apps                                        0
#define ES_ejs_web_CommonLog_app                                       0
#define ES_ejs_web_CommonLog_logger                                    1
#define ES_ejs_web_ContentType_app                                     0
#define ES_ejs_web_ContentType_options                                 1
#define ES_ejs_web_DirApp_request                                      0
#define ES_ejs_web_Head_app                                            0
#define ES_ejs_web_MethodOverride_app                                  0
#define ES_ejs_web_Middleware_app                                      0
#define ES_ejs_web_Middleware_middleware                               1
#define ES_ejs_web_MvcApp_request                                      0
#define ES_ejs_web_MvcBuilder_request                                  0
#define ES_ejs_web_ScriptApp_request                                   0
#define ES_ejs_web_ScriptBuilder_request                               0
#define ES_ejs_web_ShowExceptions_app                                  0
#define ES_ejs_web_StaticApp_request                                   0
#define ES_ejs_web_StaticBuilder_request                               0
#define ES_ejs_web_TemplateFilter_app                                  0
#define ES_ejs_web_TemplateApp_request                                 0
#define ES_ejs_web_TemplateBuilder_request                             0
#define ES_ejs_web_TemplateBuilder_options                             1
#define ES_ejs_web_UrlMap_map                                          0
#define ES_ejs_web_UrlMap_options                                      1
#define ES_ejs_web_errorBody_title                                     0
#define ES_ejs_web_errorBody_msg                                       1
#define ES_ejs_web_parseCookies_cookieHeader                           0
#define ES_ejs_web_escapeHtml_str                                      0
#define ES_ejs_web_html_args                                           0
#define ES_ejs_web_unescapeHtml_s                                      0


/*
    Class property slots for the "CommonLogClass" type 
 */
#define ES_ejs_web_CommonLogClass_NUM_CLASS_PROP                       0

/*
   Prototype (instance) slots for "CommonLogClass" type 
 */
#define ES_ejs_web_CommonLogClass_innerApp                             0
#define ES_ejs_web_CommonLogClass_logger                               1
#define ES_ejs_web_CommonLogClass_app                                  2
#define ES_ejs_web_CommonLogClass_NUM_INSTANCE_PROP                    3
#define ES_ejs_web_CommonLogClass_NUM_INHERITED_PROP                   0


/*
    Class property slots for the "Controller" type 
 */
#define ES_ejs_web_Controller__initializer___Controller_               0
#define ES_ejs_web_Controller__allOptions                              1
#define ES_ejs_web_Controller_ejs_web_create                           2
#define ES_ejs_web_Controller_ejs_web_cache                            3
#define ES_ejs_web_Controller_ejs_web_updateCache                      4
#define ES_ejs_web_Controller_getCacheIndex                            5
#define ES_ejs_web_Controller_NUM_CLASS_PROP                           6

/*
   Prototype (instance) slots for "Controller" type 
 */
#define ES_ejs_web_Controller__afterCheckers                           0
#define ES_ejs_web_Controller__beforeCheckers                          1
#define ES_ejs_web_Controller_ejs_web_actionName                       2
#define ES_ejs_web_Controller_ejs_web_config                           3
#define ES_ejs_web_Controller_ejs_web_controllerName                   4
#define ES_ejs_web_Controller_ejs_web_log                              5
#define ES_ejs_web_Controller_ejs_web_params                           6
#define ES_ejs_web_Controller_ejs_web_request                          7
#define ES_ejs_web_Controller_ejs_web_cacheIndex                       8
#define ES_ejs_web_Controller_ejs_web_cacheOptions                     9
#define ES_ejs_web_Controller_ejs_web_cacheName                        10
#define ES_ejs_web_Controller_ejs_web_cacheItem                        11
#define ES_ejs_web_Controller_ejs_web_absHome                          12
#define ES_ejs_web_Controller_ejs_web_home                             13
#define ES_ejs_web_Controller_ejs_web_pathInfo                         14
#define ES_ejs_web_Controller_ejs_web_session                          15
#define ES_ejs_web_Controller_ejs_web_uri                              16
#define ES_ejs_web_Controller_ejs_web_after                            17
#define ES_ejs_web_Controller_cacheTag                                 18
#define ES_ejs_web_Controller_fetchCachedResponse                      19
#define ES_ejs_web_Controller_saveCachedResponse                       20
#define ES_ejs_web_Controller_ejs_web_writeCached                      21
#define ES_ejs_web_Controller_ejs_web_app                              22
#define ES_ejs_web_Controller_ejs_web_autoFinalize                     23
#define ES_ejs_web_Controller_ejs_web_autoFinalizing                   24
#define ES_ejs_web_Controller_ejs_web_before                           25
#define ES_ejs_web_Controller_ejs_web_clearFlash                       26
#define ES_ejs_web_Controller_getCacheName                             27
#define ES_ejs_web_Controller_ejs_web_dontAutoFinalize                 28
#define ES_ejs_web_Controller_ejs_web_error                            29
#define ES_ejs_web_Controller_ejs_web_finalize                         30
#define ES_ejs_web_Controller_ejs_web_finalized                        31
#define ES_ejs_web_Controller_ejs_web_flash                            32
#define ES_ejs_web_Controller_ejs_web_flush                            33
#define ES_ejs_web_Controller_ejs_web_header                           34
#define ES_ejs_web_Controller_ejs_web_inform                           35
#define ES_ejs_web_Controller_ejs_web_link                             36
#define ES_ejs_web_Controller_action_missing                           37
#define ES_ejs_web_Controller_ejs_web_notify                           38
#define ES_ejs_web_Controller_ejs_web_on                               39
#define ES_ejs_web_Controller_ejs_web_read                             40
#define ES_ejs_web_Controller_ejs_web_redirect                         41
#define ES_ejs_web_Controller_ejs_web_removeCheckers                   42
#define ES_ejs_web_Controller_ejs_web_setHeader                        43
#define ES_ejs_web_Controller_ejs_web_setHeaders                       44
#define ES_ejs_web_Controller_ejs_web_setStatus                        45
#define ES_ejs_web_Controller_ejs_web_write                            46
#define ES_ejs_web_Controller_ejs_web_warn                             47
#define ES_ejs_web_Controller_ejs_web_writeContent                     48
#define ES_ejs_web_Controller_ejs_web_writeError                       49
#define ES_ejs_web_Controller_ejs_web_writeFile                        50
#define ES_ejs_web_Controller_ejs_web_writePartialTemplate             51
#define ES_ejs_web_Controller_ejs_web_writeView                        52
#define ES_ejs_web_Controller_ejs_web_writeTemplate                    53
#define ES_ejs_web_Controller_ejs_web_writeTemplateLiteral             54
#define ES_ejs_web_Controller_checkSecurityToken                       55
#define ES_ejs_web_Controller_runCheckers                              56
#define ES_ejs_web_Controller_viewExists                               57
#define ES_ejs_web_Controller_NUM_INSTANCE_PROP                        58
#define ES_ejs_web_Controller_NUM_INHERITED_PROP                       0

/*
    Local slots for methods in type "Controller" 
 */
#define ES_ejs_web_Controller_ejs_web_create_request                   0
#define ES_ejs_web_Controller_ejs_web_create_cname                     1
#define ES_ejs_web_Controller_ejs_web_cache_controller                 0
#define ES_ejs_web_Controller_ejs_web_cache_actions                    1
#define ES_ejs_web_Controller_ejs_web_cache_options                    2
#define ES_ejs_web_Controller_ejs_web_updateCache_controller           0
#define ES_ejs_web_Controller_ejs_web_updateCache_actions              1
#define ES_ejs_web_Controller_ejs_web_updateCache_data                 2
#define ES_ejs_web_Controller_ejs_web_updateCache_options              3
#define ES_ejs_web_Controller_getCacheIndex_cname                      0
#define ES_ejs_web_Controller_getCacheIndex_name                       1


/*
    Class property slots for the "HtmlViewConnector" type 
 */
#define ES_HtmlViewConnector__initializer___HtmlViewConnector_         0
#define ES_HtmlViewConnector_lastDomID                                 1
#define ES_HtmlViewConnector_htmlOptions                               2
#define ES_HtmlViewConnector_defaultStylesheets                        3
#define ES_HtmlViewConnector_defaultScripts                            4
#define ES_HtmlViewConnector_NUM_CLASS_PROP                            5

/*
   Prototype (instance) slots for "HtmlViewConnector" type 
 */
#define ES_HtmlViewConnector_request                                   0
#define ES_HtmlViewConnector_view                                      1
#define ES_HtmlViewConnector_ejs_web_alert                             2
#define ES_HtmlViewConnector_ejs_web_anchor                            3
#define ES_HtmlViewConnector_ejs_web_button                            4
#define ES_HtmlViewConnector_ejs_web_buttonLink                        5
#define ES_HtmlViewConnector_ejs_web_chart                             6
#define ES_HtmlViewConnector_ejs_web_checkbox                          7
#define ES_HtmlViewConnector_ejs_web_div                               8
#define ES_HtmlViewConnector_ejs_web_endform                           9
#define ES_HtmlViewConnector_ejs_web_flash                             10
#define ES_HtmlViewConnector_ejs_web_form                              11
#define ES_HtmlViewConnector_ejs_web_icon                              12
#define ES_HtmlViewConnector_ejs_web_image                             13
#define ES_HtmlViewConnector_ejs_web_label                             14
#define ES_HtmlViewConnector_ejs_web_list                              15
#define ES_HtmlViewConnector_ejs_web_mail                              16
#define ES_HtmlViewConnector_ejs_web_progress                          17
#define ES_HtmlViewConnector_ejs_web_radio                             18
#define ES_HtmlViewConnector_ejs_web_refresh                           19
#define ES_HtmlViewConnector_ejs_web_script                            20
#define ES_HtmlViewConnector_ejs_web_securityToken                     21
#define ES_HtmlViewConnector_ejs_web_stylesheet                        22
#define ES_HtmlViewConnector_ejs_web_table                             23
#define ES_HtmlViewConnector_ejs_web_tabs                              24
#define ES_HtmlViewConnector_ejs_web_text                              25
#define ES_HtmlViewConnector_ejs_web_tree                              26
#define ES_HtmlViewConnector_emitFormErrors                            27
#define ES_HtmlViewConnector_setKeyFields                              28
#define ES_HtmlViewConnector_ejs_web_getAttributes                     29
#define ES_HtmlViewConnector_getColumns                                30
#define ES_HtmlViewConnector_getTextKind                               31
#define ES_HtmlViewConnector_getNextID                                 32
#define ES_HtmlViewConnector_mapAttributes                             33
#define ES_HtmlViewConnector_setLinkOptions                            34
#define ES_HtmlViewConnector_write                                     35
#define ES_HtmlViewConnector_append                                    36
#define ES_HtmlViewConnector_NUM_INSTANCE_PROP                         37
#define ES_HtmlViewConnector_NUM_INHERITED_PROP                        0


/*
    Class property slots for the "HttpServer" type 
 */
#define ES_ejs_web_HttpServer__initializer___HttpServer_               0
#define ES_ejs_web_HttpServer_PrunePeriod                              1
#define ES_ejs_web_HttpServer_defaultConfig                            2
#define ES_ejs_web_HttpServer_initHttpServer                           3
#define ES_ejs_web_HttpServer_indicies                                 4
#define ES_ejs_web_HttpServer_create                                   5
#define ES_ejs_web_HttpServer_NUM_CLASS_PROP                           6

/*
   Prototype (instance) slots for "HttpServer" type 
 */
#define ES_ejs_web_HttpServer_idleWorkers                              0
#define ES_ejs_web_HttpServer_activeWorkers                            1
#define ES_ejs_web_HttpServer_workerImage                              2
#define ES_ejs_web_HttpServer_address                                  3
#define ES_ejs_web_HttpServer_async                                    4
#define ES_ejs_web_HttpServer_config                                   5
#define ES_ejs_web_HttpServer_documents                                6
#define ES_ejs_web_HttpServer_hostedDocuments                          7
#define ES_ejs_web_HttpServer_hostedHome                               8
#define ES_ejs_web_HttpServer_isSecure                                 9
#define ES_ejs_web_HttpServer_hosted                                   10
#define ES_ejs_web_HttpServer_limits                                   11
#define ES_ejs_web_HttpServer_name                                     12
#define ES_ejs_web_HttpServer_options                                  13
#define ES_ejs_web_HttpServer_port                                     14
#define ES_ejs_web_HttpServer_onrequest                                15
#define ES_ejs_web_HttpServer_defaultOnRequest                         16
#define ES_ejs_web_HttpServer_home                                     17
#define ES_ejs_web_HttpServer_software                                 18
#define ES_ejs_web_HttpServer_openSession                              19
#define ES_ejs_web_HttpServer_accept                                   20
#define ES_ejs_web_HttpServer_close                                    21
#define ES_ejs_web_HttpServer_getWorker                                22
#define ES_ejs_web_HttpServer_listen                                   23
#define ES_ejs_web_HttpServer_off                                      24
#define ES_ejs_web_HttpServer_on                                       25
#define ES_ejs_web_HttpServer_passRequest                              26
#define ES_ejs_web_HttpServer_process                                  27
#define ES_ejs_web_HttpServer_processBody                              28
#define ES_ejs_web_HttpServer_pruneWorkers                             29
#define ES_ejs_web_HttpServer_releaseWorker                            30
#define ES_ejs_web_HttpServer_run                                      31
#define ES_ejs_web_HttpServer_secure                                   32
#define ES_ejs_web_HttpServer_serve                                    33
#define ES_ejs_web_HttpServer_setPipeline                              34
#define ES_ejs_web_HttpServer_setLimits                                35
#define ES_ejs_web_HttpServer_setWorkerImage                           36
#define ES_ejs_web_HttpServer_trace                                    37
#define ES_ejs_web_HttpServer_verifyClients                            38
#define ES_ejs_web_HttpServer_NUM_INSTANCE_PROP                        39
#define ES_ejs_web_HttpServer_NUM_INHERITED_PROP                       0

/*
    Local slots for methods in type "HttpServer" 
 */
#define ES_ejs_web_HttpServer_create_address                           0
#define ES_ejs_web_HttpServer_create_options                           1


/*
    Class property slots for the "Mvc" type 
 */
#define ES_ejs_web_Mvc__initializer___Mvc_                             0
#define ES_ejs_web_Mvc_apps                                            1
#define ES_ejs_web_Mvc_defaultConfig                                   2
#define ES_ejs_web_Mvc_loaded                                          3
#define ES_ejs_web_Mvc_EJSRC                                           4
#define ES_ejs_web_Mvc_load                                            5
#define ES_ejs_web_Mvc_openDatabase                                    6
#define ES_ejs_web_Mvc_NUM_CLASS_PROP                                  7

/*
   Prototype (instance) slots for "Mvc" type 
 */
#define ES_ejs_web_Mvc_config                                          0
#define ES_ejs_web_Mvc_loadRequest                                     1
#define ES_ejs_web_Mvc_loadComponent                                   2
#define ES_ejs_web_Mvc_rebuildComponent                                3
#define ES_ejs_web_Mvc_NUM_INSTANCE_PROP                               4
#define ES_ejs_web_Mvc_NUM_INHERITED_PROP                              0

/*
    Local slots for methods in type "Mvc" 
 */
#define ES_ejs_web_Mvc_load_request                                    0
#define ES_ejs_web_Mvc_load_dir                                        1
#define ES_ejs_web_Mvc_load_config                                     2
#define ES_ejs_web_Mvc_openDatabase_home                               0


/*
    Class property slots for the "Request" type 
 */
#define ES_ejs_web_Request__initializer___Request_                     0
#define ES_ejs_web_Request_SecurityTokenName                           1
#define ES_ejs_web_Request_jsgi                                        2
#define ES_ejs_web_Request_NUM_CLASS_PROP                              3

/*
   Prototype (instance) slots for "Request" type 
 */
#define ES_ejs_web_Request_lastFlash                                   0
#define ES_ejs_web_Request_absHome                                     1
#define ES_ejs_web_Request_authGroup                                   2
#define ES_ejs_web_Request_authType                                    3
#define ES_ejs_web_Request_authUser                                    4
#define ES_ejs_web_Request_autoFinalizing                              5
#define ES_ejs_web_Request_config                                      6
#define ES_ejs_web_Request_controller                                  7
#define ES_ejs_web_Request_contentLength                               8
#define ES_ejs_web_Request_contentType                                 9
#define ES_ejs_web_Request_cookies                                     10
#define ES_ejs_web_Request_dir                                         11
#define ES_ejs_web_Request_encoding                                    12
#define ES_ejs_web_Request_errorMessage                                13
#define ES_ejs_web_Request_files                                       14
#define ES_ejs_web_Request_filename                                    15
#define ES_ejs_web_Request_flash                                       16
#define ES_ejs_web_Request_formData                                    17
#define ES_ejs_web_Request_headers                                     18
#define ES_ejs_web_Request_home                                        19
#define ES_ejs_web_Request_host                                        20
#define ES_ejs_web_Request_isSecure                                    21
#define ES_ejs_web_Request_limits                                      22
#define ES_ejs_web_Request_localAddress                                23
#define ES_ejs_web_Request_log                                         24
#define ES_ejs_web_Request_method                                      25
#define ES_ejs_web_Request_originalMethod                              26
#define ES_ejs_web_Request_originalUri                                 27
#define ES_ejs_web_Request_params                                      28
#define ES_ejs_web_Request_pathInfo                                    29
#define ES_ejs_web_Request_port                                        30
#define ES_ejs_web_Request_protocol                                    31
#define ES_ejs_web_Request_query                                       32
#define ES_ejs_web_Request_reference                                   33
#define ES_ejs_web_Request_referrer                                    34
#define ES_ejs_web_Request_remoteAddress                               35
#define ES_ejs_web_Request_responded                                   36
#define ES_ejs_web_Request_responseHeaders                             37
#define ES_ejs_web_Request_route                                       38
#define ES_ejs_web_Request_routed                                      39
#define ES_ejs_web_Request_scheme                                      40
#define ES_ejs_web_Request_scriptName                                  41
#define ES_ejs_web_Request_server                                      42
#define ES_ejs_web_Request_session                                     43
#define ES_ejs_web_Request_sessionID                                   44
#define ES_ejs_web_Request_status                                      45
#define ES_ejs_web_Request_uri                                         46
#define ES_ejs_web_Request_writeBuffer                                 47
#define ES_ejs_web_Request_async                                       48
#define ES_ejs_web_Request_autoFinalize                                49
#define ES_ejs_web_Request_close                                       50
#define ES_ejs_web_Request_checkSecurityToken                          51
#define ES_ejs_web_Request_clearFlash                                  52
#define ES_ejs_web_Request_createSession                               53
#define ES_ejs_web_Request_dontAutoFinalize                            54
#define ES_ejs_web_Request_destroySession                              55
#define ES_ejs_web_Request_error                                       56
#define ES_ejs_web_Request_extension                                   57
#define ES_ejs_web_Request_finalize                                    58
#define ES_ejs_web_Request_finalized                                   59
#define ES_ejs_web_Request_finalizeFlash                               60
#define ES_ejs_web_Request_flush                                       61
#define ES_ejs_web_Request_header                                      62
#define ES_ejs_web_Request_inform                                      63
#define ES_ejs_web_Request_link                                        64
#define ES_ejs_web_Request_matchContent                                65
#define ES_ejs_web_Request_notify                                      66
#define ES_ejs_web_Request_off                                         67
#define ES_ejs_web_Request_on                                          68
#define ES_ejs_web_Request_read                                        69
#define ES_ejs_web_Request_redirect                                    70
#define ES_ejs_web_Request_securityToken                               71
#define ES_ejs_web_Request_setCookie                                   72
#define ES_ejs_web_Request_setHeader                                   73
#define ES_ejs_web_Request_setHeaders                                  74
#define ES_ejs_web_Request_setLimits                                   75
#define ES_ejs_web_Request_setLocation                                 76
#define ES_ejs_web_Request_setStatus                                   77
#define ES_ejs_web_Request_setupFlash                                  78
#define ES_ejs_web_Request_show                                        79
#define ES_ejs_web_Request_showRequest                                 80
#define ES_ejs_web_Request_trace                                       81
#define ES_ejs_web_Request_warn                                        82
#define ES_ejs_web_Request_write                                       83
#define ES_ejs_web_Request_writeContent                                84
#define ES_ejs_web_Request_writeError                                  85
#define ES_ejs_web_Request_writeFile                                   86
#define ES_ejs_web_Request_writeResponse                               87
#define ES_ejs_web_Request_writeSafe                                   88
#define ES_ejs_web_Request_written                                     89
#define ES_ejs_web_Request_env                                         90
#define ES_ejs_web_Request_input                                       91
#define ES_ejs_web_Request_queryString                                 92
#define ES_ejs_web_Request_serverPort                                  93
#define ES_ejs_web_Request_NUM_INSTANCE_PROP                           94
#define ES_ejs_web_Request_NUM_INHERITED_PROP                          0


/*
    Class property slots for the "Router" type 
 */
#define ES_ejs_web_Router__initializer___Router_                       0
#define ES_ejs_web_Router_Top                                          1
#define ES_ejs_web_Router_MaxRoute                                     2
#define ES_ejs_web_Router_Restful                                      3
#define ES_ejs_web_Router_isDir                                        4
#define ES_ejs_web_Router_NUM_CLASS_PROP                               5

/*
   Prototype (instance) slots for "Router" type 
 */
#define ES_ejs_web_Router_defaultApp                                   0
#define ES_ejs_web_Router_routerOptions                                1
#define ES_ejs_web_Router_routes                                       2
#define ES_ejs_web_Router_addCatchall                                  3
#define ES_ejs_web_Router_addDefault                                   4
#define ES_ejs_web_Router_addHandlers                                  5
#define ES_ejs_web_Router_addHome                                      6
#define ES_ejs_web_Router_addResource                                  7
#define ES_ejs_web_Router_addResources                                 8
#define ES_ejs_web_Router_addRestful                                   9
#define ES_ejs_web_Router_insertRoute                                  10
#define ES_ejs_web_Router_add                                          11
#define ES_ejs_web_Router_lookup                                       12
#define ES_ejs_web_Router_remove                                       13
#define ES_ejs_web_Router_reset                                        14
#define ES_ejs_web_Router_reroute                                      15
#define ES_ejs_web_Router_secondStageRoute                             16
#define ES_ejs_web_Router_route                                        17
#define ES_ejs_web_Router_setDefaultApp                                18
#define ES_ejs_web_Router_show                                         19
#define ES_ejs_web_Router_showRoute                                    20
#define ES_ejs_web_Router_NUM_INSTANCE_PROP                            21
#define ES_ejs_web_Router_NUM_INHERITED_PROP                           0

/*
    Local slots for methods in type "Router" 
 */
#define ES_ejs_web_Router_isDir_request                                0


/*
    Class property slots for the "Route" type 
 */
#define ES_ejs_web_Route__initializer___Route_                         0
#define ES_ejs_web_Route_nameSeed                                      1
#define ES_ejs_web_Route_NUM_CLASS_PROP                                2

/*
   Prototype (instance) slots for "Route" type 
 */
#define ES_ejs_web_Route_limits                                        0
#define ES_ejs_web_Route_location                                      1
#define ES_ejs_web_Route_method                                        2
#define ES_ejs_web_Route_middleware                                    3
#define ES_ejs_web_Route_name                                          4
#define ES_ejs_web_Route_moduleName                                    5
#define ES_ejs_web_Route_originalTemplate                              6
#define ES_ejs_web_Route_outer                                         7
#define ES_ejs_web_Route_params                                        8
#define ES_ejs_web_Route_rewrite                                       9
#define ES_ejs_web_Route_redirect                                      10
#define ES_ejs_web_Route_response                                      11
#define ES_ejs_web_Route_router                                        12
#define ES_ejs_web_Route_routeSetName                                  13
#define ES_ejs_web_Route_target                                        14
#define ES_ejs_web_Route_template                                      15
#define ES_ejs_web_Route_workers                                       16
#define ES_ejs_web_Route_tokens                                        17
#define ES_ejs_web_Route_trace                                         18
#define ES_ejs_web_Route_match                                         19
#define ES_ejs_web_Route_pattern                                       20
#define ES_ejs_web_Route_splitter                                      21
#define ES_ejs_web_Route_getTemplate                                   22
#define ES_ejs_web_Route_inheritRoutes                                 23
#define ES_ejs_web_Route_compileTemplate                               24
#define ES_ejs_web_Route_matchAndSplit                                 25
#define ES_ejs_web_Route_matchRegExp                                   26
#define ES_ejs_web_Route_makeParams                                    27
#define ES_ejs_web_Route_parseOptions                                  28
#define ES_ejs_web_Route_setName                                       29
#define ES_ejs_web_Route_setRouteSetName                               30
#define ES_ejs_web_Route_setRouteProperties                            31
#define ES_ejs_web_Route_NUM_INSTANCE_PROP                             32
#define ES_ejs_web_Route_NUM_INHERITED_PROP                            0


/*
    Class property slots for the "Session" type 
 */
#define ES_ejs_web_Session_key                                         0
#define ES_ejs_web_Session_destorySession                              1
#define ES_ejs_web_Session_NUM_CLASS_PROP                              2

/*
   Prototype (instance) slots for "Session" type 
 */
#define ES_ejs_web_Session_NUM_INSTANCE_PROP                           0
#define ES_ejs_web_Session_NUM_INHERITED_PROP                          0

/*
    Local slots for methods in type "Session" 
 */
#define ES_ejs_web_Session_key_session                                 0
#define ES_ejs_web_Session_destorySession_session                      0


/*
    Class property slots for the "UploadFile" type 
 */
#define ES_ejs_web_UploadFile_NUM_CLASS_PROP                           0

/*
   Prototype (instance) slots for "UploadFile" type 
 */
#define ES_ejs_web_UploadFile_clientFilename                           0
#define ES_ejs_web_UploadFile_contentType                              1
#define ES_ejs_web_UploadFile_filename                                 2
#define ES_ejs_web_UploadFile_name                                     3
#define ES_ejs_web_UploadFile_size                                     4
#define ES_ejs_web_UploadFile_NUM_INSTANCE_PROP                        5
#define ES_ejs_web_UploadFile_NUM_INHERITED_PROP                       0


/*
    Class property slots for the "View" type 
 */
#define ES_ejs_web_View_dateFormatter                                  0
#define ES_ejs_web_View_plainFormatter                                 1
#define ES_ejs_web_View_NUM_CLASS_PROP                                 2

/*
   Prototype (instance) slots for "View" type 
 */
#define ES_ejs_web_View_connectors                                     0
#define ES_ejs_web_View_currentRecord                                  1
#define ES_ejs_web_View_formats                                        2
#define ES_ejs_web_View_config                                         3
#define ES_ejs_web_View_controller                                     4
#define ES_ejs_web_View_params                                         5
#define ES_ejs_web_View_request                                        6
#define ES_ejs_web_View_ejs_web_render                                 7
#define ES_ejs_web_View_ejs_web_alert                                  8
#define ES_ejs_web_View_ejs_web_anchor                                 9
#define ES_ejs_web_View_ejs_web_button                                 10
#define ES_ejs_web_View_ejs_web_buttonLink                             11
#define ES_ejs_web_View_ejs_web_chart                                  12
#define ES_ejs_web_View_ejs_web_checkbox                               13
#define ES_ejs_web_View_ejs_web_div                                    14
#define ES_ejs_web_View_ejs_web_endform                                15
#define ES_ejs_web_View_ejs_web_flash                                  16
#define ES_ejs_web_View_ejs_web_form                                   17
#define ES_ejs_web_View_ejs_web_icon                                   18
#define ES_ejs_web_View_ejs_web_image                                  19
#define ES_ejs_web_View_ejs_web_input                                  20
#define ES_ejs_web_View_ejs_web_label                                  21
#define ES_ejs_web_View_ejs_web_list                                   22
#define ES_ejs_web_View_ejs_web_mail                                   23
#define ES_ejs_web_View_ejs_web_progress                               24
#define ES_ejs_web_View_ejs_web_radio                                  25
#define ES_ejs_web_View_ejs_web_refresh                                26
#define ES_ejs_web_View_ejs_web_script                                 27
#define ES_ejs_web_View_ejs_web_securityToken                          28
#define ES_ejs_web_View_ejs_web_stylesheet                             29
#define ES_ejs_web_View_ejs_web_table                                  30
#define ES_ejs_web_View_ejs_web_tabs                                   31
#define ES_ejs_web_View_ejs_web_text                                   32
#define ES_ejs_web_View_ejs_web_tree                                   33
#define ES_ejs_web_View_ejs_web_view                                   34
#define ES_ejs_web_View_ejs_web_link                                   35
#define ES_ejs_web_View_ejs_web_redirect                               36
#define ES_ejs_web_View_ejs_web_session                                37
#define ES_ejs_web_View_ejs_web_setHeader                              38
#define ES_ejs_web_View_ejs_web_setHeaders                             39
#define ES_ejs_web_View_ejs_web_setStatus                              40
#define ES_ejs_web_View_ejs_web_show                                   41
#define ES_ejs_web_View_ejs_web_write                                  42
#define ES_ejs_web_View_ejs_web_writeSafe                              43
#define ES_ejs_web_View_ejs_web_formatValue                            44
#define ES_ejs_web_View_getConnector                                   45
#define ES_ejs_web_View_getFieldName                                   46
#define ES_ejs_web_View_getOptions                                     47
#define ES_ejs_web_View_ejs_web_getValue                               48
#define ES_ejs_web_View_pivot                                          49
#define ES_ejs_web_View_ejs_web_formatters                             50
#define ES_ejs_web_View_ejs_web_date                                   51
#define ES_ejs_web_View_ejs_web_currency                               52
#define ES_ejs_web_View_ejs_web_number                                 53
#define ES_ejs_web_View_NUM_INSTANCE_PROP                              54
#define ES_ejs_web_View_NUM_INHERITED_PROP                             0

/*
    Local slots for methods in type "View" 
 */
#define ES_ejs_web_View_dateFormatter_view                             0
#define ES_ejs_web_View_dateFormatter_value                            1
#define ES_ejs_web_View_dateFormatter_options                          2
#define ES_ejs_web_View_plainFormatter_view                            0
#define ES_ejs_web_View_plainFormatter_value                           1
#define ES_ejs_web_View_plainFormatter_options                         2

#define _ES_CHECKSUM_ejs_web   832910

#endif
