/*
   ejs.zlib.slots.h -- Native property slot definitions for the "ejs.zlib" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsZlibSlots
#define _h_SLOTS_EjsZlibSlots 1


/*
   Slots for the "ejs.zlib" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Zlib" type 
 */
#define ES_ejs_zlib_Zlib_compress                                      0
#define ES_ejs_zlib_Zlib_uncompress                                    1
#define ES_ejs_zlib_Zlib_compressBytes                                 2
#define ES_ejs_zlib_Zlib_uncompressBytes                               3
#define ES_ejs_zlib_Zlib_compressString                                4
#define ES_ejs_zlib_Zlib_uncompressString                              5
#define ES_ejs_zlib_Zlib_NUM_CLASS_PROP                                6

/*
   Prototype (instance) slots for "Zlib" type 
 */
#define ES_ejs_zlib_Zlib_NUM_INSTANCE_PROP                             0
#define ES_ejs_zlib_Zlib_NUM_INHERITED_PROP                            0

/*
    Local slots for methods in type "Zlib" 
 */
#define ES_ejs_zlib_Zlib_compress_src                                  0
#define ES_ejs_zlib_Zlib_compress_dest                                 1
#define ES_ejs_zlib_Zlib_uncompress_src                                0
#define ES_ejs_zlib_Zlib_uncompress_dest                               1
#define ES_ejs_zlib_Zlib_compressBytes_data                            0
#define ES_ejs_zlib_Zlib_uncompressBytes_data                          0
#define ES_ejs_zlib_Zlib_compressString_data                           0
#define ES_ejs_zlib_Zlib_uncompressString_data                         0

#define _ES_CHECKSUM_ejs_zlib   14504

#endif
