/*
   ejs.db.sqlite.slots.h -- Native property slot definitions for the "ejs.db.sqlite" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.3.6.
 */

#ifndef _h_SLOTS_EjsDbSqliteSlots
#define _h_SLOTS_EjsDbSqliteSlots 1


/*
   Slots for the "ejs.db.sqlite" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Sqlite" type 
 */
#define ES_ejs_db_sqlite_Sqlite__initializer___Sqlite_                 0
#define ES_ejs_db_sqlite_Sqlite_DataTypeToSqlType                      1
#define ES_ejs_db_sqlite_Sqlite_SqlTypeToDataType                      2
#define ES_ejs_db_sqlite_Sqlite_SqlTypeToEjsType                       3
#define ES_ejs_db_sqlite_Sqlite_NUM_CLASS_PROP                         4

/*
   Prototype (instance) slots for "Sqlite" type 
 */
#define ES_ejs_db_sqlite_Sqlite_addColumn                              0
#define ES_ejs_db_sqlite_Sqlite_addIndex                               1
#define ES_ejs_db_sqlite_Sqlite_changeColumn                           2
#define ES_ejs_db_sqlite_Sqlite_close                                  3
#define ES_ejs_db_sqlite_Sqlite_commit                                 4
#define ES_ejs_db_sqlite_Sqlite_connect                                5
#define ES_ejs_db_sqlite_Sqlite_createDatabase                         6
#define ES_ejs_db_sqlite_Sqlite_createTable                            7
#define ES_ejs_db_sqlite_Sqlite_dataTypeToSqlType                      8
#define ES_ejs_db_sqlite_Sqlite_destroyDatabase                        9
#define ES_ejs_db_sqlite_Sqlite_destroyTable                           10
#define ES_ejs_db_sqlite_Sqlite_endTransaction                         11
#define ES_ejs_db_sqlite_Sqlite_getColumns                             12
#define ES_ejs_db_sqlite_Sqlite_getNumRows                             13
#define ES_ejs_db_sqlite_Sqlite_getTables                              14
#define ES_ejs_db_sqlite_Sqlite_removeColumns                          15
#define ES_ejs_db_sqlite_Sqlite_removeIndex                            16
#define ES_ejs_db_sqlite_Sqlite_renameColumn                           17
#define ES_ejs_db_sqlite_Sqlite_renameTable                            18
#define ES_ejs_db_sqlite_Sqlite_rollback                               19
#define ES_ejs_db_sqlite_Sqlite_query                                  20
#define ES_ejs_db_sqlite_Sqlite_sql                                    21
#define ES_ejs_db_sqlite_Sqlite_sqlTypeToDataType                      22
#define ES_ejs_db_sqlite_Sqlite_sqlTypeToEjsType                       23
#define ES_ejs_db_sqlite_Sqlite_startTransaction                       24
#define ES_ejs_db_sqlite_Sqlite_NUM_INSTANCE_PROP                      25
#define ES_ejs_db_sqlite_Sqlite_NUM_INHERITED_PROP                     0

#define _ES_CHECKSUM_ejs_db_sqlite   73576

#endif
