#
#	Makefile for master includes
#
#	Copyright (c) Embedthis Software LLC, 2003-2012. All Rights Reserved.
#

include 		.makedep

import:
	for f in *slots* ; do \
		echo cp $(BLD_INC_DIR)/$$f . ; \
		cp $(BLD_INC_DIR)/$$f . ; \
	done


#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
