#!/bin/bash
#
#   Create or modify symlinks for the most recent installed versions of Ejscript
#
#   Copyright (c) Embedthis Software LLC, 2003-2012. All Rights Reserved.
#

TASK=$1
PRODUCT=ejs
ROOT_DIR="${2%/}"
INC_DIR="${ROOT_DIR}/usr/include"
MAN_DIR="${ROOT_DIR}/usr/share/man"
PROGRAMS="bit ejs ejsc ejsman ejsmod sqlite mvc jem"
LIBRARIES="libmpr libejs"

if [ -x "${ROOT_DIR}/usr/local/bin" ] ; then
    BIN="${ROOT_DIR}/usr/local/bin"
else 
    BIN="${ROOT_DIR}/usr/bin"
fi
LIB="${ROOT_DIR}/usr/lib"

prefix="${ROOT_DIR}/usr/lib/${PRODUCT}"
version=

for v in `ls $prefix 2>/dev/null | egrep -v '[a-zA-Z@!_\-]' | sort -n -r`
do
    if [ -x "$prefix/$v/bin/ejs" ] ; then
        version=$v
        break
    fi
done

if [ "$version" = "" ] ; then
    for name in $PROGRAMS
    do
        rm -f "${BIN}/$name"
    done
    rm -fr "${INC_DIR}/${PRODUCT}"
else

    latest=${prefix}/$version
    rm -f ${prefix}/latest
    ln -s ${version} ${prefix}/latest
    bin=${latest}/bin
    inc=${latest}/inc
    man=${latest}/doc/man/man1
    lib=${latest}/lib

    [ ! -x "${BIN}" ] && mkdir -p "${BIN}"

    home=`pwd`
    for name in $PROGRAMS ; do
        name=${name}
        rm -f "${BIN}/${name}"
        if [ -f "${bin}/${name}" ] ; then
            ln -s "${bin}/${name}" "${BIN}/${name}"
        fi
    done
    for name in $LIBRARIES ; do
        name=${name}
        rm -f "${LIB}/${name}*"
        if [ -f "${lib}/${name}*" ] ; then
            ln -s "${lib}/${name}*" "${LIB}/${name}"
        fi
    done
    if [ -d "${inc}" ] ; then
        [ ! -x "${INC_DIR}" ] && mkdir -p "${INC_DIR}"
        rm -rf  "${INC_DIR}/${PRODUCT}"
        ln -s "${inc}" "${INC_DIR}/${PRODUCT}"
    fi
    if [ -d "${man}" ] ; then
        [ ! -x "${MAN_DIR}" ] && mkdir -p "${MAN_DIR}/man1"
        for f in ${man}/*.1.gz
        do
            name=`basename "$f"`
            rm -f "${MAN_DIR}/man1/${name}"
            ln -s "${f}" "${MAN_DIR}/man1/${name}"
        done
    fi
fi
