/*
   ejs.cache.slots.h -- Native property slot definitions for the "ejs.cache" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsCacheSlots
#define _h_SLOTS_EjsCacheSlots 1


/*
   Slots for the "ejs.cache" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Cache" type 
 */
#define ES_ejs_cache_Cache__initializer___Cache_                       0
#define ES_ejs_cache_Cache_cache                                       1

#define ES_ejs_cache_Cache_NUM_CLASS_PROP                              2

/*
   Prototype (instance) slots for "Cache" type 
 */
#define ES_ejs_cache_Cache_Cache                                       12
#define ES_ejs_cache_Cache_read                                        13
#define ES_ejs_cache_Cache_write                                       14
#define ES_ejs_cache_Cache_remove                                      15
#define ES_ejs_cache_Cache_NUM_INSTANCE_PROP                           16

#define _ES_CHECKSUM_ejs_cache   11463

#endif
