/*
   ejs.cjs.slots.h -- Native property slot definitions for the "ejs.cjs" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsCjsSlots
#define _h_SLOTS_EjsCjsSlots 1


/*
   Slots for the "ejs.cjs" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "System" type 
 */
#define ES_ejs_cjs_System_stdin                                        0
#define ES_ejs_cjs_System_stdout                                       1
#define ES_ejs_cjs_System_stderr                                       2
#define ES_ejs_cjs_System_args                                         3
#define ES_ejs_cjs_System_env                                          4
#define ES_ejs_cjs_System_fs                                           5
#define ES_ejs_cjs_System_platform                                     6
#define ES_ejs_cjs_System_NUM_CLASS_PROP                               7

/*
   Prototype (instance) slots for "System" type 
 */
#define ES_ejs_cjs_System_log                                          0
#define ES_ejs_cjs_System_NUM_INSTANCE_PROP                            1
#define ES_ejs_cjs_System_NUM_INHERITED_PROP                           0

#define _ES_CHECKSUM_ejs_cjs   9044

#endif
