/*
   ejs.db.sqlite.slots.h -- Native property slot definitions for the "ejs.db.sqlite" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsDbSqliteSlots
#define _h_SLOTS_EjsDbSqliteSlots 1


/*
   Slots for the "ejs.db.sqlite" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Sqlite" type 
 */
#define ES_ejs_db_Sqlite__initializer___Sqlite_                        0
#define ES_ejs_db_Sqlite_DataTypeToSqlType                             1
#define ES_ejs_db_Sqlite_SqlTypeToDataType                             2
#define ES_ejs_db_Sqlite_SqlTypeToEjsType                              3

#define ES_ejs_db_Sqlite_NUM_CLASS_PROP                                4

/*
   Prototype (instance) slots for "Sqlite" type 
 */
#define ES_ejs_db_Sqlite_constructor                                   0
#define ES_ejs_db_Sqlite_clone                                         1
#define ES_ejs_db_Sqlite_get                                           2
#define ES_ejs_db_Sqlite_getValues                                     3
#define ES_ejs_db_Sqlite_hasOwnProperty                                4
#define ES_ejs_db_Sqlite_isPrototypeOf                                 5
#define ES_ejs_db_Sqlite_propertyIsEnumerable                          6
#define ES_ejs_db_Sqlite_toJSON                                        7
#define ES_ejs_db_Sqlite_toLocaleString                                8
#define ES_ejs_db_Sqlite_toString                                      9
#define ES_ejs_db_Sqlite_valueOf                                       10
#define ES_ejs_db_Sqlite_Sqlite                                        11
#define ES_ejs_db_Sqlite_addColumn                                     12
#define ES_ejs_db_Sqlite_addIndex                                      13
#define ES_ejs_db_Sqlite_changeColumn                                  14
#define ES_ejs_db_Sqlite_close                                         15
#define ES_ejs_db_Sqlite_commit                                        16
#define ES_ejs_db_Sqlite_connect                                       17
#define ES_ejs_db_Sqlite_createDatabase                                18
#define ES_ejs_db_Sqlite_createTable                                   19
#define ES_ejs_db_Sqlite_dataTypeToSqlType                             20
#define ES_ejs_db_Sqlite_destroyDatabase                               21
#define ES_ejs_db_Sqlite_destroyTable                                  22
#define ES_ejs_db_Sqlite_endTransaction                                23
#define ES_ejs_db_Sqlite_getColumns                                    24
#define ES_ejs_db_Sqlite_getNumRows                                    25
#define ES_ejs_db_Sqlite_getTables                                     26
#define ES_ejs_db_Sqlite_removeColumns                                 27
#define ES_ejs_db_Sqlite_removeIndex                                   28
#define ES_ejs_db_Sqlite_renameColumn                                  29
#define ES_ejs_db_Sqlite_renameTable                                   30
#define ES_ejs_db_Sqlite_rollback                                      31
#define ES_ejs_db_Sqlite_query                                         32
#define ES_ejs_db_Sqlite_sql                                           33
#define ES_ejs_db_Sqlite_sqlTypeToDataType                             34
#define ES_ejs_db_Sqlite_sqlTypeToEjsType                              35
#define ES_ejs_db_Sqlite_startTransaction                              36
#define ES_ejs_db_Sqlite_NUM_INSTANCE_PROP                             37

#define _ES_CHECKSUM_ejs_db_sqlite   73341

#endif
