/*
   ejs.db.sqlite.slots.h -- Native property slot definitions for the "ejs.db.sqlite" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsDbSqliteSlots
#define _h_SLOTS_EjsDbSqliteSlots 1


/*
   Slots for the "ejs.db.sqlite" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Sqlite" type 
 */
#define ES_ejs_db_Sqlite__initializer___Sqlite_                        0
#define ES_ejs_db_Sqlite_DataTypeToSqlType                             1
#define ES_ejs_db_Sqlite_SqlTypeToDataType                             2
#define ES_ejs_db_Sqlite_SqlTypeToEjsType                              3

#define ES_ejs_db_Sqlite_NUM_CLASS_PROP                                4

/*
   Prototype (instance) slots for "Sqlite" type 
 */
#define ES_ejs_db_Sqlite_Sqlite                                        12
#define ES_ejs_db_Sqlite_addColumn                                     13
#define ES_ejs_db_Sqlite_addIndex                                      14
#define ES_ejs_db_Sqlite_changeColumn                                  15
#define ES_ejs_db_Sqlite_close                                         16
#define ES_ejs_db_Sqlite_commit                                        17
#define ES_ejs_db_Sqlite_connect                                       18
#define ES_ejs_db_Sqlite_createDatabase                                19
#define ES_ejs_db_Sqlite_createTable                                   20
#define ES_ejs_db_Sqlite_dataTypeToSqlType                             21
#define ES_ejs_db_Sqlite_destroyDatabase                               22
#define ES_ejs_db_Sqlite_destroyTable                                  23
#define ES_ejs_db_Sqlite_endTransaction                                24
#define ES_ejs_db_Sqlite_getColumns                                    25
#define ES_ejs_db_Sqlite_getNumRows                                    26
#define ES_ejs_db_Sqlite_getTables                                     27
#define ES_ejs_db_Sqlite_removeColumns                                 28
#define ES_ejs_db_Sqlite_removeIndex                                   29
#define ES_ejs_db_Sqlite_renameColumn                                  30
#define ES_ejs_db_Sqlite_renameTable                                   31
#define ES_ejs_db_Sqlite_rollback                                      32
#define ES_ejs_db_Sqlite_query                                         33
#define ES_ejs_db_Sqlite_sql                                           34
#define ES_ejs_db_Sqlite_sqlTypeToDataType                             35
#define ES_ejs_db_Sqlite_sqlTypeToEjsType                              36
#define ES_ejs_db_Sqlite_startTransaction                              37
#define ES_ejs_db_Sqlite_NUM_INSTANCE_PROP                             38

#define _ES_CHECKSUM_ejs_db_sqlite   73369

#endif
