/*
   ejs.xml.slots.h -- Native property slot definitions for the "ejs.xml" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsXmlSlots
#define _h_SLOTS_EjsXmlSlots 1


/*
   Slots for the "ejs.xml" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_readFile_path                                               0
#define ES_readFile_encoding                                           1
#define ES_makeGetter_fn                                               0
#define ES_clearBoundThis_fn                                           0
#define ES_assert_condition                                            0
#define ES_cloneBase_klass                                             0
#define ES_dump_args                                                   0
#define ES_dumpAll_args                                                0
#define ES_dumpDef_args                                                0
#define ES_md5_str                                                     0
#define ES_blend_dest                                                  0
#define ES_blend_src                                                   1
#define ES_blend_overwrite                                             2
#define ES_eval_script                                                 0
#define ES_eval_cache                                                  1
#define ES_hashcode_o                                                  0
#define ES_isNaN_arg                                                   0
#define ES_isFinite_arg                                                0
#define ES_load_file                                                   0
#define ES_load_cache                                                  1
#define ES_print_args                                                  0
#define ES_parse_str                                                   0
#define ES_parse_preferredType                                         1
#define ES_parseFloat_str                                              0
#define ES_parseInt_str                                                0
#define ES_parseInt_radix                                              1
#define ES_printHash_name                                              0
#define ES_printHash_o                                                 1
#define ES_instanceOf_obj                                              0
#define ES_instanceOf_target                                           1
#define ES_deserialize_str                                             0
#define ES_serialize_obj                                               0
#define ES_serialize_options                                           1
#define ES_typeOf_o                                                    0
#define ES_setInterval_callback                                        0
#define ES_setInterval_delay                                           1
#define ES_setInterval_args                                            2
#define ES_clearInterval_timer                                         0
#define ES_setTimeout_callback                                         0
#define ES_setTimeout_delay                                            1
#define ES_setTimeout_args                                             2
#define ES_clearTimeout_timer                                          0
#define ES_decodeURI_str                                               0
#define ES_decodeURIComponent_str                                      0
#define ES_encodeURI_str                                               0
#define ES_encodeURIComponent_str                                      0
#define ES_ejs_worker_postMessage_data                                 0
#define ES_ejs_worker_postMessage_ports                                1

#define _ES_CHECKSUM_ejs_xml   705

#endif
