/*
   ejs.tar.slots.h -- Native property slot definitions for the "ejs.tar" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsTarSlots
#define _h_SLOTS_EjsTarSlots 1


/*
   Slots for the "ejs.tar" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */
#define ES_ejs_tar_Tar_NUM_CLASS_PROP                                  0

/*
   Prototype (instance) slots for "Tar" type 
 */
#define ES_ejs_tar_Tar_path                                            0
#define ES_ejs_tar_Tar_files                                           1
#define ES_ejs_tar_Tar_add                                             2
#define ES_ejs_tar_Tar_create                                          3
#define ES_ejs_tar_Tar_extract                                         4
#define ES_ejs_tar_Tar_cat                                             5
#define ES_ejs_tar_Tar_NUM_INSTANCE_PROP                               6
#define ES_ejs_tar_Tar_NUM_INHERITED_PROP                              0

#define _ES_CHECKSUM_ejs_tar   8993

#endif
