/*
   ejs.web.slots.h -- Native property slot definitions for the "ejs.web" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsWebSlots
#define _h_SLOTS_EjsWebSlots 1


/*
   Slots for the "ejs.web" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_ejs_web_Cascade_apps                                        0
#define ES_ejs_web_CommonLog_app                                       0
#define ES_ejs_web_CommonLog_logger                                    1
#define ES_ejs_web_ContentType_app                                     0
#define ES_ejs_web_ContentType_options                                 1
#define ES_ejs_web_DirApp_request                                      0
#define ES_ejs_web_DirBuilder_request                                  0
#define ES_ejs_web_Head_app                                            0
#define ES_ejs_web_MethodOverride_app                                  0
#define ES_ejs_web_Middleware_app                                      0
#define ES_ejs_web_Middleware_middleware                               1
#define ES_ejs_web_MvcApp_request                                      0
#define ES_ejs_web_MvcBuilder_request                                  0
#define ES_ejs_web_ScriptBuilder_request                               0
#define ES_ejs_web_ShowExceptions_app                                  0
#define ES_ejs_web_StaticApp_request                                   0
#define ES_ejs_web_StaticBuilder_request                               0
#define ES_ejs_web_TemplateFilter_app                                  0
#define ES_ejs_web_TemplateApp_request                                 0
#define ES_ejs_web_TemplateBuilder_request                             0
#define ES_ejs_web_TemplateBuilder_options                             1
#define ES_ejs_web_UrlMap_map                                          0
#define ES_ejs_web_UrlMap_options                                      1
#define ES_ejs_web_errorBody_title                                     0
#define ES_ejs_web_errorBody_msg                                       1
#define ES_ejs_web_parseCookies_cookieHeader                           0
#define ES_ejs_web_escapeHtml_str                                      0
#define ES_ejs_web_html_args                                           0
#define ES_ejs_web_unescapeHtml_s                                      0
#define ES_ejs_web_CommonLogBuilder_NUM_CLASS_PROP                     0

/*
   Prototype (instance) slots for "CommonLogBuilder" type 
 */
#define ES_ejs_web_CommonLogBuilder_app                                0
#define ES_ejs_web_CommonLogBuilder_logger                             1
#define ES_ejs_web_CommonLogBuilder_run                                2
#define ES_ejs_web_CommonLogBuilder_NUM_INSTANCE_PROP                  3
#define ES_ejs_web_CommonLogBuilder_NUM_INHERITED_PROP                 0


/*
    Class property slots for the "Controller" type 
 */
#define ES_ejs_web_Controller__initRequest                             0
#define ES_ejs_web_Controller_ejs_web_create                           1
#define ES_ejs_web_Controller_NUM_CLASS_PROP                           2

/*
   Prototype (instance) slots for "Controller" type 
 */
#define ES_ejs_web_Controller__afterCheckers                           0
#define ES_ejs_web_Controller__beforeCheckers                          1
#define ES_ejs_web_Controller_ejs_web_actionName                       2
#define ES_ejs_web_Controller_ejs_web_config                           3
#define ES_ejs_web_Controller_ejs_web_controllerName                   4
#define ES_ejs_web_Controller_ejs_web_log                              5
#define ES_ejs_web_Controller_ejs_web_params                           6
#define ES_ejs_web_Controller_ejs_web_request                          7
#define ES_ejs_web_Controller_ejs_web_absHome                          8
#define ES_ejs_web_Controller_ejs_web_home                             9
#define ES_ejs_web_Controller_ejs_web_pathInfo                         10
#define ES_ejs_web_Controller_ejs_web_session                          11
#define ES_ejs_web_Controller_ejs_web_uri                              12
#define ES_ejs_web_Controller_ejs_web_afterChecker                     13
#define ES_ejs_web_Controller_ejs_web_app                              14
#define ES_ejs_web_Controller_ejs_web_beforeChecker                    15
#define ES_ejs_web_Controller_ejs_web_error                            16
#define ES_ejs_web_Controller_ejs_web_flash                            17
#define ES_ejs_web_Controller_ejs_web_header                           18
#define ES_ejs_web_Controller_ejs_web_inform                           19
#define ES_ejs_web_Controller_ejs_web_makeUri                          20
#define ES_ejs_web_Controller_action_missing                           21
#define ES_ejs_web_Controller_ejs_web_observe                          22
#define ES_ejs_web_Controller_ejs_web_read                             23
#define ES_ejs_web_Controller_ejs_web_redirect                         24
#define ES_ejs_web_Controller_ejs_web_redirectAction                   25
#define ES_ejs_web_Controller_ejs_web_write                            26
#define ES_ejs_web_Controller_ejs_web_writeError                       27
#define ES_ejs_web_Controller_ejs_web_writeFile                        28
#define ES_ejs_web_Controller_ejs_web_writePartialTemplate             29
#define ES_ejs_web_Controller_ejs_web_writeView                        30
#define ES_ejs_web_Controller_ejs_web_writeTemplate                    31
#define ES_ejs_web_Controller_ejs_web_removeCheckers                   32
#define ES_ejs_web_Controller_ejs_web_setHeader                        33
#define ES_ejs_web_Controller_ejs_web_setStatus                        34
#define ES_ejs_web_Controller_ejs_web_warn                             35
#define ES_ejs_web_Controller_ejs_web_autoFinalize                     36
#define ES_ejs_web_Controller_ejs_web_autoFinalizing                   37
#define ES_ejs_web_Controller_ejs_web_flush                            38
#define ES_ejs_web_Controller_ejs_web_finalize                         39
#define ES_ejs_web_Controller_ejs_web_finalized                        40
#define ES_ejs_web_Controller_ejs_web_dontAutoFinalize                 41
#define ES_ejs_web_Controller_openDatabase                             42
#define ES_ejs_web_Controller_runCheckers                              43
#define ES_ejs_web_Controller_viewExists                               44
#define ES_ejs_web_Controller_NUM_INSTANCE_PROP                        45
#define ES_ejs_web_Controller_NUM_INHERITED_PROP                       0

/*
    Local slots for methods in type "Controller" 
 */
#define ES_ejs_web_Controller_ejs_web_create_request                   0
#define ES_ejs_web_Controller_ejs_web_create_cname                     1
#define ES_HtmlConnector_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "HtmlConnector" type 
 */
#define ES_HtmlConnector_request                                       0
#define ES_HtmlConnector_view                                          1
#define ES_HtmlConnector_ejs_web_aform                                 2
#define ES_HtmlConnector_ejs_web_alink                                 3
#define ES_HtmlConnector_ejs_web_button                                4
#define ES_HtmlConnector_ejs_web_buttonLink                            5
#define ES_HtmlConnector_ejs_web_chart                                 6
#define ES_HtmlConnector_ejs_web_checkbox                              7
#define ES_HtmlConnector_ejs_web_endform                               8
#define ES_HtmlConnector_ejs_web_flash                                 9
#define ES_HtmlConnector_ejs_web_form                                  10
#define ES_HtmlConnector_ejs_web_image                                 11
#define ES_HtmlConnector_ejs_web_imageLink                             12
#define ES_HtmlConnector_ejs_web_label                                 13
#define ES_HtmlConnector_ejs_web_link                                  14
#define ES_HtmlConnector_ejs_web_extlink                               15
#define ES_HtmlConnector_ejs_web_list                                  16
#define ES_HtmlConnector_ejs_web_mail                                  17
#define ES_HtmlConnector_ejs_web_progress                              18
#define ES_HtmlConnector_ejs_web_radio                                 19
#define ES_HtmlConnector_ejs_web_script                                20
#define ES_HtmlConnector_ejs_web_status                                21
#define ES_HtmlConnector_ejs_web_stylesheet                            22
#define ES_HtmlConnector_ejs_web_table                                 23
#define ES_HtmlConnector_ejs_web_tabs                                  24
#define ES_HtmlConnector_ejs_web_text                                  25
#define ES_HtmlConnector_ejs_web_textarea                              26
#define ES_HtmlConnector_ejs_web_tree                                  27
#define ES_HtmlConnector_getColumns                                    28
#define ES_HtmlConnector_getTextKind                                   29
#define ES_HtmlConnector_getOptions                                    30
#define ES_HtmlConnector_write                                         31
#define ES_HtmlConnector_getDataAttributes                             32
#define ES_HtmlConnector_NUM_INSTANCE_PROP                             33
#define ES_HtmlConnector_NUM_INHERITED_PROP                            0


/*
    Class property slots for the "HttpServer" type 
 */
#define ES_ejs_web_HttpServer__initializer___HttpServer_               0
#define ES_ejs_web_HttpServer_indicies                                 1
#define ES_ejs_web_HttpServer_NUM_CLASS_PROP                           2

/*
   Prototype (instance) slots for "HttpServer" type 
 */
#define ES_ejs_web_HttpServer_address                                  0
#define ES_ejs_web_HttpServer_async                                    1
#define ES_ejs_web_HttpServer_documentRoot                             2
#define ES_ejs_web_HttpServer_isSecure                                 3
#define ES_ejs_web_HttpServer_limits                                   4
#define ES_ejs_web_HttpServer_name                                     5
#define ES_ejs_web_HttpServer_port                                     6
#define ES_ejs_web_HttpServer_serverRoot                               7
#define ES_ejs_web_HttpServer_sessions                                 8
#define ES_ejs_web_HttpServer_software                                 9
#define ES_ejs_web_HttpServer_accept                                   10
#define ES_ejs_web_HttpServer_close                                    11
#define ES_ejs_web_HttpServer_listen                                   12
#define ES_ejs_web_HttpServer_observe                                  13
#define ES_ejs_web_HttpServer_removeObserver                           14
#define ES_ejs_web_HttpServer_secure                                   15
#define ES_ejs_web_HttpServer_setPipeline                              16
#define ES_ejs_web_HttpServer_setLimits                                17
#define ES_ejs_web_HttpServer_trace                                    18
#define ES_ejs_web_HttpServer_verifyClients                            19
#define ES_ejs_web_HttpServer_NUM_INSTANCE_PROP                        20
#define ES_ejs_web_HttpServer_NUM_INHERITED_PROP                       0


/*
    Class property slots for the "Mvc" type 
 */
#define ES_Mvc__initializer___Mvc_                                     0
#define ES_Mvc_apps                                                    1
#define ES_Mvc_defaultConfig                                           2
#define ES_Mvc_loaded                                                  3
#define ES_Mvc_EJSRC                                                   4
#define ES_Mvc_NUM_CLASS_PROP                                          5

/*
   Prototype (instance) slots for "Mvc" type 
 */
#define ES_Mvc_loadConfig                                              0
#define ES_Mvc_init                                                    1
#define ES_Mvc_loadComponent                                           2
#define ES_Mvc_NUM_INSTANCE_PROP                                       3
#define ES_Mvc_NUM_INHERITED_PROP                                      0


/*
    Class property slots for the "Request" type 
 */
#define ES_ejs_web_Request__initializer___Request_                     0
#define ES_ejs_web_Request_jsgi                                        1
#define ES_ejs_web_Request_NUM_CLASS_PROP                              2

/*
   Prototype (instance) slots for "Request" type 
 */
#define ES_ejs_web_Request_lastFlash                                   0
#define ES_ejs_web_Request_absHome                                     1
#define ES_ejs_web_Request_authGroup                                   2
#define ES_ejs_web_Request_authType                                    3
#define ES_ejs_web_Request_authUser                                    4
#define ES_ejs_web_Request_autoFinalizing                              5
#define ES_ejs_web_Request_config                                      6
#define ES_ejs_web_Request_controller                                  7
#define ES_ejs_web_Request_contentLength                               8
#define ES_ejs_web_Request_contentType                                 9
#define ES_ejs_web_Request_cookies                                     10
#define ES_ejs_web_Request_dir                                         11
#define ES_ejs_web_Request_encoding                                    12
#define ES_ejs_web_Request_errorMessage                                13
#define ES_ejs_web_Request_files                                       14
#define ES_ejs_web_Request_filename                                    15
#define ES_ejs_web_Request_flashMessages                               16
#define ES_ejs_web_Request_headers                                     17
#define ES_ejs_web_Request_home                                        18
#define ES_ejs_web_Request_host                                        19
#define ES_ejs_web_Request_isSecure                                    20
#define ES_ejs_web_Request_limits                                      21
#define ES_ejs_web_Request_localAddress                                22
#define ES_ejs_web_Request_log                                         23
#define ES_ejs_web_Request_method                                      24
#define ES_ejs_web_Request_originalMethod                              25
#define ES_ejs_web_Request_originalUri                                 26
#define ES_ejs_web_Request_params                                      27
#define ES_ejs_web_Request_pathInfo                                    28
#define ES_ejs_web_Request_port                                        29
#define ES_ejs_web_Request_protocol                                    30
#define ES_ejs_web_Request_query                                       31
#define ES_ejs_web_Request_reference                                   32
#define ES_ejs_web_Request_referrer                                    33
#define ES_ejs_web_Request_remoteAddress                               34
#define ES_ejs_web_Request_responded                                   35
#define ES_ejs_web_Request_responseHeaders                             36
#define ES_ejs_web_Request_route                                       37
#define ES_ejs_web_Request_scheme                                      38
#define ES_ejs_web_Request_scriptName                                  39
#define ES_ejs_web_Request_server                                      40
#define ES_ejs_web_Request_session                                     41
#define ES_ejs_web_Request_sessionID                                   42
#define ES_ejs_web_Request_status                                      43
#define ES_ejs_web_Request_uri                                         44
#define ES_ejs_web_Request_async                                       45
#define ES_ejs_web_Request_autoFinalize                                46
#define ES_ejs_web_Request_close                                       47
#define ES_ejs_web_Request_createSession                               48
#define ES_ejs_web_Request_dontAutoFinalize                            49
#define ES_ejs_web_Request_destroySession                              50
#define ES_ejs_web_Request_error                                       51
#define ES_ejs_web_Request_extension                                   52
#define ES_ejs_web_Request_finalize                                    53
#define ES_ejs_web_Request_finalized                                   54
#define ES_ejs_web_Request_finalizeFlash                               55
#define ES_ejs_web_Request_flash                                       56
#define ES_ejs_web_Request_flush                                       57
#define ES_ejs_web_Request_header                                      58
#define ES_ejs_web_Request_inform                                      59
#define ES_ejs_web_Request_makeUri                                     60
#define ES_ejs_web_Request_observe                                     61
#define ES_ejs_web_Request_read                                        62
#define ES_ejs_web_Request_redirect                                    63
#define ES_ejs_web_Request_removeObserver                              64
#define ES_ejs_web_Request_sendFile                                    65
#define ES_ejs_web_Request_sendResponse                                66
#define ES_ejs_web_Request_setCookie                                   67
#define ES_ejs_web_Request_setHeader                                   68
#define ES_ejs_web_Request_setHeaders                                  69
#define ES_ejs_web_Request_setLimits                                   70
#define ES_ejs_web_Request_setLocation                                 71
#define ES_ejs_web_Request_setStatus                                   72
#define ES_ejs_web_Request_setupFlash                                  73
#define ES_ejs_web_Request_show                                        74
#define ES_ejs_web_Request_trace                                       75
#define ES_ejs_web_Request_warn                                        76
#define ES_ejs_web_Request_write                                       77
#define ES_ejs_web_Request_writeError                                  78
#define ES_ejs_web_Request_writeHtml                                   79
#define ES_ejs_web_Request_written                                     80
#define ES_ejs_web_Request_env                                         81
#define ES_ejs_web_Request_input                                       82
#define ES_ejs_web_Request_queryString                                 83
#define ES_ejs_web_Request_serverPort                                  84
#define ES_ejs_web_Request_NUM_INSTANCE_PROP                           85
#define ES_ejs_web_Request_NUM_INHERITED_PROP                          0


/*
    Class property slots for the "Router" type 
 */
#define ES_ejs_web_Router__initializer___Router_                       0
#define ES_ejs_web_Router_isDir                                        1
#define ES_ejs_web_Router_TopRoutes                                    2
#define ES_ejs_web_Router_RestfulRoutes                                3
#define ES_ejs_web_Router_NUM_CLASS_PROP                               4

/*
   Prototype (instance) slots for "Router" type 
 */
#define ES_ejs_web_Router_routes                                       0
#define ES_ejs_web_Router_routeLookup                                  1
#define ES_ejs_web_Router_addRestfulRoutes                             2
#define ES_ejs_web_Router_addRoutes                                    3
#define ES_ejs_web_Router_route                                        4
#define ES_ejs_web_Router_NUM_INSTANCE_PROP                            5
#define ES_ejs_web_Router_NUM_INHERITED_PROP                           0

/*
    Local slots for methods in type "Router" 
 */
#define ES_ejs_web_Router_isDir_request                                0
#define ES_ejs_web_Route_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "Route" type 
 */
#define ES_ejs_web_Route_builder                                       0
#define ES_ejs_web_Route_dir                                           1
#define ES_ejs_web_Route_limits                                        2
#define ES_ejs_web_Route_match                                         3
#define ES_ejs_web_Route_method                                        4
#define ES_ejs_web_Route_middleware                                    5
#define ES_ejs_web_Route_module                                        6
#define ES_ejs_web_Route_name                                          7
#define ES_ejs_web_Route_params                                        8
#define ES_ejs_web_Route_provider                                      9
#define ES_ejs_web_Route_rewrite                                       10
#define ES_ejs_web_Route_router                                        11
#define ES_ejs_web_Route_subroute                                      12
#define ES_ejs_web_Route_threaded                                      13
#define ES_ejs_web_Route_trace                                         14
#define ES_ejs_web_Route_type                                          15
#define ES_ejs_web_Route_urimaker                                      16
#define ES_ejs_web_Route_matcher                                       17
#define ES_ejs_web_Route_splitter                                      18
#define ES_ejs_web_Route_tokens                                        19
#define ES_ejs_web_Route_makeUri                                       20
#define ES_ejs_web_Route_NUM_INSTANCE_PROP                             21
#define ES_ejs_web_Route_NUM_INHERITED_PROP                            0
#define ES_ejs_web_Session_NUM_CLASS_PROP                              0

/*
   Prototype (instance) slots for "Session" type 
 */
#define ES_ejs_web_Session_NUM_INSTANCE_PROP                           0
#define ES_ejs_web_Session_NUM_INHERITED_PROP                          0
#define ES_ejs_web_UploadFile_NUM_CLASS_PROP                           0

/*
   Prototype (instance) slots for "UploadFile" type 
 */
#define ES_ejs_web_UploadFile_clientFilename                           0
#define ES_ejs_web_UploadFile_contentType                              1
#define ES_ejs_web_UploadFile_filename                                 2
#define ES_ejs_web_UploadFile_name                                     3
#define ES_ejs_web_UploadFile_size                                     4
#define ES_ejs_web_UploadFile_NUM_INSTANCE_PROP                        5
#define ES_ejs_web_UploadFile_NUM_INHERITED_PROP                       0


/*
    Class property slots for the "View" type 
 */
#define ES_ejs_web_View__initializer___View_                           0
#define ES_ejs_web_View_htmlOptions                                    1
#define ES_ejs_web_View_NUM_CLASS_PROP                                 2

/*
   Prototype (instance) slots for "View" type 
 */
#define ES_ejs_web_View_currentRecord                                  0
#define ES_ejs_web_View_nextId                                         1
#define ES_ejs_web_View_config                                         2
#define ES_ejs_web_View_controller                                     3
#define ES_ejs_web_View_request                                        4
#define ES_ejs_web_View_log                                            5
#define ES_ejs_web_View_ejs_web_getNextId                              6
#define ES_ejs_web_View_ejs_web_makeUri                                7
#define ES_ejs_web_View_ejs_web_render                                 8
#define ES_ejs_web_View_ejs_web_setHeader                              9
#define ES_ejs_web_View_ejs_web_setHeaders                             10
#define ES_ejs_web_View_ejs_web_setStatus                              11
#define ES_ejs_web_View_ejs_web_show                                   12
#define ES_ejs_web_View_ejs_web_write                                  13
#define ES_ejs_web_View_ejs_web_aform                                  14
#define ES_ejs_web_View_ejs_web_alink                                  15
#define ES_ejs_web_View_ejs_web_button                                 16
#define ES_ejs_web_View_ejs_web_buttonLink                             17
#define ES_ejs_web_View_ejs_web_chart                                  18
#define ES_ejs_web_View_ejs_web_checkbox                               19
#define ES_ejs_web_View_ejs_web_endform                                20
#define ES_ejs_web_View_ejs_web_form                                   21
#define ES_ejs_web_View_ejs_web_image                                  22
#define ES_ejs_web_View_ejs_web_imageLink                              23
#define ES_ejs_web_View_ejs_web_input                                  24
#define ES_ejs_web_View_ejs_web_label                                  25
#define ES_ejs_web_View_ejs_web_link                                   26
#define ES_ejs_web_View_ejs_web_extlink                                27
#define ES_ejs_web_View_ejs_web_list                                   28
#define ES_ejs_web_View_ejs_web_mail                                   29
#define ES_ejs_web_View_ejs_web_progress                               30
#define ES_ejs_web_View_ejs_web_radio                                  31
#define ES_ejs_web_View_ejs_web_script                                 32
#define ES_ejs_web_View_ejs_web_status                                 33
#define ES_ejs_web_View_ejs_web_stylesheet                             34
#define ES_ejs_web_View_ejs_web_table                                  35
#define ES_ejs_web_View_ejs_web_tabs                                   36
#define ES_ejs_web_View_ejs_web_text                                   37
#define ES_ejs_web_View_ejs_web_textarea                               38
#define ES_ejs_web_View_ejs_web_tree                                   39
#define ES_ejs_web_View_ejs_web_flash                                  40
#define ES_ejs_web_View_emitFormErrors                                 41
#define ES_ejs_web_View_getConnector                                   42
#define ES_ejs_web_View_setOptions                                     43
#define ES_ejs_web_View_ejs_web_getValue                               44
#define ES_ejs_web_View_ejs_web_date                                   45
#define ES_ejs_web_View_ejs_web_currency                               46
#define ES_ejs_web_View_ejs_web_number                                 47
#define ES_ejs_web_View_ejs_web_getOptions                             48
#define ES_ejs_web_View_pivot                                          49
#define ES_ejs_web_View_filter                                         50
#define ES_ejs_web_View_NUM_INSTANCE_PROP                              51
#define ES_ejs_web_View_NUM_INHERITED_PROP                             0


/*
    Class property slots for the "Web" type 
 */
#define ES_ejs_web_Web__initializer___Web_                             0
#define ES_ejs_web_Web_config                                          1
#define ES_ejs_web_Web_defaultConfig                                   2
#define ES_ejs_web_Web_init                                            3
#define ES_ejs_web_Web_serve                                           4
#define ES_ejs_web_Web_worker                                          5
#define ES_ejs_web_Web_workerHelper                                    6
#define ES_ejs_web_Web_processBody                                     7
#define ES_ejs_web_Web_process                                         8
#define ES_ejs_web_Web_start                                           9
#define ES_ejs_web_Web_run                                             10
#define ES_ejs_web_Web_NUM_CLASS_PROP                                  11

/*
   Prototype (instance) slots for "Web" type 
 */
#define ES_ejs_web_Web_NUM_INSTANCE_PROP                               0
#define ES_ejs_web_Web_NUM_INHERITED_PROP                              0

/*
    Local slots for methods in type "Web" 
 */
#define ES_ejs_web_Web_serve_request                                   0
#define ES_ejs_web_Web_serve_router                                    1
#define ES_ejs_web_Web_worker_app                                      0
#define ES_ejs_web_Web_worker_request                                  1
#define ES_ejs_web_Web_workerHelper_app                                0
#define ES_ejs_web_Web_workerHelper_request                            1
#define ES_ejs_web_Web_processBody_request                             0
#define ES_ejs_web_Web_processBody_body                                1
#define ES_ejs_web_Web_process_app                                     0
#define ES_ejs_web_Web_process_request                                 1
#define ES_ejs_web_Web_process_finalize                                2
#define ES_ejs_web_Web_start_address                                   0
#define ES_ejs_web_Web_start_documentRoot                              1
#define ES_ejs_web_Web_start_serverRoot                                2
#define ES_ejs_web_Web_start_routes                                    3
#define ES_ejs_web_Web_run_address                                     0
#define ES_ejs_web_Web_run_documentRoot                                1
#define ES_ejs_web_Web_run_serverRoot                                  2

#define _ES_CHECKSUM_ejs_web   649770

#endif
