/*
   ejs.db.slots.h -- Native property slot definitions for the "ejs.db" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsDbSlots
#define _h_SLOTS_EjsDbSlots 1


/*
   Slots for the "ejs.db" module 
 */


/*
    Class property slots for the "Database" type 
 */
#define ES_ejs_db_Database__origin                                     26
#define ES_ejs_db_Database_Database                                    26
#define ES_ejs_db_Database_defaultDb                                   27
#define ES_ejs_db_Database_addColumn                                   28
#define ES_ejs_db_Database_addIndex                                    29
#define ES_ejs_db_Database_changeColumn                                30
#define ES_ejs_db_Database_close                                       31
#define ES_ejs_db_Database_commit                                      32
#define ES_ejs_db_Database_connect                                     33
#define ES_ejs_db_Database_connection                                  34
#define ES_ejs_db_Database_createDatabase                              35
#define ES_ejs_db_Database_createTable                                 36
#define ES_ejs_db_Database_dataTypeToSqlType                           37
#define ES_ejs_db_Database_defaultDatabase                             38
#define ES_ejs_db_Database_destroyDatabase                             39
#define ES_ejs_db_Database_destroyTable                                40
#define ES_ejs_db_Database_endTransaction                              41
#define ES_ejs_db_Database_getColumns                                  42
#define ES_ejs_db_Database_getTables                                   43
#define ES_ejs_db_Database_getNumRows                                  44
#define ES_ejs_db_Database_name                                        45
#define ES_ejs_db_Database_query                                       46
#define ES_ejs_db_Database_removeColumns                               47
#define ES_ejs_db_Database_removeIndex                                 48
#define ES_ejs_db_Database_renameColumn                                49
#define ES_ejs_db_Database_renameTable                                 50
#define ES_ejs_db_Database_rollback                                    51
#define ES_ejs_db_Database_sql                                         52
#define ES_ejs_db_Database_sqlTypeToDataType                           53
#define ES_ejs_db_Database_sqlTypeToEjsType                            54
#define ES_ejs_db_Database_startTransaction                            55
#define ES_ejs_db_Database_trace                                       56
#define ES_ejs_db_Database_transaction                                 57
#define ES_ejs_db_Database_quote                                       58

#define ES_ejs_db_Database_NUM_CLASS_PROP                              59

/*
 * Instance slots for "Database" type 
 */
#define ES_ejs_db_Database__adapter                                    0
#define ES_ejs_db_Database__connection                                 1
#define ES_ejs_db_Database__name                                       2
#define ES_ejs_db_Database__traceAll                                   3
#define ES_ejs_db_Database_NUM_INSTANCE_PROP                           4

/*
    Local slots for methods in type "Database" 
 */
#define ES_ejs_db_Database_Database_adapter                            0
#define ES_ejs_db_Database_Database_connectionString                   1
#define ES_ejs_db_Database_addColumn_table                             0
#define ES_ejs_db_Database_addColumn_column                            1
#define ES_ejs_db_Database_addColumn_datatype                          2
#define ES_ejs_db_Database_addColumn_options                           3
#define ES_ejs_db_Database_addIndex_table                              0
#define ES_ejs_db_Database_addIndex_column                             1
#define ES_ejs_db_Database_addIndex_index                              2
#define ES_ejs_db_Database_changeColumn_table                          0
#define ES_ejs_db_Database_changeColumn_column                         1
#define ES_ejs_db_Database_changeColumn_datatype                       2
#define ES_ejs_db_Database_changeColumn_options                        3
#define ES_ejs_db_Database_connect_connectionString                    0
#define ES_ejs_db_Database_createDatabase_name                         0
#define ES_ejs_db_Database_createDatabase_options                      1
#define ES_ejs_db_Database_createTable_table                           0
#define ES_ejs_db_Database_createTable_columns                         1
#define ES_ejs_db_Database_dataTypeToSqlType_dataType                  0
#define ES_ejs_db_Database_destroyDatabase_name                        0
#define ES_ejs_db_Database_destroyTable_table                          0
#define ES_ejs_db_Database_getColumns_table                            0
#define ES_ejs_db_Database_getNumRows_table                            0
#define ES_ejs_db_Database_query_cmd                                   0
#define ES_ejs_db_Database_query_tag                                   1
#define ES_ejs_db_Database_query_trace                                 2
#define ES_ejs_db_Database_removeColumns_table                         0
#define ES_ejs_db_Database_removeColumns_columns                       1
#define ES_ejs_db_Database_removeIndex_table                           0
#define ES_ejs_db_Database_removeIndex_index                           1
#define ES_ejs_db_Database_renameColumn_table                          0
#define ES_ejs_db_Database_renameColumn_oldColumn                      1
#define ES_ejs_db_Database_renameColumn_newColumn                      2
#define ES_ejs_db_Database_renameTable_oldTable                        0
#define ES_ejs_db_Database_renameTable_newTable                        1
#define ES_ejs_db_Database_sql_cmd                                     0
#define ES_ejs_db_Database_sqlTypeToDataType_sqlType                   0
#define ES_ejs_db_Database_sqlTypeToEjsType_sqlType                    0
#define ES_ejs_db_Database_trace_on                                    0
#define ES_ejs_db_Database_transaction_code                            0
#define ES_ejs_db_Database_quote_str                                   0


/*
    Class property slots for the "DatabaseConnector" type 
 */
#define ES_ejs_db_DatabaseConnector__origin                            0
#define ES_ejs_db_DatabaseConnector_addColumn                          0
#define ES_ejs_db_DatabaseConnector_addIndex                           1
#define ES_ejs_db_DatabaseConnector_changeColumn                       2
#define ES_ejs_db_DatabaseConnector_close                              3
#define ES_ejs_db_DatabaseConnector_commit                             4
#define ES_ejs_db_DatabaseConnector_connect                            5
#define ES_ejs_db_DatabaseConnector_createDatabase                     6
#define ES_ejs_db_DatabaseConnector_createTable                        7
#define ES_ejs_db_DatabaseConnector_dataTypeToSqlType                  8
#define ES_ejs_db_DatabaseConnector_destroyDatabase                    9
#define ES_ejs_db_DatabaseConnector_destroyTable                       10
#define ES_ejs_db_DatabaseConnector_getColumns                         11
#define ES_ejs_db_DatabaseConnector_getTables                          12
#define ES_ejs_db_DatabaseConnector_removeColumns                      13
#define ES_ejs_db_DatabaseConnector_removeIndex                        14
#define ES_ejs_db_DatabaseConnector_renameColumn                       15
#define ES_ejs_db_DatabaseConnector_renameTable                        16
#define ES_ejs_db_DatabaseConnector_rollback                           17
#define ES_ejs_db_DatabaseConnector_sql                                18
#define ES_ejs_db_DatabaseConnector_sqlTypeToDataType                  19
#define ES_ejs_db_DatabaseConnector_sqlTypeToEjsType                   20
#define ES_ejs_db_DatabaseConnector_startTransaction                   21

#define ES_ejs_db_DatabaseConnector_NUM_CLASS_PROP                     22
#define ES_ejs_db_DatabaseConnector_NUM_INSTANCE_PROP                  0

/*
    Local slots for methods in type "DatabaseConnector" 
 */
#define ES_ejs_db_DatabaseConnector_addColumn_table                    0
#define ES_ejs_db_DatabaseConnector_addColumn_column                   1
#define ES_ejs_db_DatabaseConnector_addColumn_datatype                 2
#define ES_ejs_db_DatabaseConnector_addColumn_options                  3
#define ES_ejs_db_DatabaseConnector_addIndex_table                     0
#define ES_ejs_db_DatabaseConnector_addIndex_column                    1
#define ES_ejs_db_DatabaseConnector_addIndex_index                     2
#define ES_ejs_db_DatabaseConnector_changeColumn_table                 0
#define ES_ejs_db_DatabaseConnector_changeColumn_column                1
#define ES_ejs_db_DatabaseConnector_changeColumn_datatype              2
#define ES_ejs_db_DatabaseConnector_changeColumn_options               3
#define ES_ejs_db_DatabaseConnector_connect_connectionString           0
#define ES_ejs_db_DatabaseConnector_createDatabase_name                0
#define ES_ejs_db_DatabaseConnector_createDatabase_options             1
#define ES_ejs_db_DatabaseConnector_createTable_table                  0
#define ES_ejs_db_DatabaseConnector_createTable_columns                1
#define ES_ejs_db_DatabaseConnector_dataTypeToSqlType_dataType         0
#define ES_ejs_db_DatabaseConnector_destroyDatabase_name               0
#define ES_ejs_db_DatabaseConnector_destroyTable_table                 0
#define ES_ejs_db_DatabaseConnector_getColumns_table                   0
#define ES_ejs_db_DatabaseConnector_removeColumns_table                0
#define ES_ejs_db_DatabaseConnector_removeColumns_columns              1
#define ES_ejs_db_DatabaseConnector_removeIndex_table                  0
#define ES_ejs_db_DatabaseConnector_removeIndex_index                  1
#define ES_ejs_db_DatabaseConnector_renameColumn_table                 0
#define ES_ejs_db_DatabaseConnector_renameColumn_oldColumn             1
#define ES_ejs_db_DatabaseConnector_renameColumn_newColumn             2
#define ES_ejs_db_DatabaseConnector_renameTable_oldTable               0
#define ES_ejs_db_DatabaseConnector_renameTable_newTable               1
#define ES_ejs_db_DatabaseConnector_sql_cmd                            0
#define ES_ejs_db_DatabaseConnector_sqlTypeToDataType_sqlType          0
#define ES_ejs_db_DatabaseConnector_sqlTypeToEjsType_sqlType           0

#define _ES_CHECKSUM_ejs_db   123160

#endif
