/*
   ejs.cjs.slots.h -- Native property slot definitions for the "ejs.cjs" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsCjsSlots
#define _h_SLOTS_EjsCjsSlots 1


/*
   Slots for the "ejs.cjs" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "CommonSystem" type 
 */
#define ES_ejs_cjs_CommonSystem_stdin                                  0
#define ES_ejs_cjs_CommonSystem_stdout                                 1
#define ES_ejs_cjs_CommonSystem_stderr                                 2
#define ES_ejs_cjs_CommonSystem_args                                   3
#define ES_ejs_cjs_CommonSystem_env                                    4
#define ES_ejs_cjs_CommonSystem_fs                                     5
#define ES_ejs_cjs_CommonSystem_platform                               6
#define ES_ejs_cjs_CommonSystem_system                                 7
#define ES_ejs_cjs_CommonSystem_NUM_CLASS_PROP                         8

/*
   Prototype (instance) slots for "CommonSystem" type 
 */
#define ES_ejs_cjs_CommonSystem_log                                    0
#define ES_ejs_cjs_CommonSystem_NUM_INSTANCE_PROP                      1
#define ES_ejs_cjs_CommonSystem_NUM_INHERITED_PROP                     0
#define ES_ejs_cjs_CommonFile_NUM_CLASS_PROP                           0

/*
   Prototype (instance) slots for "CommonFile" type 
 */
#define ES_ejs_cjs_CommonFile_open                                     0
#define ES_ejs_cjs_CommonFile_read                                     1
#define ES_ejs_cjs_CommonFile_basename                                 2
#define ES_ejs_cjs_CommonFile_write                                    3
#define ES_ejs_cjs_CommonFile_NUM_INSTANCE_PROP                        4
#define ES_ejs_cjs_CommonFile_NUM_INHERITED_PROP                       0

#define _ES_CHECKSUM_ejs_cjs   18196

#endif
