/*
   ejs.unix.slots.h -- Native property slot definitions for the "ejs.unix" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsUnixSlots
#define _h_SLOTS_EjsUnixSlots 1


/*
   Slots for the "ejs.unix" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_basename_path                                               0
#define ES_chdir_dir                                                   0
#define ES_chmod_path                                                  0
#define ES_chmod_perms                                                 1
#define ES_cp_fromPath                                                 0
#define ES_cp_toPath                                                   1
#define ES_dirname_path                                                0
#define ES_exists_path                                                 0
#define ES_extension_path                                              0
#define ES_freeSpace_path                                              0
#define ES_isDir_path                                                  0
#define ES_kill_pid                                                    0
#define ES_kill_signal                                                 1
#define ES_ls_path                                                     0
#define ES_ls_enumDirs                                                 1
#define ES_find_path                                                   0
#define ES_find_glob                                                   1
#define ES_find_recurse                                                2
#define ES_mkdir_path                                                  0
#define ES_mkdir_permissions                                           1
#define ES_mv_fromFile                                                 0
#define ES_mv_toFile                                                   1
#define ES_rm_path                                                     0
#define ES_rmdir_path                                                  0
#define ES_rmdir_contents                                              1
#define ES_tempname_directory                                          0

#define _ES_CHECKSUM_ejs_unix   31952

#endif
