/*
   ejs.cjs.slots.h -- Native property slot definitions for the "ejs.cjs" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsCjsSlots
#define _h_SLOTS_EjsCjsSlots 1


/*
   Slots for the "ejs.cjs" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_ejs_cjs_require_id                                          0


/*
    Class property slots for the "Loader" type 
 */
#define ES_Loader__initializer___Loader_                               0
#define ES_Loader_prototype                                            1
#define ES_Loader_mainId                                               2
#define ES_Loader_signatures                                           3
#define ES_Loader_timestamps                                           4
#define ES_Loader_defaultExtensions                                    5
#define ES_Loader_config                                               6
#define ES_Loader_init                                                 7
#define ES_Loader_require                                              8
#define ES_Loader_load                                                 9
#define ES_Loader_cached                                               10
#define ES_Loader_wrap                                                 11
#define ES_Loader_locate                                               12
#define ES_Loader_setConfig                                            13

#define ES_Loader_NUM_CLASS_PROP                                       14

/*
   Prototype (instance) slots for "Loader" type 
 */
#define ES_Loader_NUM_INSTANCE_PROP                                    0
#define ES_Loader_NUM_INHERITED_PROP                                   0

/*
    Local slots for methods in type "Loader" 
 */
#define ES_Loader_init_mainId                                          0
#define ES_Loader_require_id                                           0
#define ES_Loader_load_id                                              0
#define ES_Loader_load_path                                            1
#define ES_Loader_load_codeReader                                      2
#define ES_Loader_cached_path                                          0
#define ES_Loader_cached_cachedir                                      1
#define ES_Loader_wrap_code                                            0
#define ES_Loader_locate_id                                            0
#define ES_Loader_setConfig_newConfig                                  0

#define _ES_CHECKSUM_ejs_cjs   26632

#endif
