/*
   ejs.db.slots.h -- Native property slot definitions for the "ejs.db" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsDbSlots
#define _h_SLOTS_EjsDbSlots 1


/*
   Slots for the "ejs.db" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Database" type 
 */
#define ES_ejs_db_Database_defaultDb                                   0
#define ES_ejs_db_Database_defaultDatabase                             1
#define ES_ejs_db_Database_quote                                       2
#define ES_ejs_db_Database_prototype                                   3

#define ES_ejs_db_Database_NUM_CLASS_PROP                              4

/*
   Prototype (instance) slots for "Database" type 
 */
#define ES_ejs_db_Database_constructor                                 0
#define ES_ejs_db_Database_clone                                       1
#define ES_ejs_db_Database_iterator_get                                2
#define ES_ejs_db_Database_iterator_getValues                          3
#define ES_ejs_db_Database_hasOwnProperty                              4
#define ES_ejs_db_Database_isPrototypeOf                               5
#define ES_ejs_db_Database_propertyIsEnumerable                        6
#define ES_ejs_db_Database_toJSON                                      7
#define ES_ejs_db_Database_toLocaleString                              8
#define ES_ejs_db_Database_toString                                    9
#define ES_ejs_db_Database_valueOf                                     10
#define ES_ejs_db_Database__adapter                                    11
#define ES_ejs_db_Database__connection                                 12
#define ES_ejs_db_Database__name                                       13
#define ES_ejs_db_Database__traceAll                                   14
#define ES_ejs_db_Database_addColumn                                   15
#define ES_ejs_db_Database_addIndex                                    16
#define ES_ejs_db_Database_changeColumn                                17
#define ES_ejs_db_Database_close                                       18
#define ES_ejs_db_Database_commit                                      19
#define ES_ejs_db_Database_connect                                     20
#define ES_ejs_db_Database_connection                                  21
#define ES_ejs_db_Database_createDatabase                              22
#define ES_ejs_db_Database_createTable                                 23
#define ES_ejs_db_Database_dataTypeToSqlType                           24
#define ES_ejs_db_Database_destroyDatabase                             25
#define ES_ejs_db_Database_destroyTable                                26
#define ES_ejs_db_Database_endTransaction                              27
#define ES_ejs_db_Database_getColumns                                  28
#define ES_ejs_db_Database_getTables                                   29
#define ES_ejs_db_Database_getNumRows                                  30
#define ES_ejs_db_Database_name                                        31
#define ES_ejs_db_Database_query                                       32
#define ES_ejs_db_Database_removeColumns                               33
#define ES_ejs_db_Database_removeIndex                                 34
#define ES_ejs_db_Database_renameColumn                                35
#define ES_ejs_db_Database_renameTable                                 36
#define ES_ejs_db_Database_rollback                                    37
#define ES_ejs_db_Database_sql                                         38
#define ES_ejs_db_Database_sqlTypeToDataType                           39
#define ES_ejs_db_Database_sqlTypeToEjsType                            40
#define ES_ejs_db_Database_startTransaction                            41
#define ES_ejs_db_Database_trace                                       42
#define ES_ejs_db_Database_transaction                                 43
#define ES_ejs_db_Database_NUM_INSTANCE_PROP                           44
#define ES_ejs_db_Database_NUM_INHERITED_PROP                          11

/*
    Local slots for methods in type "Database" 
 */
#define ES_ejs_db_Database_quote_str                                   0


/*
    Class property slots for the "DatabaseConnector" type 
 */
#define ES_ejs_db_DatabaseConnector_prototype                          0

#define ES_ejs_db_DatabaseConnector_NUM_CLASS_PROP                     1

/*
   Prototype (instance) slots for "DatabaseConnector" type 
 */
#define ES_ejs_db_DatabaseConnector_addColumn                          0
#define ES_ejs_db_DatabaseConnector_addIndex                           1
#define ES_ejs_db_DatabaseConnector_changeColumn                       2
#define ES_ejs_db_DatabaseConnector_close                              3
#define ES_ejs_db_DatabaseConnector_commit                             4
#define ES_ejs_db_DatabaseConnector_connect                            5
#define ES_ejs_db_DatabaseConnector_createDatabase                     6
#define ES_ejs_db_DatabaseConnector_createTable                        7
#define ES_ejs_db_DatabaseConnector_dataTypeToSqlType                  8
#define ES_ejs_db_DatabaseConnector_destroyDatabase                    9
#define ES_ejs_db_DatabaseConnector_destroyTable                       10
#define ES_ejs_db_DatabaseConnector_getColumns                         11
#define ES_ejs_db_DatabaseConnector_getTables                          12
#define ES_ejs_db_DatabaseConnector_removeColumns                      13
#define ES_ejs_db_DatabaseConnector_removeIndex                        14
#define ES_ejs_db_DatabaseConnector_renameColumn                       15
#define ES_ejs_db_DatabaseConnector_renameTable                        16
#define ES_ejs_db_DatabaseConnector_rollback                           17
#define ES_ejs_db_DatabaseConnector_sql                                18
#define ES_ejs_db_DatabaseConnector_sqlTypeToDataType                  19
#define ES_ejs_db_DatabaseConnector_sqlTypeToEjsType                   20
#define ES_ejs_db_DatabaseConnector_startTransaction                   21
#define ES_ejs_db_DatabaseConnector_NUM_INSTANCE_PROP                  22
#define ES_ejs_db_DatabaseConnector_NUM_INHERITED_PROP                 0

#define _ES_CHECKSUM_ejs_db   124596

#endif
