/*
   ejs.tar.slots.h -- Native property slot definitions for the "ejs.tar" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsTarSlots
#define _h_SLOTS_EjsTarSlots 1


/*
   Slots for the "ejs.tar" module 
 */


/*
    Class property slots for the "Tar" type 
 */
#define ES_ejs_tar_Tar__origin                                         27
#define ES_ejs_tar_Tar_Tar                                             27
#define ES_ejs_tar_Tar_add                                             28
#define ES_ejs_tar_Tar_xcreate                                         29
#define ES_ejs_tar_Tar_extract                                         30
#define ES_ejs_tar_Tar_cat                                             31

#define ES_ejs_tar_Tar_NUM_CLASS_PROP                                  32

/*
 * Instance slots for "Tar" type 
 */
#define ES_ejs_tar_Tar_path                                            0
#define ES_ejs_tar_Tar_files                                           1
#define ES_ejs_tar_Tar_NUM_INSTANCE_PROP                               2

/*
    Local slots for methods in type "Tar" 
 */
#define ES_ejs_tar_Tar_Tar_path                                        0
#define ES_ejs_tar_Tar_add_path                                        0
#define ES_ejs_tar_Tar_extract_files                                   0
#define ES_ejs_tar_Tar_cat_files                                       0

#define _ES_CHECKSUM_ejs_tar   8361

#endif
