/*
   ejs.db.couch.slots.h -- Native property slot definitions for the "ejs.db.couch" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsDbCouchSlots
#define _h_SLOTS_EjsDbCouchSlots 1


/*
   Slots for the "ejs.db.couch" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "Couch" type 
 */
#define ES_ejs_db_couch_Couch_prototype                                0

#define ES_ejs_db_couch_Couch_NUM_CLASS_PROP                           1

/*
   Prototype (instance) slots for "Couch" type 
 */
#define ES_ejs_db_couch_Couch_constructor                              0
#define ES_ejs_db_couch_Couch_clone                                    1
#define ES_ejs_db_couch_Couch_iterator_get                             2
#define ES_ejs_db_couch_Couch_iterator_getValues                       3
#define ES_ejs_db_couch_Couch_hasOwnProperty                           4
#define ES_ejs_db_couch_Couch_isPrototypeOf                            5
#define ES_ejs_db_couch_Couch_propertyIsEnumerable                     6
#define ES_ejs_db_couch_Couch_toJSON                                   7
#define ES_ejs_db_couch_Couch_toLocaleString                           8
#define ES_ejs_db_couch_Couch_toString                                 9
#define ES_ejs_db_couch_Couch_valueOf                                  10
#define ES_ejs_db_couch_Couch_db                                       11
#define ES_ejs_db_couch_Couch_uri                                      12
#define ES_ejs_db_couch_Couch_hp                                       13
#define ES_ejs_db_couch_Couch_addListener                              14
#define ES_ejs_db_couch_Couch_async                                    15
#define ES_ejs_db_couch_Couch_close                                    16
#define ES_ejs_db_couch_Couch_cmd                                      17
#define ES_ejs_db_couch_Couch_flush                                    18
#define ES_ejs_db_couch_Couch_http                                     19
#define ES_ejs_db_couch_Couch_removeListener                           20
#define ES_ejs_db_couch_Couch_status                                   21
#define ES_ejs_db_couch_Couch_success                                  22
#define ES_ejs_db_couch_Couch_read                                     23
#define ES_ejs_db_couch_Couch_write                                    24
#define ES_ejs_db_couch_Couch_getDatabases                             25
#define ES_ejs_db_couch_Couch_bulkUpdate                               26
#define ES_ejs_db_couch_Couch_compact                                  27
#define ES_ejs_db_couch_Couch_createDatabase                           28
#define ES_ejs_db_couch_Couch_destroyDatabase                          29
#define ES_ejs_db_couch_Couch_cleanupView                              30
#define ES_ejs_db_couch_Couch_getDocuments                             31
#define ES_ejs_db_couch_Couch_createDoc                                32
#define ES_ejs_db_couch_Couch_deleteDoc                                33
#define ES_ejs_db_couch_Couch_getDoc                                   34
#define ES_ejs_db_couch_Couch_updateDoc                                35
#define ES_ejs_db_couch_Couch_tempView                                 36
#define ES_ejs_db_couch_Couch_view                                     37
#define ES_ejs_db_couch_Couch_NUM_INSTANCE_PROP                        38
#define ES_ejs_db_couch_Couch_NUM_INHERITED_PROP                       11

#define _ES_CHECKSUM_ejs_db_couch   42322

#endif
