/*
   ejs.db.mapper.slots.h -- Native property slot definitions for the "ejs.db.mapper" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsDbMapperSlots
#define _h_SLOTS_EjsDbMapperSlots 1


/*
   Slots for the "ejs.db.mapper" module 
 */

/*
    Local slots for global methods 
 */
#define ES_ejs_db_mapper_plural_name                                   0
#define ES_ejs_db_mapper_singular_name                                 0
#define ES_ejs_db_mapper_mapType_value                                 0


/*
    Class property slots for the "Record" type 
 */
#define ES_Record__origin                                              26
#define ES_Record_Record                                               26
#define ES_Record__initializer__Record_initializer                     27
#define ES_Record__assocName                                           28
#define ES_Record__belongsTo                                           29
#define ES_Record__className                                           30
#define ES_Record__columns                                             31
#define ES_Record__hasOne                                              32
#define ES_Record__hasMany                                             33
#define ES_Record__db                                                  34
#define ES_Record__foreignId                                           35
#define ES_Record__keyName                                             36
#define ES_Record__model                                               37
#define ES_Record__tableName                                           38
#define ES_Record__trace                                               39
#define ES_Record__validations                                         40
#define ES_Record__beforeFilters                                       41
#define ES_Record__afterFilters                                        42
#define ES_Record__wrapFilters                                         43
#define ES_Record_ErrorMessages                                        44
#define ES_Record_initialize                                           45
#define ES_Record_afterFilter                                          46
#define ES_Record_beforeFilter                                         47
#define ES_Record_belongsTo                                            48
#define ES_Record_cachedRead                                           49
#define ES_Record_checkFormat                                          50
#define ES_Record_checkNumber                                          51
#define ES_Record_checkPresent                                         52
#define ES_Record_checkUnique                                          53
#define ES_Record_coerceToEjsTypes                                     54
#define ES_Record_createAssociations                                   55
#define ES_Record_createRecord                                         56
#define ES_Record_error                                                57
#define ES_Record_find                                                 58
#define ES_Record_findAll                                              59
#define ES_Record_findOneWhere                                         60
#define ES_Record_findWhere                                            61
#define ES_Record_getColumnNames                                       62
#define ES_Record_getColumnTitles                                      63
#define ES_Record_getColumnType                                        64
#define ES_Record_getDb                                                65
#define ES_Record_getErrors                                            66
#define ES_Record_getKeyName                                           67
#define ES_Record_getNumRows                                           68
#define ES_Record_getSchema                                            69
#define ES_Record_getTableName                                         70
#define ES_Record_hasAndBelongsToMany                                  71
#define ES_Record_hasError                                             72
#define ES_Record_hasMany                                              73
#define ES_Record_hasOne                                               74
#define ES_Record_innerFind                                            75
#define ES_Record_makeLazyReader                                       76
#define ES_Record_mapSqlTypeToEjs                                      77
#define ES_Record_prepareValue                                         78
#define ES_Record_readRecords                                          79
#define ES_Record_remove                                               80
#define ES_Record_runFilters                                           81
#define ES_Record_save                                                 82
#define ES_Record_saveUpdate                                           83
#define ES_Record_setDb                                                84
#define ES_Record_setKeyName                                           85
#define ES_Record_setTableName                                         86
#define ES_Record_sql                                                  87
#define ES_Record_trace                                                88
#define ES_Record_validateFormat                                       89
#define ES_Record_validateNumber                                       90
#define ES_Record_validatePresence                                     91
#define ES_Record_validateRecord                                       92
#define ES_Record_validateUnique                                       93
#define ES_Record_wrapFilter                                           94
#define ES_Record_columnNames                                          95
#define ES_Record_columnTitles                                         96
#define ES_Record_db                                                   97
#define ES_Record_keyName                                              98
#define ES_Record_numRows                                              99
#define ES_Record_tableName                                            100
#define ES_Record_constructorOLD                                       101

#define ES_Record_NUM_CLASS_PROP                                       102

/*
 * Instance slots for "Record" type 
 */
#define ES_Record__keyValue                                            0
#define ES_Record__errors                                              1
#define ES_Record__cacheAssoc                                          2
#define ES_Record_NUM_INSTANCE_PROP                                    3

/*
    Local slots for methods in type "Record" 
 */
#define ES_Record_Record_fields                                        0
#define ES_Record_initialize_fields                                    0
#define ES_Record_afterFilter_fn                                       0
#define ES_Record_afterFilter_options                                  1
#define ES_Record_beforeFilter_fn                                      0
#define ES_Record_beforeFilter_options                                 1
#define ES_Record_belongsTo_owner                                      0
#define ES_Record_belongsTo_options                                    1
#define ES_Record_cachedRead_rec                                       0
#define ES_Record_cachedRead_field                                     1
#define ES_Record_cachedRead_model                                     2
#define ES_Record_cachedRead_key                                       3
#define ES_Record_cachedRead_options                                   4
#define ES_Record_checkFormat_thisObj                                  0
#define ES_Record_checkFormat_field                                    1
#define ES_Record_checkFormat_value                                    2
#define ES_Record_checkFormat_options                                  3
#define ES_Record_checkNumber_thisObj                                  0
#define ES_Record_checkNumber_field                                    1
#define ES_Record_checkNumber_value                                    2
#define ES_Record_checkNumber_options                                  3
#define ES_Record_checkPresent_thisObj                                 0
#define ES_Record_checkPresent_field                                   1
#define ES_Record_checkPresent_value                                   2
#define ES_Record_checkPresent_options                                 3
#define ES_Record_checkUnique_thisObj                                  0
#define ES_Record_checkUnique_field                                    1
#define ES_Record_checkUnique_value                                    2
#define ES_Record_checkUnique_options                                  3
#define ES_Record_createAssociations_rec                               0
#define ES_Record_createAssociations_set                               1
#define ES_Record_createAssociations_preload                           2
#define ES_Record_createAssociations_options                           3
#define ES_Record_createRecord_data                                    0
#define ES_Record_createRecord_options                                 1
#define ES_Record_error_field                                          0
#define ES_Record_error_msg                                            1
#define ES_Record_find_key                                             0
#define ES_Record_find_options                                         1
#define ES_Record_findAll_options                                      0
#define ES_Record_findOneWhere_where                                   0
#define ES_Record_findWhere_where                                      0
#define ES_Record_findWhere_count                                      1
#define ES_Record_getColumnType_field                                  0
#define ES_Record_hasAndBelongsToMany_model                            0
#define ES_Record_hasAndBelongsToMany_options                          1
#define ES_Record_hasError_field                                       0
#define ES_Record_hasMany_model                                        0
#define ES_Record_hasMany_options                                      1
#define ES_Record_hasOne_model                                         0
#define ES_Record_hasOne_options                                       1
#define ES_Record_innerFind_key                                        0
#define ES_Record_innerFind_limit                                      1
#define ES_Record_innerFind_options                                    2
#define ES_Record_makeLazyReader_rec                                   0
#define ES_Record_makeLazyReader_field                                 1
#define ES_Record_makeLazyReader_model                                 2
#define ES_Record_makeLazyReader_key                                   3
#define ES_Record_makeLazyReader_options                               4
#define ES_Record_mapSqlTypeToEjs_sqlType                              0
#define ES_Record_prepareValue_field                                   0
#define ES_Record_prepareValue_value                                   1
#define ES_Record_readRecords_key                                      0
#define ES_Record_readRecords_options                                  1
#define ES_Record_remove_ids                                           0
#define ES_Record_runFilters_filters                                   0
#define ES_Record_saveUpdate_fields                                    0
#define ES_Record_setDb_database                                       0
#define ES_Record_setKeyName_name                                      0
#define ES_Record_setTableName_name                                    0
#define ES_Record_sql_cmd                                              0
#define ES_Record_sql_count                                            1
#define ES_Record_trace_on                                             0
#define ES_Record_validateFormat_fields                                0
#define ES_Record_validateFormat_options                               1
#define ES_Record_validateNumber_fields                                0
#define ES_Record_validateNumber_options                               1
#define ES_Record_validatePresence_fields                              0
#define ES_Record_validatePresence_options                             1
#define ES_Record_validateUnique_fields                                0
#define ES_Record_validateUnique_option                                1
#define ES_Record_wrapFilter_fn                                        0
#define ES_Record_wrapFilter_options                                   1
#define ES_Record_constructorOLD_fields                                0


/*
    Class property slots for the "Column" type 
 */
#define ES_ejs_db_mapper_Column__origin                                26
#define ES_ejs_db_mapper_Column_Column                                 26

#define ES_ejs_db_mapper_Column_NUM_CLASS_PROP                         27

/*
 * Instance slots for "Column" type 
 */
#define ES_ejs_db_mapper_Column_ejsType                                0
#define ES_ejs_db_mapper_Column_sqlType                                1
#define ES_ejs_db_mapper_Column_NUM_INSTANCE_PROP                      2

/*
    Local slots for methods in type "Column" 
 */
#define ES_ejs_db_mapper_Column_Column_name                            0
#define ES_ejs_db_mapper_Column_Column_accessor                        1
#define ES_ejs_db_mapper_Column_Column_ejsType                         2
#define ES_ejs_db_mapper_Column_Column_sqlType                         3

#define _ES_CHECKSUM_ejs_db_mapper   190860

#endif
