/*
   ejs.web.slots.h -- Native property slot definitions for the "ejs.web" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.0.0.
 */

#ifndef _h_SLOTS_EjsWebSlots
#define _h_SLOTS_EjsWebSlots 1


/*
   Slots for the "ejs.web" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_ejs_web_DirApp_request                                      0
#define ES_ejs_web_DirBuilder_request                                  0
#define ES_ejs_web_Middleware_app                                      0
#define ES_ejs_web_Middleware_middleware                               1
#define ES_ejs_web_Monitor2_app                                        0
#define ES_ejs_web_Monitor_app                                         0
#define ES_ejs_web_MvcApp_request                                      0
#define ES_ejs_web_MvcBuilder_request                                  0
#define ES_ejs_web_ScriptBuilder_request                               0
#define ES_ejs_web_TemplateBuilder_request                             0
#define ES_ejs_web_StaticApp_request                                   0
#define ES_ejs_web_StaticBuilder_request                               0
#define ES_ejs_web_TemplateFilter_app                                  0
#define ES_ejs_web_TemplateApp_request                                 0
#define ES_ejs_web_errorBody_title                                     0
#define ES_ejs_web_errorBody_msg                                       1
#define ES_ejs_web_parseCookies_cookieHeader                           0
#define ES_ejs_web_escapeHtml_str                                      0
#define ES_ejs_web_html_args                                           0
#define ES_ejs_web_unescapeHtml_s                                      0


/*
    Class property slots for the "Controller" type 
 */
#define ES_ejs_web_Controller__initRequest                             0
#define ES_ejs_web_Controller_ejs_web_create                           1
#define ES_ejs_web_Controller_NUM_CLASS_PROP                           2

/*
   Prototype (instance) slots for "Controller" type 
 */
#define ES_ejs_web_Controller_ejs_web_actionName                       0
#define ES_ejs_web_Controller_ejs_web_config                           1
#define ES_ejs_web_Controller_ejs_web_controllerName                   2
#define ES_ejs_web_Controller_ejs_web_deploymentMode                   3
#define ES_ejs_web_Controller_ejs_web_log                              4
#define ES_ejs_web_Controller_ejs_web_params                           5
#define ES_ejs_web_Controller_ejs_web_request                          6
#define ES_ejs_web_Controller_ejs_web_view                             7
#define ES_ejs_web_Controller_flash                                    8
#define ES_ejs_web_Controller_rendered                                 9
#define ES_ejs_web_Controller_redirected                               10
#define ES_ejs_web_Controller__afterFilters                            11
#define ES_ejs_web_Controller__beforeFilters                           12
#define ES_ejs_web_Controller__wrapFilters                             13
#define ES_ejs_web_Controller_lastFlash                                14
#define ES_ejs_web_Controller_openDatabase                             15
#define ES_ejs_web_Controller_ejs_web_run                              16
#define ES_ejs_web_Controller_flashBefore                              17
#define ES_ejs_web_Controller_flashAfter                               18
#define ES_ejs_web_Controller_ejs_web_resetFilters                     19
#define ES_ejs_web_Controller_ejs_web_beforeFilter                     20
#define ES_ejs_web_Controller_ejs_web_afterFilter                      21
#define ES_ejs_web_Controller_ejs_web_wrapFilter                       22
#define ES_ejs_web_Controller_runFilters                               23
#define ES_ejs_web_Controller_loadView                                 24
#define ES_ejs_web_Controller_ejs_web_renderError                      25
#define ES_ejs_web_Controller_ejs_web_redirect                         26
#define ES_ejs_web_Controller_ejs_web_redirectAction                   27
#define ES_ejs_web_Controller_ejs_web_render                           28
#define ES_ejs_web_Controller_ejs_web_renderFile                       29
#define ES_ejs_web_Controller_ejs_web_renderPartial                    30
#define ES_ejs_web_Controller_viewExists                               31
#define ES_ejs_web_Controller_ejs_web_renderView                       32
#define ES_ejs_web_Controller_ejs_web_error                            33
#define ES_ejs_web_Controller_ejs_web_inform                           34
#define ES_ejs_web_Controller_ejs_web_warn                             35
#define ES_ejs_web_Controller_ejs_web_makeUri                          36
#define ES_ejs_web_Controller_ejs_web_session                          37
#define ES_ejs_web_Controller_action_missing                           38
#define ES_ejs_web_Controller_ejs_web_appUrl                           39
#define ES_ejs_web_Controller_ejs_web_makeUrl                          40
#define ES_ejs_web_Controller_NUM_INSTANCE_PROP                        41
#define ES_ejs_web_Controller_NUM_INHERITED_PROP                       0

/*
    Local slots for methods in type "Controller" 
 */
#define ES_ejs_web_Controller_ejs_web_create_request                   0
#define ES_HtmlConnector_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "HtmlConnector" type 
 */
#define ES_HtmlConnector_request                                       0
#define ES_HtmlConnector_view                                          1
#define ES_HtmlConnector_ejs_web_aform                                 2
#define ES_HtmlConnector_ejs_web_alink                                 3
#define ES_HtmlConnector_ejs_web_button                                4
#define ES_HtmlConnector_ejs_web_buttonLink                            5
#define ES_HtmlConnector_ejs_web_chart                                 6
#define ES_HtmlConnector_ejs_web_checkbox                              7
#define ES_HtmlConnector_ejs_web_endform                               8
#define ES_HtmlConnector_ejs_web_flash                                 9
#define ES_HtmlConnector_ejs_web_form                                  10
#define ES_HtmlConnector_ejs_web_image                                 11
#define ES_HtmlConnector_ejs_web_imageLink                             12
#define ES_HtmlConnector_ejs_web_label                                 13
#define ES_HtmlConnector_ejs_web_link                                  14
#define ES_HtmlConnector_ejs_web_extlink                               15
#define ES_HtmlConnector_ejs_web_list                                  16
#define ES_HtmlConnector_ejs_web_mail                                  17
#define ES_HtmlConnector_ejs_web_progress                              18
#define ES_HtmlConnector_ejs_web_radio                                 19
#define ES_HtmlConnector_ejs_web_script                                20
#define ES_HtmlConnector_ejs_web_status                                21
#define ES_HtmlConnector_ejs_web_stylesheet                            22
#define ES_HtmlConnector_ejs_web_table                                 23
#define ES_HtmlConnector_ejs_web_tabs                                  24
#define ES_HtmlConnector_ejs_web_text                                  25
#define ES_HtmlConnector_ejs_web_textarea                              26
#define ES_HtmlConnector_ejs_web_tree                                  27
#define ES_HtmlConnector_getColumns                                    28
#define ES_HtmlConnector_getTextKind                                   29
#define ES_HtmlConnector_getOptions                                    30
#define ES_HtmlConnector_write                                         31
#define ES_HtmlConnector_getDataAttributes                             32
#define ES_HtmlConnector_NUM_INSTANCE_PROP                             33
#define ES_HtmlConnector_NUM_INHERITED_PROP                            0


/*
    Class property slots for the "HttpServer" type 
 */
#define ES_ejs_web_HttpServer__initializer___HttpServer_               0
#define ES_ejs_web_HttpServer_indicies                                 1
#define ES_ejs_web_HttpServer_NUM_CLASS_PROP                           2

/*
   Prototype (instance) slots for "HttpServer" type 
 */
#define ES_ejs_web_HttpServer_accept                                   0
#define ES_ejs_web_HttpServer_address                                  1
#define ES_ejs_web_HttpServer_async                                    2
#define ES_ejs_web_HttpServer_close                                    3
#define ES_ejs_web_HttpServer_documentRoot                             4
#define ES_ejs_web_HttpServer_isSecure                                 5
#define ES_ejs_web_HttpServer_listen                                   6
#define ES_ejs_web_HttpServer_name                                     7
#define ES_ejs_web_HttpServer_port                                     8
#define ES_ejs_web_HttpServer_observe                                  9
#define ES_ejs_web_HttpServer_removeObserver                           10
#define ES_ejs_web_HttpServer_secure                                   11
#define ES_ejs_web_HttpServer_setLimits                                12
#define ES_ejs_web_HttpServer_getLimits                                13
#define ES_ejs_web_HttpServer_setOptions                               14
#define ES_ejs_web_HttpServer_getOptions                               15
#define ES_ejs_web_HttpServer_trace                                    16
#define ES_ejs_web_HttpServer_traceFilter                              17
#define ES_ejs_web_HttpServer_setPipeline                              18
#define ES_ejs_web_HttpServer_verifyClients                            19
#define ES_ejs_web_HttpServer_serverRoot                               20
#define ES_ejs_web_HttpServer_software                                 21
#define ES_ejs_web_HttpServer_NUM_INSTANCE_PROP                        22
#define ES_ejs_web_HttpServer_NUM_INHERITED_PROP                       0


/*
    Class property slots for the "Mvc" type 
 */
#define ES_Mvc__initializer___Mvc_                                     0
#define ES_Mvc_apps                                                    1
#define ES_Mvc_defaultConfig                                           2
#define ES_Mvc_loaded                                                  3
#define ES_Mvc_EJSRC                                                   4
#define ES_Mvc_NUM_CLASS_PROP                                          5

/*
   Prototype (instance) slots for "Mvc" type 
 */
#define ES_Mvc_loadConfig                                              0
#define ES_Mvc_init                                                    1
#define ES_Mvc_loadComponent                                           2
#define ES_Mvc_NUM_INSTANCE_PROP                                       3
#define ES_Mvc_NUM_INHERITED_PROP                                      0


/*
    Class property slots for the "Request" type 
 */
#define ES_ejs_web_Request__initializer___Request_                     0
#define ES_ejs_web_Request_jsgi                                        1
#define ES_ejs_web_Request_NUM_CLASS_PROP                              2

/*
   Prototype (instance) slots for "Request" type 
 */
#define ES_ejs_web_Request_absHome                                     0
#define ES_ejs_web_Request_authGroup                                   1
#define ES_ejs_web_Request_authType                                    2
#define ES_ejs_web_Request_authUser                                    3
#define ES_ejs_web_Request_chunkSize                                   4
#define ES_ejs_web_Request_config                                      5
#define ES_ejs_web_Request_contentLength                               6
#define ES_ejs_web_Request_contentType                                 7
#define ES_ejs_web_Request_cookies                                     8
#define ES_ejs_web_Request_dir                                         9
#define ES_ejs_web_Request_encoding                                    10
#define ES_ejs_web_Request_files                                       11
#define ES_ejs_web_Request_filename                                    12
#define ES_ejs_web_Request_headers                                     13
#define ES_ejs_web_Request_home                                        14
#define ES_ejs_web_Request_host                                        15
#define ES_ejs_web_Request_inactivityTimeout                           16
#define ES_ejs_web_Request_isSecure                                    17
#define ES_ejs_web_Request_localAddress                                18
#define ES_ejs_web_Request_log                                         19
#define ES_ejs_web_Request_method                                      20
#define ES_ejs_web_Request_params                                      21
#define ES_ejs_web_Request_pathInfo                                    22
#define ES_ejs_web_Request_protocol                                    23
#define ES_ejs_web_Request_query                                       24
#define ES_ejs_web_Request_referrer                                    25
#define ES_ejs_web_Request_remoteAddress                               26
#define ES_ejs_web_Request_route                                       27
#define ES_ejs_web_Request_scheme                                      28
#define ES_ejs_web_Request_scriptName                                  29
#define ES_ejs_web_Request_server                                      30
#define ES_ejs_web_Request_session                                     31
#define ES_ejs_web_Request_sessionID                                   32
#define ES_ejs_web_Request_status                                      33
#define ES_ejs_web_Request_timeout                                     34
#define ES_ejs_web_Request_uri                                         35
#define ES_ejs_web_Request_userAgent                                   36
#define ES_ejs_web_Request_async                                       37
#define ES_ejs_web_Request_cachable                                    38
#define ES_ejs_web_Request_close                                       39
#define ES_ejs_web_Request_dontFinalize                                40
#define ES_ejs_web_Request_show                                        41
#define ES_ejs_web_Request_destroySession                              42
#define ES_ejs_web_Request_extension                                   43
#define ES_ejs_web_Request_finalize                                    44
#define ES_ejs_web_Request_flush                                       45
#define ES_ejs_web_Request_responseHeaders                             46
#define ES_ejs_web_Request_header                                      47
#define ES_ejs_web_Request_observe                                     48
#define ES_ejs_web_Request_read                                        49
#define ES_ejs_web_Request_redirect                                    50
#define ES_ejs_web_Request_removeObserver                              51
#define ES_ejs_web_Request_sendfile                                    52
#define ES_ejs_web_Request_makeUri                                     53
#define ES_ejs_web_Request_setLocation                                 54
#define ES_ejs_web_Request_sendResponse                                55
#define ES_ejs_web_Request_setCookie                                   56
#define ES_ejs_web_Request_setHeader                                   57
#define ES_ejs_web_Request_setHeaders                                  58
#define ES_ejs_web_Request_setStatus                                   59
#define ES_ejs_web_Request_write                                       60
#define ES_ejs_web_Request_error                                       61
#define ES_ejs_web_Request_writeHtml                                   62
#define ES_ejs_web_Request_env                                         63
#define ES_ejs_web_Request_input                                       64
#define ES_ejs_web_Request_queryString                                 65
#define ES_ejs_web_Request_serverName                                  66
#define ES_ejs_web_Request_serverPort                                  67
#define ES_ejs_web_Request_accept                                      68
#define ES_ejs_web_Request_acceptCharset                               69
#define ES_ejs_web_Request_acceptEncoding                              70
#define ES_ejs_web_Request_authAcl                                     71
#define ES_ejs_web_Request_body                                        72
#define ES_ejs_web_Request_connection                                  73
#define ES_ejs_web_Request_hostName                                    74
#define ES_ejs_web_Request_mimeType                                    75
#define ES_ejs_web_Request_pathTranslated                              76
#define ES_ejs_web_Request_pragma                                      77
#define ES_ejs_web_Request_remoteHost                                  78
#define ES_ejs_web_Request_url                                         79
#define ES_ejs_web_Request_originalUri                                 80
#define ES_ejs_web_Request_writeError                                  81
#define ES_ejs_web_Request_NUM_INSTANCE_PROP                           82
#define ES_ejs_web_Request_NUM_INHERITED_PROP                          0


/*
    Class property slots for the "Router" type 
 */
#define ES_ejs_web_Router__initializer___Router_                       0
#define ES_ejs_web_Router_isDir                                        1
#define ES_ejs_web_Router_TopRoutes                                    2
#define ES_ejs_web_Router_RestfulRoutes                                3
#define ES_ejs_web_Router_LegacyRoutes                                 4
#define ES_ejs_web_Router_NUM_CLASS_PROP                               5

/*
   Prototype (instance) slots for "Router" type 
 */
#define ES_ejs_web_Router_routes                                       0
#define ES_ejs_web_Router_addRestfulRoutes                             1
#define ES_ejs_web_Router_addRoutes                                    2
#define ES_ejs_web_Router_route                                        3
#define ES_ejs_web_Router_NUM_INSTANCE_PROP                            4
#define ES_ejs_web_Router_NUM_INHERITED_PROP                           0

/*
    Local slots for methods in type "Router" 
 */
#define ES_ejs_web_Router_isDir_request                                0
#define ES_ejs_web_Route_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "Route" type 
 */
#define ES_ejs_web_Route_builder                                       0
#define ES_ejs_web_Route_dir                                           1
#define ES_ejs_web_Route_match                                         2
#define ES_ejs_web_Route_method                                        3
#define ES_ejs_web_Route_middleware                                    4
#define ES_ejs_web_Route_module                                        5
#define ES_ejs_web_Route_name                                          6
#define ES_ejs_web_Route_params                                        7
#define ES_ejs_web_Route_provider                                      8
#define ES_ejs_web_Route_rewrite                                       9
#define ES_ejs_web_Route_router                                        10
#define ES_ejs_web_Route_subroute                                      11
#define ES_ejs_web_Route_threaded                                      12
#define ES_ejs_web_Route_type                                          13
#define ES_ejs_web_Route_urimaker                                      14
#define ES_ejs_web_Route_matcher                                       15
#define ES_ejs_web_Route_splitter                                      16
#define ES_ejs_web_Route_tokens                                        17
#define ES_ejs_web_Route_makeUri                                       18
#define ES_ejs_web_Route_NUM_INSTANCE_PROP                             19
#define ES_ejs_web_Route_NUM_INHERITED_PROP                            0


/*
    Class property slots for the "Session" type 
 */
#define ES_ejs_web_Session_count                                       0
#define ES_ejs_web_Session_NUM_CLASS_PROP                              1

/*
   Prototype (instance) slots for "Session" type 
 */
#define ES_ejs_web_Session_timeout                                     0
#define ES_ejs_web_Session_NUM_INSTANCE_PROP                           1
#define ES_ejs_web_Session_NUM_INHERITED_PROP                          0
#define ES_ejs_web_UploadFile_NUM_CLASS_PROP                           0

/*
   Prototype (instance) slots for "UploadFile" type 
 */
#define ES_ejs_web_UploadFile_clientFilename                           0
#define ES_ejs_web_UploadFile_contentType                              1
#define ES_ejs_web_UploadFile_filename                                 2
#define ES_ejs_web_UploadFile_name                                     3
#define ES_ejs_web_UploadFile_size                                     4
#define ES_ejs_web_UploadFile_NUM_INSTANCE_PROP                        5
#define ES_ejs_web_UploadFile_NUM_INHERITED_PROP                       0


/*
    Class property slots for the "View" type 
 */
#define ES_ejs_web_View__initializer___View_                           0
#define ES_ejs_web_View_htmlOptions                                    1
#define ES_ejs_web_View_NUM_CLASS_PROP                                 2

/*
   Prototype (instance) slots for "View" type 
 */
#define ES_ejs_web_View_ejs_web_controller                             0
#define ES_ejs_web_View_ejs_web_request                                1
#define ES_ejs_web_View_currentRecord                                  2
#define ES_ejs_web_View_config                                         3
#define ES_ejs_web_View_ejs_web_log                                    4
#define ES_ejs_web_View_nextId                                         5
#define ES_ejs_web_View_ejs_web_getNextId                              6
#define ES_ejs_web_View_makeUri                                        7
#define ES_ejs_web_View_render                                         8
#define ES_ejs_web_View_setHeader                                      9
#define ES_ejs_web_View_setHeaders                                     10
#define ES_ejs_web_View_setStatus                                      11
#define ES_ejs_web_View_write                                          12
#define ES_ejs_web_View_ejs_web_aform                                  13
#define ES_ejs_web_View_ejs_web_alink                                  14
#define ES_ejs_web_View_ejs_web_button                                 15
#define ES_ejs_web_View_ejs_web_buttonLink                             16
#define ES_ejs_web_View_ejs_web_chart                                  17
#define ES_ejs_web_View_ejs_web_checkbox                               18
#define ES_ejs_web_View_ejs_web_endform                                19
#define ES_ejs_web_View_ejs_web_form                                   20
#define ES_ejs_web_View_ejs_web_image                                  21
#define ES_ejs_web_View_ejs_web_imageLink                              22
#define ES_ejs_web_View_ejs_web_input                                  23
#define ES_ejs_web_View_ejs_web_label                                  24
#define ES_ejs_web_View_ejs_web_link                                   25
#define ES_ejs_web_View_ejs_web_extlink                                26
#define ES_ejs_web_View_ejs_web_list                                   27
#define ES_ejs_web_View_ejs_web_mail                                   28
#define ES_ejs_web_View_ejs_web_progress                               29
#define ES_ejs_web_View_ejs_web_radio                                  30
#define ES_ejs_web_View_ejs_web_script                                 31
#define ES_ejs_web_View_ejs_web_status                                 32
#define ES_ejs_web_View_ejs_web_stylesheet                             33
#define ES_ejs_web_View_ejs_web_table                                  34
#define ES_ejs_web_View_ejs_web_tabs                                   35
#define ES_ejs_web_View_ejs_web_text                                   36
#define ES_ejs_web_View_ejs_web_textarea                               37
#define ES_ejs_web_View_ejs_web_tree                                   38
#define ES_ejs_web_View_ejs_web_flash                                  39
#define ES_ejs_web_View_emitFormErrors                                 40
#define ES_ejs_web_View_getConnector                                   41
#define ES_ejs_web_View_setOptions                                     42
#define ES_ejs_web_View_ejs_web_getValue                               43
#define ES_ejs_web_View_ejs_web_date                                   44
#define ES_ejs_web_View_ejs_web_currency                               45
#define ES_ejs_web_View_ejs_web_number                                 46
#define ES_ejs_web_View_ejs_web_getOptions                             47
#define ES_ejs_web_View_pivot                                          48
#define ES_ejs_web_View_filter                                         49
#define ES_ejs_web_View_ejs_web_makeUrl                                50
#define ES_ejs_web_View_ejs_web_appUrl                                 51
#define ES_ejs_web_View_ejs_web_redirect                               52
#define ES_ejs_web_View_NUM_INSTANCE_PROP                              53
#define ES_ejs_web_View_NUM_INHERITED_PROP                             0


/*
    Class property slots for the "Web" type 
 */
#define ES_ejs_web_Web__initializer___Web_                             0
#define ES_ejs_web_Web_config                                          1
#define ES_ejs_web_Web_defaultConfig                                   2
#define ES_ejs_web_Web_init                                            3
#define ES_ejs_web_Web_serve                                           4
#define ES_ejs_web_Web_worker                                          5
#define ES_ejs_web_Web_workerHelper                                    6
#define ES_ejs_web_Web_process                                         7
#define ES_ejs_web_Web_start                                           8
#define ES_ejs_web_Web_run                                             9
#define ES_ejs_web_Web_NUM_CLASS_PROP                                  10

/*
   Prototype (instance) slots for "Web" type 
 */
#define ES_ejs_web_Web_NUM_INSTANCE_PROP                               0
#define ES_ejs_web_Web_NUM_INHERITED_PROP                              0

/*
    Local slots for methods in type "Web" 
 */
#define ES_ejs_web_Web_serve_request                                   0
#define ES_ejs_web_Web_serve_router                                    1
#define ES_ejs_web_Web_worker_app                                      0
#define ES_ejs_web_Web_worker_request                                  1
#define ES_ejs_web_Web_workerHelper_app                                0
#define ES_ejs_web_Web_workerHelper_request                            1
#define ES_ejs_web_Web_process_app                                     0
#define ES_ejs_web_Web_process_request                                 1
#define ES_ejs_web_Web_start_address                                   0
#define ES_ejs_web_Web_start_documentRoot                              1
#define ES_ejs_web_Web_start_serverRoot                                2
#define ES_ejs_web_Web_start_routes                                    3
#define ES_ejs_web_Web_run_address                                     0
#define ES_ejs_web_Web_run_documentRoot                                1
#define ES_ejs_web_Web_run_serverRoot                                  2

#define _ES_CHECKSUM_ejs_web   619819

#endif
