/*
   ejs.db.mapper.slots.h -- Native property slot definitions for the "ejs.db.mapper" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsDbMapperSlots
#define _h_SLOTS_EjsDbMapperSlots 1


/*
   Slots for the "ejs.db.mapper" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */

/*
    Local slots for global methods 
 */
#define ES_ejs_db_mapper_plural_name                                   0
#define ES_ejs_db_mapper_singular_name                                 0
#define ES_ejs_db_mapper_mapType_value                                 0


/*
    Class property slots for the "Record" type 
 */
#define ES_Record__initializer___Record_                               0
#define ES_Record__assocName                                           1
#define ES_Record__belongsTo                                           2
#define ES_Record__className                                           3
#define ES_Record__columns                                             4
#define ES_Record__hasOne                                              5
#define ES_Record__hasMany                                             6
#define ES_Record__db                                                  7
#define ES_Record__foreignId                                           8
#define ES_Record__keyName                                             9
#define ES_Record__model                                               10
#define ES_Record__tableName                                           11
#define ES_Record__trace                                               12
#define ES_Record__validations                                         13
#define ES_Record__beforeFilters                                       14
#define ES_Record__afterFilters                                        15
#define ES_Record__wrapFilters                                         16
#define ES_Record_ErrorMessages                                        17
#define ES_Record_afterFilter                                          18
#define ES_Record_beforeFilter                                         19
#define ES_Record_belongsTo                                            20
#define ES_Record_cachedRead                                           21
#define ES_Record_checkFormat                                          22
#define ES_Record_checkNumber                                          23
#define ES_Record_checkPresent                                         24
#define ES_Record_checkUnique                                          25
#define ES_Record_createAssociations                                   26
#define ES_Record_createRecord                                         27
#define ES_Record_find                                                 28
#define ES_Record_findAll                                              29
#define ES_Record_findOneWhere                                         30
#define ES_Record_findWhere                                            31
#define ES_Record_getColumnNames                                       32
#define ES_Record_getColumnTitles                                      33
#define ES_Record_getColumnType                                        34
#define ES_Record_getDb                                                35
#define ES_Record_getKeyName                                           36
#define ES_Record_getNumRows                                           37
#define ES_Record_getSchema                                            38
#define ES_Record_getTableName                                         39
#define ES_Record_hasAndBelongsToMany                                  40
#define ES_Record_hasMany                                              41
#define ES_Record_hasOne                                               42
#define ES_Record_innerFind                                            43
#define ES_Record_makeLazyReader                                       44
#define ES_Record_mapSqlTypeToEjs                                      45
#define ES_Record_prepareValue                                         46
#define ES_Record_readRecords                                          47
#define ES_Record_remove                                               48
#define ES_Record_setDb                                                49
#define ES_Record_setKeyName                                           50
#define ES_Record_setTableName                                         51
#define ES_Record_sql                                                  52
#define ES_Record_trace                                                53
#define ES_Record_validateFormat                                       54
#define ES_Record_validateNumber                                       55
#define ES_Record_validatePresence                                     56
#define ES_Record_validateUnique                                       57
#define ES_Record_wrapFilter                                           58
#define ES_Record_columnNames                                          59
#define ES_Record_columnTitles                                         60
#define ES_Record_db                                                   61
#define ES_Record_keyName                                              62
#define ES_Record_numRows                                              63
#define ES_Record_tableName                                            64

#define ES_Record_NUM_CLASS_PROP                                       65

/*
   Prototype (instance) slots for "Record" type 
 */
#define ES_Record_Object_constructor                                   0
#define ES_Record_Object_clone                                         1
#define ES_Record_Object_iterator_get                                  2
#define ES_Record_Object_iterator_getValues                            3
#define ES_Record_Object_hasOwnProperty                                4
#define ES_Record_Object_isPrototypeOf                                 5
#define ES_Record_Object_propertyIsEnumerable                          6
#define ES_Record_Object_toJSON                                        7
#define ES_Record_Object_toLocaleString                                8
#define ES_Record_Object_toString                                      9
#define ES_Record_Object_valueOf                                       10
#define ES_Record_Record                                               11
#define ES_Record__keyValue                                            12
#define ES_Record__errors                                              13
#define ES_Record__cacheAssoc                                          14
#define ES_Record_initialize                                           15
#define ES_Record_coerceToEjsTypes                                     16
#define ES_Record_error                                                17
#define ES_Record_getErrors                                            18
#define ES_Record_hasError                                             19
#define ES_Record_runFilters                                           20
#define ES_Record_save                                                 21
#define ES_Record_saveUpdate                                           22
#define ES_Record_validateRecord                                       23
#define ES_Record_constructorOLD                                       24
#define ES_Record_NUM_INSTANCE_PROP                                    25

/*
    Local slots for methods in type "Record" 
 */
#define ES_Record_afterFilter_fn                                       0
#define ES_Record_afterFilter_options                                  1
#define ES_Record_beforeFilter_fn                                      0
#define ES_Record_beforeFilter_options                                 1
#define ES_Record_belongsTo_owner                                      0
#define ES_Record_belongsTo_options                                    1
#define ES_Record_cachedRead_rec                                       0
#define ES_Record_cachedRead_field                                     1
#define ES_Record_cachedRead_model                                     2
#define ES_Record_cachedRead_key                                       3
#define ES_Record_cachedRead_options                                   4
#define ES_Record_checkFormat_thisObj                                  0
#define ES_Record_checkFormat_field                                    1
#define ES_Record_checkFormat_value                                    2
#define ES_Record_checkFormat_options                                  3
#define ES_Record_checkNumber_thisObj                                  0
#define ES_Record_checkNumber_field                                    1
#define ES_Record_checkNumber_value                                    2
#define ES_Record_checkNumber_options                                  3
#define ES_Record_checkPresent_thisObj                                 0
#define ES_Record_checkPresent_field                                   1
#define ES_Record_checkPresent_value                                   2
#define ES_Record_checkPresent_options                                 3
#define ES_Record_checkUnique_thisObj                                  0
#define ES_Record_checkUnique_field                                    1
#define ES_Record_checkUnique_value                                    2
#define ES_Record_checkUnique_options                                  3
#define ES_Record_createAssociations_rec                               0
#define ES_Record_createAssociations_set                               1
#define ES_Record_createAssociations_preload                           2
#define ES_Record_createAssociations_options                           3
#define ES_Record_createRecord_data                                    0
#define ES_Record_createRecord_options                                 1
#define ES_Record_find_key                                             0
#define ES_Record_find_options                                         1
#define ES_Record_findAll_options                                      0
#define ES_Record_findOneWhere_where                                   0
#define ES_Record_findWhere_where                                      0
#define ES_Record_findWhere_count                                      1
#define ES_Record_getColumnType_field                                  0
#define ES_Record_hasAndBelongsToMany_model                            0
#define ES_Record_hasAndBelongsToMany_options                          1
#define ES_Record_hasMany_model                                        0
#define ES_Record_hasMany_options                                      1
#define ES_Record_hasOne_model                                         0
#define ES_Record_hasOne_options                                       1
#define ES_Record_innerFind_key                                        0
#define ES_Record_innerFind_limit                                      1
#define ES_Record_innerFind_options                                    2
#define ES_Record_makeLazyReader_rec                                   0
#define ES_Record_makeLazyReader_field                                 1
#define ES_Record_makeLazyReader_model                                 2
#define ES_Record_makeLazyReader_key                                   3
#define ES_Record_makeLazyReader_options                               4
#define ES_Record_mapSqlTypeToEjs_sqlType                              0
#define ES_Record_prepareValue_field                                   0
#define ES_Record_prepareValue_value                                   1
#define ES_Record_readRecords_key                                      0
#define ES_Record_readRecords_options                                  1
#define ES_Record_remove_ids                                           0
#define ES_Record_setDb_database                                       0
#define ES_Record_setKeyName_name                                      0
#define ES_Record_setTableName_name                                    0
#define ES_Record_sql_cmd                                              0
#define ES_Record_sql_count                                            1
#define ES_Record_trace_on                                             0
#define ES_Record_validateFormat_fields                                0
#define ES_Record_validateFormat_options                               1
#define ES_Record_validateNumber_fields                                0
#define ES_Record_validateNumber_options                               1
#define ES_Record_validatePresence_fields                              0
#define ES_Record_validatePresence_options                             1
#define ES_Record_validateUnique_fields                                0
#define ES_Record_validateUnique_option                                1
#define ES_Record_wrapFilter_fn                                        0
#define ES_Record_wrapFilter_options                                   1

#define ES_ejs_db_mapper_Column_NUM_CLASS_PROP                         0

/*
   Prototype (instance) slots for "Column" type 
 */
#define ES_ejs_db_mapper_Column_Object_constructor                     0
#define ES_ejs_db_mapper_Column_Object_clone                           1
#define ES_ejs_db_mapper_Column_Object_iterator_get                    2
#define ES_ejs_db_mapper_Column_Object_iterator_getValues              3
#define ES_ejs_db_mapper_Column_Object_hasOwnProperty                  4
#define ES_ejs_db_mapper_Column_Object_isPrototypeOf                   5
#define ES_ejs_db_mapper_Column_Object_propertyIsEnumerable            6
#define ES_ejs_db_mapper_Column_Object_toJSON                          7
#define ES_ejs_db_mapper_Column_Object_toLocaleString                  8
#define ES_ejs_db_mapper_Column_Object_toString                        9
#define ES_ejs_db_mapper_Column_Object_valueOf                         10
#define ES_ejs_db_mapper_Column_Column                                 11
#define ES_ejs_db_mapper_Column_ejsType                                12
#define ES_ejs_db_mapper_Column_sqlType                                13
#define ES_ejs_db_mapper_Column_NUM_INSTANCE_PROP                      14

#define _ES_CHECKSUM_ejs_db_mapper   186943

#endif
