/*
   ejs.slots.h -- Native property slot definitions for the "ejs" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 1.1.0.
 */

#ifndef _h_SLOTS_EjsSlots
#define _h_SLOTS_EjsSlots 1


/*
   Slots for the "ejs" module 
 */


/*
    Global property slots
 */
#define ES_stderr                                                      0
#define ES_stdin                                                       1
#define ES_stdout                                                      2
#define ES_App                                                         3
#define ES_appInit                                                     4
#define ES_Array                                                       5
#define ES_BinaryStream                                                6
#define ES_Block                                                       7
#define ES_Boolean                                                     8
#define ES_ByteArray                                                   9
#define ES_Cmd                                                         10
#define ES_CmdArgs                                                     11
#define ES_gc                                                          12
#define ES_readFile                                                    13
#define ES_Config                                                      14
#define ES_Date                                                        15
#define ES_Emitter                                                     16
#define ES_Endpoint                                                    17
#define ES_ArgError                                                    18
#define ES_ArithmeticError                                             19
#define ES_AssertError                                                 20
#define ES_InstructionError                                            21
#define ES_Error                                                       22
#define ES_IOError                                                     23
#define ES_InternalError                                               24
#define ES_MemoryError                                                 25
#define ES_OutOfBoundsError                                            26
#define ES_ReferenceError                                              27
#define ES_ResourceError                                               28
#define ES_SecurityError                                               29
#define ES_StateError                                                  30
#define ES_SyntaxError                                                 31
#define ES_TypeError                                                   32
#define ES_URIError                                                    33
#define ES_Event                                                       34
#define ES_ErrorEvent                                                  35
#define ES_File                                                        36
#define ES_FileSystem                                                  37
#define ES_Frame                                                       38
#define ES_Function                                                    39
#define ES_makeGetter                                                  40
#define ES_clearBoundThis                                              41
#define ES_GC                                                          42
#define ES_EJSCRIPT                                                    43
#define ES_ECMA                                                        44
#define ES_ejs                                                         45
#define ES_public                                                      46
#define ES_internal                                                    47
#define ES_iterator                                                    48
#define ES_CONFIG                                                      49
#define ES_TODO                                                        50
#define ES_FUTURE                                                      51
#define ES_ASC                                                         52
#define ES_DOC_ONLY                                                    53
#define ES_DEPRECATED                                                  54
#define ES_boolean                                                     55
#define ES_double                                                      56
#define ES_num                                                         57
#define ES_string                                                      58
#define ES_false                                                       59
#define ES_global                                                      60
#define ES_null                                                        61
#define ES_Infinity                                                    62
#define ES_NegativeInfinity                                            63
#define ES_NaN                                                         64
#define ES_true                                                        65
#define ES_undefined                                                   66
#define ES_void                                                        67
#define ES_assert                                                      68
#define ES_breakpoint                                                  69
#define ES_cloneBase                                                   70
#define ES_decodeURI                                                   71
#define ES_dump                                                        72
#define ES_dumpAll                                                     73
#define ES_dumpDef                                                     74
#define ES_encodeURI                                                   75
#define ES_escape                                                      76
#define ES_md5                                                         77
#define ES_blend                                                       78
#define ES_eval                                                        79
#define ES_formatStack                                                 80
#define ES_hashcode                                                    81
#define ES_isNaN                                                       82
#define ES_isFinite                                                    83
#define ES_load                                                        84
#define ES_print                                                       85
#define ES_parse                                                       86
#define ES_parseFloat                                                  87
#define ES_parseInt                                                    88
#define ES_printHash                                                   89
#define ES_instanceOf                                                  90
#define ES_error                                                       91
#define ES_input                                                       92
#define ES_output                                                      93
#define ES_Http                                                        94
#define ES_Iterable                                                    95
#define ES_Iterator                                                    96
#define ES_StopIteration                                               97
#define ES_JSON                                                        98
#define ES_deserialize                                                 99
#define ES_serialize                                                   100
#define ES_Locale                                                      101
#define ES_Logger                                                      102
#define ES_Math                                                        103
#define ES_Memory                                                      104
#define ES_Namespace                                                   105
#define ES_Null                                                        106
#define ES_Number                                                      107
#define ES_Object                                                      108
#define ES_Path                                                        109
#define ES_Promise                                                     110
#define ES_Reflect                                                     111
#define ES_typeOf                                                      112
#define ES_RegExp                                                      113
#define ES_Socket                                                      114
#define ES_Stream                                                      115
#define ES_String                                                      116
#define ES_System                                                      117
#define ES_TextStream                                                  118
#define ES_Timer                                                       119
#define ES_setInterval                                                 120
#define ES_setTimeout                                                  121
#define ES_TimerEvent                                                  122
#define ES_Type                                                        123
#define ES_Uri                                                         124
#define ES_decodeUri                                                   125
#define ES_decodeUriComponent                                          126
#define ES_Void                                                        127
#define ES_Worker                                                      128
#define ES_ejs_worker_self                                             129
#define ES_ejs_worker_exit                                             130
#define ES_ejs_worker_postMessage                                      131
#define ES_ejs_worker_onerror                                          132
#define ES_ejs_worker_onmessage                                        133
#define ES_XML                                                         134
#define ES_XMLHttp                                                     135
#define ES_XMLList                                                     136

#define ES_global_NUM_CLASS_PROP                                       137

/*
   Prototype (instance) slots for "global" type 
 */
#define ES_global_NUM_INSTANCE_PROP                                    0

/*
    Local slots for global methods 
 */
#define ES_readFile_path                                               0
#define ES_readFile_encoding                                           1
#define ES_makeGetter_fn                                               0
#define ES_clearBoundThis_fn                                           0
#define ES_assert_condition                                            0
#define ES_cloneBase_klass                                             0
#define ES_decodeURI_str                                               0
#define ES_dump_args                                                   0
#define ES_dumpAll_args                                                0
#define ES_dumpDef_args                                                0
#define ES_encodeURI_str                                               0
#define ES_escape_str                                                  0
#define ES_md5_str                                                     0
#define ES_blend_dest                                                  0
#define ES_blend_src                                                   1
#define ES_blend_overwrite                                             2
#define ES_eval_script                                                 0
#define ES_eval_cache                                                  1
#define ES_hashcode_o                                                  0
#define ES_isNaN_arg                                                   0
#define ES_isFinite_arg                                                0
#define ES_load_file                                                   0
#define ES_load_cache                                                  1
#define ES_print_args                                                  0
#define ES_parse_str                                                   0
#define ES_parse_preferredType                                         1
#define ES_parseFloat_str                                              0
#define ES_parseInt_str                                                0
#define ES_parseInt_radix                                              1
#define ES_printHash_name                                              0
#define ES_printHash_o                                                 1
#define ES_instanceOf_obj                                              0
#define ES_instanceOf_target                                           1
#define ES_error_args                                                  0
#define ES_output_args                                                 0
#define ES_deserialize_str                                             0
#define ES_serialize_obj                                               0
#define ES_serialize_options                                           1
#define ES_typeOf_o                                                    0
#define ES_setInterval_callback                                        0
#define ES_setInterval_delay                                           1
#define ES_setTimeout_callback                                         0
#define ES_setTimeout_delay                                            1
#define ES_decodeUri_str                                               0
#define ES_decodeUriComponent_str                                      0
#define ES_ejs_worker_postMessage_data                                 0
#define ES_ejs_worker_postMessage_ports                                1


/*
    Class property slots for the "App" type 
 */
#define ES_App__initializer___App_                                     0
#define ES_App_config                                                  1
#define ES_App_SearchSeparator                                         2
#define ES_App__errorStream                                            3
#define ES_App__inputStream                                            4
#define ES_App__outputStream                                           5
#define ES_App_defaultConfig                                           6
#define ES_App_args                                                    7
#define ES_App_dir                                                     8
#define ES_App_chdir                                                   9
#define ES_App_exeDir                                                  10
#define ES_App_exePath                                                 11
#define ES_App_errorStream                                             12
#define ES_App_exit                                                    13
#define ES_App_getenv                                                  14
#define ES_App_inputStream                                             15
#define ES_App_log                                                     16
#define ES_App_name                                                    17
#define ES_App_noexit                                                  18
#define ES_App_outputStream                                            19
#define ES_App_putenv                                                  20
#define ES_App_search                                                  21
#define ES_App_createSearch                                            22
#define ES_App_eventLoop                                               23
#define ES_App_sleep                                                   24
#define ES_App_title                                                   25
#define ES_App_version                                                 26
#define ES_App_searchPath                                              27
#define ES_App_serviceEvents                                           28

#define ES_App_NUM_CLASS_PROP                                          29

/*
   Prototype (instance) slots for "App" type 
 */
#define ES_App_NUM_INSTANCE_PROP                                       12

/*
    Local slots for methods in type "App" 
 */
#define ES_App_chdir_value                                             0
#define ES_App_exit_status                                             0
#define ES_App_getenv_name                                             0
#define ES_App_noexit_exit                                             0
#define ES_App_putenv_name                                             0
#define ES_App_putenv_value                                            1
#define ES_App_createSearch_searchPath                                 0
#define ES_App_eventLoop_timeout                                       0
#define ES_App_eventLoop_oneEvent                                      1
#define ES_App_sleep_delay                                             0
#define ES_App_serviceEvents_count                                     0
#define ES_App_serviceEvents_timeout                                   1

#define ES_Array_NUM_CLASS_PROP                                        0

/*
   Prototype (instance) slots for "Array" type 
 */
#define ES_Array_Array                                                 12
#define ES_Array_append                                                13
#define ES_Array_clear                                                 14
#define ES_Array_compact                                               15
#define ES_Array_concat                                                16
#define ES_Array_contains                                              17
#define ES_Array_every                                                 18
#define ES_Array_filter                                                19
#define ES_Array_find                                                  20
#define ES_Array_findAll                                               21
#define ES_Array_forEach                                               22
#define ES_Array_indexOf                                               23
#define ES_Array_insert                                                24
#define ES_Array_join                                                  25
#define ES_Array_lastIndexOf                                           26
#define ES_Array_length                                                27
#define ES_Array_map                                                   28
#define ES_Array_pop                                                   29
#define ES_Array_push                                                  30
#define ES_Array_reject                                                31
#define ES_Array_remove                                                32
#define ES_Array_reverse                                               33
#define ES_Array_shift                                                 34
#define ES_Array_slice                                                 35
#define ES_Array_some                                                  36
#define ES_Array_sort                                                  37
#define ES_Array_splice                                                38
#define ES_Array_transform                                             39
#define ES_Array_unique                                                40
#define ES_Array_unshift                                               41
#define ES_Array_NUM_INSTANCE_PROP                                     42


/*
    Class property slots for the "BinaryStream" type 
 */
#define ES_BinaryStream__initializer___BinaryStream_                   0
#define ES_BinaryStream_BigEndian                                      1
#define ES_BinaryStream_LittleEndian                                   2

#define ES_BinaryStream_NUM_CLASS_PROP                                 3

/*
   Prototype (instance) slots for "BinaryStream" type 
 */
#define ES_BinaryStream_BinaryStream                                   12
#define ES_BinaryStream_inbuf                                          13
#define ES_BinaryStream_outbuf                                         14
#define ES_BinaryStream_nextStream                                     15
#define ES_BinaryStream_addListener                                    16
#define ES_BinaryStream_async                                          17
#define ES_BinaryStream_available                                      18
#define ES_BinaryStream_close                                          19
#define ES_BinaryStream_encoding                                       20
#define ES_BinaryStream_endian                                         21
#define ES_BinaryStream_flush                                          22
#define ES_BinaryStream_read                                           23
#define ES_BinaryStream_readBoolean                                    24
#define ES_BinaryStream_readByte                                       25
#define ES_BinaryStream_readDate                                       26
#define ES_BinaryStream_readDouble                                     27
#define ES_BinaryStream_readInteger                                    28
#define ES_BinaryStream_readLong                                       29
#define ES_BinaryStream_readString                                     30
#define ES_BinaryStream_readXML                                        31
#define ES_BinaryStream_removeListener                                 32
#define ES_BinaryStream_room                                           33
#define ES_BinaryStream_write                                          34
#define ES_BinaryStream_writeByte                                      35
#define ES_BinaryStream_writeShort                                     36
#define ES_BinaryStream_writeDouble                                    37
#define ES_BinaryStream_writeInteger                                   38
#define ES_BinaryStream_writeLong                                      39
#define ES_BinaryStream_NUM_INSTANCE_PROP                              40

#define ES_Block_NUM_CLASS_PROP                                        0

/*
   Prototype (instance) slots for "Block" type 
 */
#define ES_Block_NUM_INSTANCE_PROP                                     12

#define ES_Boolean_NUM_CLASS_PROP                                      0

/*
   Prototype (instance) slots for "Boolean" type 
 */
#define ES_Boolean_Boolean                                             12
#define ES_Boolean_NUM_INSTANCE_PROP                                   13


/*
    Class property slots for the "ByteArray" type 
 */
#define ES_ByteArray__initializer___ByteArray_                         0
#define ES_ByteArray_LittleEndian                                      1
#define ES_ByteArray_BigEndian                                         2

#define ES_ByteArray_NUM_CLASS_PROP                                    3

/*
   Prototype (instance) slots for "ByteArray" type 
 */
#define ES_ByteArray_ByteArray                                         12
#define ES_ByteArray_addListener                                       13
#define ES_ByteArray_available                                         14
#define ES_ByteArray_async                                             15
#define ES_ByteArray_close                                             16
#define ES_ByteArray_compact                                           17
#define ES_ByteArray_copyIn                                            18
#define ES_ByteArray_copyOut                                           19
#define ES_ByteArray_encoding                                          20
#define ES_ByteArray_endian                                            21
#define ES_ByteArray_flush                                             22
#define ES_ByteArray_growable                                          23
#define ES_ByteArray_length                                            24
#define ES_ByteArray_MD5                                               25
#define ES_ByteArray_read                                              26
#define ES_ByteArray_readBoolean                                       27
#define ES_ByteArray_readByte                                          28
#define ES_ByteArray_readDate                                          29
#define ES_ByteArray_readDouble                                        30
#define ES_ByteArray_readInteger                                       31
#define ES_ByteArray_readLong                                          32
#define ES_ByteArray_readPosition                                      33
#define ES_ByteArray_readShort                                         34
#define ES_ByteArray_readString                                        35
#define ES_ByteArray_readXML                                           36
#define ES_ByteArray_removeListener                                    37
#define ES_ByteArray_reset                                             38
#define ES_ByteArray_room                                              39
#define ES_ByteArray_write                                             40
#define ES_ByteArray_writeByte                                         41
#define ES_ByteArray_writeShort                                        42
#define ES_ByteArray_writeDouble                                       43
#define ES_ByteArray_writeInteger                                      44
#define ES_ByteArray_writeLong                                         45
#define ES_ByteArray_writePosition                                     46
#define ES_ByteArray_input                                             47
#define ES_ByteArray_output                                            48
#define ES_ByteArray_NUM_INSTANCE_PROP                                 49


/*
    Class property slots for the "Cmd" type 
 */
#define ES_Cmd_sh                                                      0
#define ES_Cmd_run                                                     1
#define ES_Cmd_daemon                                                  2
#define ES_Cmd_runx                                                    3

#define ES_Cmd_NUM_CLASS_PROP                                          4

/*
   Prototype (instance) slots for "Cmd" type 
 */
#define ES_Cmd_NUM_INSTANCE_PROP                                       12

/*
    Local slots for methods in type "Cmd" 
 */
#define ES_Cmd_sh_cmdline                                              0
#define ES_Cmd_sh_data                                                 1
#define ES_Cmd_run_cmdline                                             0
#define ES_Cmd_run_data                                                1
#define ES_Cmd_daemon_cmdline                                          0
#define ES_Cmd_runx_cmdline                                            0

#define ES_CmdArgs_NUM_CLASS_PROP                                      0

/*
   Prototype (instance) slots for "CmdArgs" type 
 */
#define ES_CmdArgs_CmdArgs                                             12
#define ES_CmdArgs_args                                                13
#define ES_CmdArgs_options                                             14
#define ES_CmdArgs_ranges                                              15
#define ES_CmdArgs_aliases                                             16
#define ES_CmdArgs_parseTemplate                                       17
#define ES_CmdArgs_validate                                            18
#define ES_CmdArgs_NUM_INSTANCE_PROP                                   19


/*
    Class property slots for the "Config" type 
 */
#define ES_Config_Debug                                                0
#define ES_Config_CPU                                                  1
#define ES_Config_OS                                                   2
#define ES_Config_Product                                              3
#define ES_Config_Title                                                4
#define ES_Config_Version                                              5
#define ES_Config_LibDir                                               6
#define ES_Config_BinDir                                               7
#define ES_Config_ModDir                                               8

#define ES_Config_NUM_CLASS_PROP                                       9

/*
   Prototype (instance) slots for "Config" type 
 */
#define ES_Config_NUM_INSTANCE_PROP                                    12


/*
    Class property slots for the "Date" type 
 */
#define ES_Date_now                                                    0
#define ES_Date_parseDate                                              1
#define ES_Date_parseUTCDate                                           2
#define ES_Date_parse                                                  3
#define ES_Date_UTC                                                    4

#define ES_Date_NUM_CLASS_PROP                                         5

/*
   Prototype (instance) slots for "Date" type 
 */
#define ES_Date_Date                                                   12
#define ES_Date_day                                                    13
#define ES_Date_dayOfYear                                              14
#define ES_Date_date                                                   15
#define ES_Date_elapsed                                                16
#define ES_Date_format                                                 17
#define ES_Date_formatUTC                                              18
#define ES_Date_fullYear                                               19
#define ES_Date_getDate                                                20
#define ES_Date_getDay                                                 21
#define ES_Date_getFullYear                                            22
#define ES_Date_getHours                                               23
#define ES_Date_getMilliseconds                                        24
#define ES_Date_getMinutes                                             25
#define ES_Date_getMonth                                               26
#define ES_Date_getSeconds                                             27
#define ES_Date_getTime                                                28
#define ES_Date_getTimezoneOffset                                      29
#define ES_Date_getUTCDate                                             30
#define ES_Date_getUTCDay                                              31
#define ES_Date_getUTCFullYear                                         32
#define ES_Date_getUTCHours                                            33
#define ES_Date_getUTCMilliseconds                                     34
#define ES_Date_getUTCMinutes                                          35
#define ES_Date_getUTCMonth                                            36
#define ES_Date_getUTCSeconds                                          37
#define ES_Date_hours                                                  38
#define ES_Date_milliseconds                                           39
#define ES_Date_minutes                                                40
#define ES_Date_month                                                  41
#define ES_Date_nanoAge                                                42
#define ES_Date_nextDay                                                43
#define ES_Date_seconds                                                44
#define ES_Date_setDate                                                45
#define ES_Date_setFullYear                                            46
#define ES_Date_setHours                                               47
#define ES_Date_setMilliseconds                                        48
#define ES_Date_setMinutes                                             49
#define ES_Date_setMonth                                               50
#define ES_Date_setSeconds                                             51
#define ES_Date_setTime                                                52
#define ES_Date_setUTCDate                                             53
#define ES_Date_setUTCFullYear                                         54
#define ES_Date_setUTCHours                                            55
#define ES_Date_setUTCMilliseconds                                     56
#define ES_Date_setUTCMinutes                                          57
#define ES_Date_setUTCMonth                                            58
#define ES_Date_setUTCSeconds                                          59
#define ES_Date_time                                                   60
#define ES_Date_toDateString                                           61
#define ES_Date_toISOString                                            62
#define ES_Date_toLocaleDateString                                     63
#define ES_Date_toLocaleTimeString                                     64
#define ES_Date_toTimeString                                           65
#define ES_Date_toUTCString                                            66
#define ES_Date_year                                                   67
#define ES_Date_NUM_INSTANCE_PROP                                      68

/*
    Local slots for methods in type "Date" 
 */
#define ES_Date_parseDate_dateString                                   0
#define ES_Date_parseDate_defaultDate                                  1
#define ES_Date_parseUTCDate_dateString                                0
#define ES_Date_parseUTCDate_defaultDate                               1
#define ES_Date_parse_dateString                                       0
#define ES_Date_UTC_year                                               0
#define ES_Date_UTC_month                                              1
#define ES_Date_UTC_day                                                2
#define ES_Date_UTC_hours                                              3
#define ES_Date_UTC_minutes                                            4
#define ES_Date_UTC_seconds                                            5
#define ES_Date_UTC_milliseconds                                       6

#define ES_Emitter_NUM_CLASS_PROP                                      0

/*
   Prototype (instance) slots for "Emitter" type 
 */
#define ES_Emitter_Emitter                                             12
#define ES_Emitter_endpoints                                           13
#define ES_Emitter_addOneListener                                      14
#define ES_Emitter_addListener                                         15
#define ES_Emitter_clearListeners                                      16
#define ES_Emitter_hasListeners                                        17
#define ES_Emitter_listeners                                           18
#define ES_Emitter_emit                                                19
#define ES_Emitter_removeOneListener                                   20
#define ES_Emitter_removeListener                                      21
#define ES_Emitter_NUM_INSTANCE_PROP                                   22

#define ES_Endpoint_NUM_CLASS_PROP                                     0

/*
   Prototype (instance) slots for "Endpoint" type 
 */
#define ES_Endpoint_Endpoint                                           12
#define ES_Endpoint_callback                                           13
#define ES_Endpoint_name                                               14
#define ES_Endpoint_active                                             15
#define ES_Endpoint_again                                              16
#define ES_Endpoint_NUM_INSTANCE_PROP                                  17

#define ES_ArgError_NUM_CLASS_PROP                                     0

/*
   Prototype (instance) slots for "ArgError" type 
 */
#define ES_ArgError_ArgError                                           16
#define ES_ArgError_NUM_INSTANCE_PROP                                  17

#define ES_ArithmeticError_NUM_CLASS_PROP                              0

/*
   Prototype (instance) slots for "ArithmeticError" type 
 */
#define ES_ArithmeticError_ArithmeticError                             16
#define ES_ArithmeticError_NUM_INSTANCE_PROP                           17

#define ES_AssertError_NUM_CLASS_PROP                                  0

/*
   Prototype (instance) slots for "AssertError" type 
 */
#define ES_AssertError_AssertError                                     16
#define ES_AssertError_NUM_INSTANCE_PROP                               17

#define ES_InstructionError_NUM_CLASS_PROP                             0

/*
   Prototype (instance) slots for "InstructionError" type 
 */
#define ES_InstructionError_InstructionError                           16
#define ES_InstructionError_NUM_INSTANCE_PROP                          17

#define ES_Error_NUM_CLASS_PROP                                        0

/*
   Prototype (instance) slots for "Error" type 
 */
#define ES_Error_Error                                                 12
#define ES_Error_message                                               13
#define ES_Error_code                                                  14
#define ES_Error_stack                                                 15
#define ES_Error_NUM_INSTANCE_PROP                                     16

#define ES_IOError_NUM_CLASS_PROP                                      0

/*
   Prototype (instance) slots for "IOError" type 
 */
#define ES_IOError_IOError                                             16
#define ES_IOError_NUM_INSTANCE_PROP                                   17

#define ES_InternalError_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "InternalError" type 
 */
#define ES_InternalError_InternalError                                 16
#define ES_InternalError_NUM_INSTANCE_PROP                             17

#define ES_MemoryError_NUM_CLASS_PROP                                  0

/*
   Prototype (instance) slots for "MemoryError" type 
 */
#define ES_MemoryError_MemoryError                                     16
#define ES_MemoryError_NUM_INSTANCE_PROP                               17

#define ES_OutOfBoundsError_NUM_CLASS_PROP                             0

/*
   Prototype (instance) slots for "OutOfBoundsError" type 
 */
#define ES_OutOfBoundsError_OutOfBoundsError                           16
#define ES_OutOfBoundsError_NUM_INSTANCE_PROP                          17

#define ES_ReferenceError_NUM_CLASS_PROP                               0

/*
   Prototype (instance) slots for "ReferenceError" type 
 */
#define ES_ReferenceError_ReferenceError                               16
#define ES_ReferenceError_NUM_INSTANCE_PROP                            17

#define ES_ResourceError_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "ResourceError" type 
 */
#define ES_ResourceError_ResourceError                                 16
#define ES_ResourceError_NUM_INSTANCE_PROP                             17

#define ES_SecurityError_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "SecurityError" type 
 */
#define ES_SecurityError_SecurityError                                 16
#define ES_SecurityError_NUM_INSTANCE_PROP                             17

#define ES_StateError_NUM_CLASS_PROP                                   0

/*
   Prototype (instance) slots for "StateError" type 
 */
#define ES_StateError_StateError                                       16
#define ES_StateError_NUM_INSTANCE_PROP                                17

#define ES_SyntaxError_NUM_CLASS_PROP                                  0

/*
   Prototype (instance) slots for "SyntaxError" type 
 */
#define ES_SyntaxError_SyntaxError                                     16
#define ES_SyntaxError_NUM_INSTANCE_PROP                               17

#define ES_TypeError_NUM_CLASS_PROP                                    0

/*
   Prototype (instance) slots for "TypeError" type 
 */
#define ES_TypeError_TypeError                                         16
#define ES_TypeError_NUM_INSTANCE_PROP                                 17

#define ES_URIError_NUM_CLASS_PROP                                     0

/*
   Prototype (instance) slots for "URIError" type 
 */
#define ES_URIError_URIError                                           16
#define ES_URIError_NUM_INSTANCE_PROP                                  17

#define ES_Event_NUM_CLASS_PROP                                        0

/*
   Prototype (instance) slots for "Event" type 
 */
#define ES_Event_Event                                                 12
#define ES_Event_data                                                  13
#define ES_Event_timestamp                                             14
#define ES_Event_NUM_INSTANCE_PROP                                     15

#define ES_ErrorEvent_NUM_CLASS_PROP                                   0

/*
   Prototype (instance) slots for "ErrorEvent" type 
 */
#define ES_ErrorEvent_ErrorEvent                                       15
#define ES_ErrorEvent_message                                          16
#define ES_ErrorEvent_filename                                         17
#define ES_ErrorEvent_lineno                                           18
#define ES_ErrorEvent_stack                                            19
#define ES_ErrorEvent_NUM_INSTANCE_PROP                                20

#define ES_File_NUM_CLASS_PROP                                         0

/*
   Prototype (instance) slots for "File" type 
 */
#define ES_File_File                                                   12
#define ES_File_addListener                                            13
#define ES_File_async                                                  14
#define ES_File_canRead                                                15
#define ES_File_canWrite                                               16
#define ES_File_close                                                  17
#define ES_File_encoding                                               18
#define ES_File_flush                                                  19
#define ES_File_isOpen                                                 20
#define ES_File_open                                                   21
#define ES_File_options                                                22
#define ES_File_path                                                   23
#define ES_File_position                                               24
#define ES_File_read                                                   25
#define ES_File_readBytes                                              26
#define ES_File_readString                                             27
#define ES_File_remove                                                 28
#define ES_File_removeListener                                         29
#define ES_File_size                                                   30
#define ES_File_truncate                                               31
#define ES_File_write                                                  32
#define ES_File_NUM_INSTANCE_PROP                                      33

#define ES_FileSystem_NUM_CLASS_PROP                                   0

/*
   Prototype (instance) slots for "FileSystem" type 
 */
#define ES_FileSystem_FileSystem                                       12
#define ES_FileSystem_hasDrives                                        13
#define ES_FileSystem_newline                                          14
#define ES_FileSystem_root                                             15
#define ES_FileSystem_separators                                       16
#define ES_FileSystem_NUM_INSTANCE_PROP                                17

#define ES_Frame_NUM_CLASS_PROP                                        0

/*
   Prototype (instance) slots for "Frame" type 
 */
#define ES_Frame_NUM_INSTANCE_PROP                                     17

#define ES_Function_NUM_CLASS_PROP                                     0

/*
   Prototype (instance) slots for "Function" type 
 */
#define ES_Function_apply                                              12
#define ES_Function_call                                               13
#define ES_Function_boundThis                                          14
#define ES_Function_bind                                               15
#define ES_Function_setScope                                           16
#define ES_Function_NUM_INSTANCE_PROP                                  17


/*
    Class property slots for the "GC" type 
 */
#define ES_GC_enabled                                                  0
#define ES_GC_workQuota                                                1
#define ES_GC_run                                                      2

#define ES_GC_NUM_CLASS_PROP                                           3

/*
   Prototype (instance) slots for "GC" type 
 */
#define ES_GC_NUM_INSTANCE_PROP                                        12

/*
    Local slots for methods in type "GC" 
 */
#define ES_GC_run_deep                                                 0


/*
    Class property slots for the "Http" type 
 */
#define ES_Http__initializer___Http_                                   0
#define ES_Http_Continue                                               1
#define ES_Http_Ok                                                     2
#define ES_Http_Created                                                3
#define ES_Http_Accepted                                               4
#define ES_Http_NotAuthoritative                                       5
#define ES_Http_NoContent                                              6
#define ES_Http_Reset                                                  7
#define ES_Http_PartialContent                                         8
#define ES_Http_MultipleChoice                                         9
#define ES_Http_MovedPermanently                                       10
#define ES_Http_MovedTemporarily                                       11
#define ES_Http_SeeOther                                               12
#define ES_Http_NotModified                                            13
#define ES_Http_UseProxy                                               14
#define ES_Http_BadRequest                                             15
#define ES_Http_Unauthorized                                           16
#define ES_Http_PaymentRequired                                        17
#define ES_Http_Forbidden                                              18
#define ES_Http_NotFound                                               19
#define ES_Http_BadMethod                                              20
#define ES_Http_NotAcceptable                                          21
#define ES_Http_ProxyAuthRequired                                      22
#define ES_Http_RequestTimeout                                         23
#define ES_Http_Conflict                                               24
#define ES_Http_Gone                                                   25
#define ES_Http_LengthRequired                                         26
#define ES_Http_PrecondFailed                                          27
#define ES_Http_EntityTooLarge                                         28
#define ES_Http_UriTooLong                                             29
#define ES_Http_UnsupportedMedia                                       30
#define ES_Http_BadRange                                               31
#define ES_Http_ServerError                                            32
#define ES_Http_NotImplemented                                         33
#define ES_Http_BadGateway                                             34
#define ES_Http_ServiceUnavailable                                     35
#define ES_Http_GatewayTimeout                                         36
#define ES_Http_VersionNotSupported                                    37
#define ES_Http_mimeType                                               38

#define ES_Http_NUM_CLASS_PROP                                         39

/*
   Prototype (instance) slots for "Http" type 
 */
#define ES_Http_Http                                                   12
#define ES_Http__response                                              13
#define ES_Http_addListener                                            14
#define ES_Http_async                                                  15
#define ES_Http_chunkSize                                              16
#define ES_Http_close                                                  17
#define ES_Http_connect                                                18
#define ES_Http_certificate                                            19
#define ES_Http_contentLength                                          20
#define ES_Http_contentType                                            21
#define ES_Http_date                                                   22
#define ES_Http_del                                                    23
#define ES_Http_encoding                                               24
#define ES_Http_expires                                                25
#define ES_Http_finalize                                               26
#define ES_Http_flush                                                  27
#define ES_Http_followRedirects                                        28
#define ES_Http_form                                                   29
#define ES_Http_get                                                    30
#define ES_Http_getRequestHeaders                                      31
#define ES_Http_head                                                   32
#define ES_Http_header                                                 33
#define ES_Http_headers                                                34
#define ES_Http_isSecure                                               35
#define ES_Http_key                                                    36
#define ES_Http_lastModified                                           37
#define ES_Http_method                                                 38
#define ES_Http_options                                                39
#define ES_Http_post                                                   40
#define ES_Http_put                                                    41
#define ES_Http_read                                                   42
#define ES_Http_readString                                             43
#define ES_Http_readLines                                              44
#define ES_Http_readXml                                                45
#define ES_Http_removeListener                                         46
#define ES_Http_response                                               47
#define ES_Http_retries                                                48
#define ES_Http_setCredentials                                         49
#define ES_Http_setHeader                                              50
#define ES_Http_setHeaders                                             51
#define ES_Http_status                                                 52
#define ES_Http_statusMessage                                          53
#define ES_Http_success                                                54
#define ES_Http_timeout                                                55
#define ES_Http_trace                                                  56
#define ES_Http_upload                                                 57
#define ES_Http_uri                                                    58
#define ES_Http_wait                                                   59
#define ES_Http_write                                                  60
#define ES_Http_addHeader                                              61
#define ES_Http_bodyLength                                             62
#define ES_Http_code                                                   63
#define ES_Http_codeString                                             64
#define ES_Http_available                                              65
#define ES_Http_contentEncoding                                        66
#define ES_Http_setCallback                                            67
#define ES_Http_chunked                                                68
#define ES_Http_NUM_INSTANCE_PROP                                      69

/*
    Local slots for methods in type "Http" 
 */
#define ES_Http_mimeType_path                                          0

#define ES_Iterable_NUM_CLASS_PROP                                     0

/*
   Prototype (instance) slots for "Iterable" type 
 */
#define ES_Iterable_get                                                0
#define ES_Iterable_getValues                                          1
#define ES_Iterable_NUM_INSTANCE_PROP                                  2

#define ES_Iterator_NUM_CLASS_PROP                                     0

/*
   Prototype (instance) slots for "Iterator" type 
 */
#define ES_Iterator_next                                               12
#define ES_Iterator_NUM_INSTANCE_PROP                                  13

#define ES_StopIteration_NUM_CLASS_PROP                                0

/*
   Prototype (instance) slots for "StopIteration" type 
 */
#define ES_StopIteration_NUM_INSTANCE_PROP                             12


/*
    Class property slots for the "JSON" type 
 */
#define ES_JSON_parse                                                  0
#define ES_JSON_stringify                                              1

#define ES_JSON_NUM_CLASS_PROP                                         2

/*
   Prototype (instance) slots for "JSON" type 
 */
#define ES_JSON_NUM_INSTANCE_PROP                                      12

/*
    Local slots for methods in type "JSON" 
 */
#define ES_JSON_parse_data                                             0
#define ES_JSON_parse_filter                                           1
#define ES_JSON_stringify_obj                                          0
#define ES_JSON_stringify_replacer                                     1
#define ES_JSON_stringify_indent                                       2


/*
    Class property slots for the "Locale" type 
 */
#define ES_Locale__initializer___Locale_                               0
#define ES_Locale_textEncoding                                         1

#define ES_Locale_NUM_CLASS_PROP                                       2

/*
   Prototype (instance) slots for "Locale" type 
 */
#define ES_Locale_Locale                                               12
#define ES_Locale_NUM_INSTANCE_PROP                                    13


/*
    Class property slots for the "Logger" type 
 */
#define ES_Logger__initializer___Logger_                               0
#define ES_Logger_Off                                                  1
#define ES_Logger_Error                                                2
#define ES_Logger_Warn                                                 3
#define ES_Logger_Info                                                 4
#define ES_Logger_Config                                               5
#define ES_Logger_All                                                  6
#define ES_Logger_mprLevel                                             7
#define ES_Logger_mprStream                                            8

#define ES_Logger_NUM_CLASS_PROP                                       9

/*
   Prototype (instance) slots for "Logger" type 
 */
#define ES_Logger_Logger                                               12
#define ES_Logger__filter                                              13
#define ES_Logger__level                                               14
#define ES_Logger__pattern                                             15
#define ES_Logger__name                                                16
#define ES_Logger__outStream                                           17
#define ES_Logger__parent                                              18
#define ES_Logger_addListener                                          19
#define ES_Logger_async                                                20
#define ES_Logger_close                                                21
#define ES_Logger_filter                                               22
#define ES_Logger_flush                                                23
#define ES_Logger_level                                                24
#define ES_Logger_match                                                25
#define ES_Logger_name                                                 26
#define ES_Logger_outStream                                            27
#define ES_Logger_parent                                               28
#define ES_Logger_debug                                                29
#define ES_Logger_config                                               30
#define ES_Logger_error                                                31
#define ES_Logger_info                                                 32
#define ES_Logger_read                                                 33
#define ES_Logger_removeListener                                       34
#define ES_Logger_write                                                35
#define ES_Logger_warn                                                 36
#define ES_Logger_emit                                                 37
#define ES_Logger_NUM_INSTANCE_PROP                                    38


/*
    Class property slots for the "Math" type 
 */
#define ES_Math__initializer___Math_                                   0
#define ES_Math_E                                                      1
#define ES_Math_LN2                                                    2
#define ES_Math_LN10                                                   3
#define ES_Math_LOG2E                                                  4
#define ES_Math_LOG10E                                                 5
#define ES_Math_PI                                                     6
#define ES_Math_SQRT1_2                                                7
#define ES_Math_SQRT2                                                  8
#define ES_Math_abs                                                    9
#define ES_Math_acos                                                   10
#define ES_Math_asin                                                   11
#define ES_Math_atan                                                   12
#define ES_Math_atan2                                                  13
#define ES_Math_ceil                                                   14
#define ES_Math_cos                                                    15
#define ES_Math_exp                                                    16
#define ES_Math_floor                                                  17
#define ES_Math_log10                                                  18
#define ES_Math_log                                                    19
#define ES_Math_max                                                    20
#define ES_Math_min                                                    21
#define ES_Math_pow                                                    22
#define ES_Math_random                                                 23
#define ES_Math_round                                                  24
#define ES_Math_sin                                                    25
#define ES_Math_sqrt                                                   26
#define ES_Math_tan                                                    27

#define ES_Math_NUM_CLASS_PROP                                         28

/*
   Prototype (instance) slots for "Math" type 
 */
#define ES_Math_NUM_INSTANCE_PROP                                      12

/*
    Local slots for methods in type "Math" 
 */
#define ES_Math_abs_value                                              0
#define ES_Math_acos_angle                                             0
#define ES_Math_asin_oper                                              0
#define ES_Math_atan_oper                                              0
#define ES_Math_atan2_y                                                0
#define ES_Math_atan2_x                                                1
#define ES_Math_ceil_oper                                              0
#define ES_Math_cos_angle                                              0
#define ES_Math_exp_power                                              0
#define ES_Math_floor_oper                                             0
#define ES_Math_log10_oper                                             0
#define ES_Math_log_oper                                               0
#define ES_Math_max_x                                                  0
#define ES_Math_max_y                                                  1
#define ES_Math_min_x                                                  0
#define ES_Math_min_y                                                  1
#define ES_Math_pow_num                                                0
#define ES_Math_pow_pow                                                1
#define ES_Math_round_num                                              0
#define ES_Math_sin_angle                                              0
#define ES_Math_sqrt_oper                                              0
#define ES_Math_tan_angle                                              0


/*
    Class property slots for the "Memory" type 
 */
#define ES_Memory_allocated                                            0
#define ES_Memory_callback                                             1
#define ES_Memory_maximum                                              2
#define ES_Memory_peak                                                 3
#define ES_Memory_redline                                              4
#define ES_Memory_resident                                             5
#define ES_Memory_stack                                                6
#define ES_Memory_system                                               7
#define ES_Memory_stats                                                8

#define ES_Memory_NUM_CLASS_PROP                                       9

/*
   Prototype (instance) slots for "Memory" type 
 */
#define ES_Memory_NUM_INSTANCE_PROP                                    12

#define ES_Namespace_NUM_CLASS_PROP                                    0

/*
   Prototype (instance) slots for "Namespace" type 
 */
#define ES_Namespace_NUM_INSTANCE_PROP                                 12

#define ES_Null_NUM_CLASS_PROP                                         0

/*
   Prototype (instance) slots for "Null" type 
 */
#define ES_Null_NUM_INSTANCE_PROP                                      12


/*
    Class property slots for the "Number" type 
 */
#define ES_Number__initializer___Number_                               0
#define ES_Number_MAX_VALUE                                            1
#define ES_Number_MIN_VALUE                                            2
#define ES_Number_NaN                                                  3
#define ES_Number_NEGATIVE_INFINITY                                    4
#define ES_Number_POSITIVE_INFINITY                                    5
#define ES_Number_MaxValue                                             6
#define ES_Number_MinValue                                             7

#define ES_Number_NUM_CLASS_PROP                                       8

/*
   Prototype (instance) slots for "Number" type 
 */
#define ES_Number_Number                                               12
#define ES_Number_abs                                                  13
#define ES_Number_ceil                                                 14
#define ES_Number_floor                                                15
#define ES_Number_isFinite                                             16
#define ES_Number_isNaN                                                17
#define ES_Number_round                                                18
#define ES_Number_toExponential                                        19
#define ES_Number_toFixed                                              20
#define ES_Number_toPrecision                                          21
#define ES_Number_byte                                                 22
#define ES_Number_integral                                             23
#define ES_Number_max                                                  24
#define ES_Number_min                                                  25
#define ES_Number_power                                                26
#define ES_Number_NUM_INSTANCE_PROP                                    27


/*
    Class property slots for the "Object" type 
 */
#define ES_Object_create                                               0
#define ES_Object_defineProperty                                       1
#define ES_Object_defineProperties                                     2
#define ES_Object_freeze                                               3
#define ES_Object_getOwnPropertyDescriptor                             4
#define ES_Object_getOwnPropertyNames                                  5
#define ES_Object_getOwnPropertyCount                                  6
#define ES_Object_getOwnPrototypeOf                                    7
#define ES_Object_isExtensible                                         8
#define ES_Object_isFrozen                                             9
#define ES_Object_isSealed                                             10
#define ES_Object_keys                                                 11
#define ES_Object_preventExtensions                                    12
#define ES_Object_seal                                                 13

#define ES_Object_NUM_CLASS_PROP                                       14

/*
   Prototype (instance) slots for "Object" type 
 */
#define ES_Object_constructor                                          0
#define ES_Object_prototype                                            1
#define ES_Object_clone                                                2
#define ES_Object_get                                                  3
#define ES_Object_getValues                                            4
#define ES_Object_hasOwnProperty                                       5
#define ES_Object_isPrototypeOf                                        6
#define ES_Object_propertyIsEnumerable                                 7
#define ES_Object_toJSON                                               8
#define ES_Object_toLocaleString                                       9
#define ES_Object_toString                                             10
#define ES_Object_valueOf                                              11
#define ES_Object_NUM_INSTANCE_PROP                                    12

/*
    Local slots for methods in type "Object" 
 */
#define ES_Object_create_prototype                                     0
#define ES_Object_create_props                                         1
#define ES_Object_defineProperty_obj                                   0
#define ES_Object_defineProperty_name                                  1
#define ES_Object_defineProperty_options                               2
#define ES_Object_defineProperties_obj                                 0
#define ES_Object_defineProperties_properties                          1
#define ES_Object_freeze_obj                                           0
#define ES_Object_getOwnPropertyDescriptor_obj                         0
#define ES_Object_getOwnPropertyDescriptor_prop                        1
#define ES_Object_getOwnPropertyNames_obj                              0
#define ES_Object_getOwnPropertyCount_obj                              0
#define ES_Object_getOwnPrototypeOf_obj                                0
#define ES_Object_isExtensible_obj                                     0
#define ES_Object_isFrozen_obj                                         0
#define ES_Object_isSealed_obj                                         0
#define ES_Object_keys_obj                                             0
#define ES_Object_preventExtensions_obj                                0
#define ES_Object_seal_obj                                             0

#define ES_Path_NUM_CLASS_PROP                                         0

/*
   Prototype (instance) slots for "Path" type 
 */
#define ES_Path_Path                                                   12
#define ES_Path_absolute                                               13
#define ES_Path_accessed                                               14
#define ES_Path_basename                                               15
#define ES_Path_components                                             16
#define ES_Path_contains                                               17
#define ES_Path_copy                                                   18
#define ES_Path_created                                                19
#define ES_Path_dirname                                                20
#define ES_Path_endsWith                                               21
#define ES_Path_exists                                                 22
#define ES_Path_extension                                              23
#define ES_Path_find                                                   24
#define ES_Path_files                                                  25
#define ES_Path_hasDrive                                               26
#define ES_Path_isAbsolute                                             27
#define ES_Path_isDir                                                  28
#define ES_Path_isLink                                                 29
#define ES_Path_isRegular                                              30
#define ES_Path_isRelative                                             31
#define ES_Path_join                                                   32
#define ES_Path_joinExt                                                33
#define ES_Path_length                                                 34
#define ES_Path_linkTarget                                             35
#define ES_Path_makeDir                                                36
#define ES_Path_makeLink                                               37
#define ES_Path_makeTemp                                               38
#define ES_Path_map                                                    39
#define ES_Path_mimeType                                               40
#define ES_Path_modified                                               41
#define ES_Path_name                                                   42
#define ES_Path_natural                                                43
#define ES_Path_normalize                                              44
#define ES_Path_open                                                   45
#define ES_Path_openTextStream                                         46
#define ES_Path_openBinaryStream                                       47
#define ES_Path_parent                                                 48
#define ES_Path_perms                                                  49
#define ES_Path_portable                                               50
#define ES_Path_readBytes                                              51
#define ES_Path_readLines                                              52
#define ES_Path_readString                                             53
#define ES_Path_readXML                                                54
#define ES_Path_relative                                               55
#define ES_Path_remove                                                 56
#define ES_Path_removeAll                                              57
#define ES_Path_rename                                                 58
#define ES_Path_replaceExt                                             59
#define ES_Path_resolve                                                60
#define ES_Path_same                                                   61
#define ES_Path_separator                                              62
#define ES_Path_size                                                   63
#define ES_Path_startsWith                                             64
#define ES_Path_toLower                                                65
#define ES_Path_trimEnd                                                66
#define ES_Path_trimExt                                                67
#define ES_Path_trimStart                                              68
#define ES_Path_truncate                                               69
#define ES_Path_write                                                  70
#define ES_Path_NUM_INSTANCE_PROP                                      71

#define ES_Promise_NUM_CLASS_PROP                                      0

/*
   Prototype (instance) slots for "Promise" type 
 */
#define ES_Promise_Promise                                             22
#define ES_Promise_timer                                               23
#define ES_Promise_fired                                               24
#define ES_Promise_addCallback                                         25
#define ES_Promise_addCancelback                                       26
#define ES_Promise_addErrback                                          27
#define ES_Promise_emitSuccess                                         28
#define ES_Promise_emitError                                           29
#define ES_Promise_emitCancel                                          30
#define ES_Promise_cancel                                              31
#define ES_Promise_then                                                32
#define ES_Promise_timeout                                             33
#define ES_Promise_wait                                                34
#define ES_Promise_issue                                               35
#define ES_Promise_NUM_INSTANCE_PROP                                   36

#define ES_Reflect_NUM_CLASS_PROP                                      0

/*
   Prototype (instance) slots for "Reflect" type 
 */
#define ES_Reflect_Reflect                                             12
#define ES_Reflect_obj                                                 13
#define ES_Reflect_base                                                14
#define ES_Reflect_isType                                              15
#define ES_Reflect_type                                                16
#define ES_Reflect_name                                                17
#define ES_Reflect_NUM_INSTANCE_PROP                                   18

#define ES_RegExp_NUM_CLASS_PROP                                       0

/*
   Prototype (instance) slots for "RegExp" type 
 */
#define ES_RegExp_RegExp                                               12
#define ES_RegExp_lastIndex                                            13
#define ES_RegExp_exec                                                 14
#define ES_RegExp_global                                               15
#define ES_RegExp_ignoreCase                                           16
#define ES_RegExp_multiline                                            17
#define ES_RegExp_source                                               18
#define ES_RegExp_matched                                              19
#define ES_RegExp_replace                                              20
#define ES_RegExp_split                                                21
#define ES_RegExp_start                                                22
#define ES_RegExp_sticky                                               23
#define ES_RegExp_test                                                 24
#define ES_RegExp_NUM_INSTANCE_PROP                                    25

#define ES_Socket_NUM_CLASS_PROP                                       0

/*
   Prototype (instance) slots for "Socket" type 
 */
#define ES_Socket_Socket                                               12
#define ES_Socket_addListener                                          13
#define ES_Socket_accept                                               14
#define ES_Socket_address                                              15
#define ES_Socket_async                                                16
#define ES_Socket_close                                                17
#define ES_Socket_connect                                              18
#define ES_Socket_encoding                                             19
#define ES_Socket_flush                                                20
#define ES_Socket_listen                                               21
#define ES_Socket_port                                                 22
#define ES_Socket_read                                                 23
#define ES_Socket_remoteAddress                                        24
#define ES_Socket_removeListener                                       25
#define ES_Socket_write                                                26
#define ES_Socket_NUM_INSTANCE_PROP                                    27

#define ES_Stream_NUM_CLASS_PROP                                       0

/*
   Prototype (instance) slots for "Stream" type 
 */
#define ES_Stream_READ                                                 0
#define ES_Stream_WRITE                                                1
#define ES_Stream_BOTH                                                 2
#define ES_Stream_addListener                                          3
#define ES_Stream_async                                                4
#define ES_Stream_close                                                5
#define ES_Stream_flush                                                6
#define ES_Stream_read                                                 7
#define ES_Stream_removeListener                                       8
#define ES_Stream_write                                                9
#define ES_Stream_NUM_INSTANCE_PROP                                    10


/*
    Class property slots for the "String" type 
 */
#define ES_String_fromCharCode                                         0

#define ES_String_NUM_CLASS_PROP                                       1

/*
   Prototype (instance) slots for "String" type 
 */
#define ES_String_String                                               12
#define ES_String_caseCompare                                          13
#define ES_String_caselessCompare                                      14
#define ES_String_charAt                                               15
#define ES_String_charCodeAt                                           16
#define ES_String_concat                                               17
#define ES_String_contains                                             18
#define ES_String_endsWith                                             19
#define ES_String_format                                               20
#define ES_String_indexOf                                              21
#define ES_String_isDigit                                              22
#define ES_String_isAlpha                                              23
#define ES_String_isAlphaNum                                           24
#define ES_String_isLower                                              25
#define ES_String_isSpace                                              26
#define ES_String_isUpper                                              27
#define ES_String_lastIndexOf                                          28
#define ES_String_length                                               29
#define ES_String_match                                                30
#define ES_String_parseJSON                                            31
#define ES_String_toCamel                                              32
#define ES_String_toPascal                                             33
#define ES_String_printable                                            34
#define ES_String_quote                                                35
#define ES_String_remove                                               36
#define ES_String_replace                                              37
#define ES_String_reverse                                              38
#define ES_String_search                                               39
#define ES_String_slice                                                40
#define ES_String_split                                                41
#define ES_String_startsWith                                           42
#define ES_String_substring                                            43
#define ES_String_times                                                44
#define ES_String_tokenize                                             45
#define ES_String_toLower                                              46
#define ES_String_toUpper                                              47
#define ES_String_trim                                                 48
#define ES_String_trimStart                                            49
#define ES_String_trimEnd                                              50
#define ES_String_MINUS                                                51
#define ES_String_MOD                                                  52
#define ES_String_NUM_INSTANCE_PROP                                    53

/*
    Local slots for methods in type "String" 
 */
#define ES_String_fromCharCode_codes                                   0


/*
    Class property slots for the "System" type 
 */
#define ES_System__initializer___System_                               0
#define ES_System_Bufsize                                              1
#define ES_System_hostname                                             2
#define ES_System_ipaddr                                               3
#define ES_System_run                                                  4
#define ES_System_runx                                                 5
#define ES_System_daemon                                               6
#define ES_System_sh                                                   7
#define ES_System_cmd                                                  8
#define ES_System_exec                                                 9

#define ES_System_NUM_CLASS_PROP                                       10

/*
   Prototype (instance) slots for "System" type 
 */
#define ES_System_NUM_INSTANCE_PROP                                    12

/*
    Local slots for methods in type "System" 
 */
#define ES_System_run_cmd                                              0
#define ES_System_runx_cmd                                             0
#define ES_System_daemon_cmd                                           0
#define ES_System_sh_args                                              0
#define ES_System_cmd_args                                             0
#define ES_System_exec_args                                            0

#define ES_TextStream_NUM_CLASS_PROP                                   0

/*
   Prototype (instance) slots for "TextStream" type 
 */
#define ES_TextStream_TextStream                                       12
#define ES_TextStream_newline                                          13
#define ES_TextStream_inbuf                                            14
#define ES_TextStream_format                                           15
#define ES_TextStream_nextStream                                       16
#define ES_TextStream_addListener                                      17
#define ES_TextStream_async                                            18
#define ES_TextStream_available                                        19
#define ES_TextStream_close                                            20
#define ES_TextStream_encoding                                         21
#define ES_TextStream_fill                                             22
#define ES_TextStream_flush                                            23
#define ES_TextStream_read                                             24
#define ES_TextStream_readLine                                         25
#define ES_TextStream_readLines                                        26
#define ES_TextStream_readString                                       27
#define ES_TextStream_removeListener                                   28
#define ES_TextStream_write                                            29
#define ES_TextStream_writeLine                                        30
#define ES_TextStream_NUM_INSTANCE_PROP                                31

#define ES_Timer_NUM_CLASS_PROP                                        0

/*
   Prototype (instance) slots for "Timer" type 
 */
#define ES_Timer_Timer                                                 12
#define ES_Timer_drift                                                 13
#define ES_Timer_period                                                14
#define ES_Timer_restart                                               15
#define ES_Timer_stop                                                  16
#define ES_Timer_NUM_INSTANCE_PROP                                     17

#define ES_TimerEvent_NUM_CLASS_PROP                                   0

/*
   Prototype (instance) slots for "TimerEvent" type 
 */
#define ES_TimerEvent_TimerEvent                                       15
#define ES_TimerEvent_NUM_INSTANCE_PROP                                16

#define ES_Type_NUM_CLASS_PROP                                         0

/*
   Prototype (instance) slots for "Type" type 
 */
#define ES_Type_NUM_INSTANCE_PROP                                      12


/*
    Class property slots for the "Uri" type 
 */
#define ES_Uri_decode                                                  0
#define ES_Uri_decodeComponent                                         1
#define ES_Uri_encode                                                  2
#define ES_Uri_encodeComponent                                         3

#define ES_Uri_NUM_CLASS_PROP                                          4

/*
   Prototype (instance) slots for "Uri" type 
 */
#define ES_Uri_Uri                                                     12
#define ES_Uri_basename                                                13
#define ES_Uri_complete                                                14
#define ES_Uri_components                                              15
#define ES_Uri_dirname                                                 16
#define ES_Uri_endsWith                                                17
#define ES_Uri_extension                                               18
#define ES_Uri_filename                                                19
#define ES_Uri_hasExtension                                            20
#define ES_Uri_hasHost                                                 21
#define ES_Uri_hasPort                                                 22
#define ES_Uri_hasQuery                                                23
#define ES_Uri_hasReference                                            24
#define ES_Uri_hasScheme                                               25
#define ES_Uri_host                                                    26
#define ES_Uri_isAbsolute                                              27
#define ES_Uri_isDir                                                   28
#define ES_Uri_isRegular                                               29
#define ES_Uri_isRelative                                              30
#define ES_Uri_join                                                    31
#define ES_Uri_joinExt                                                 32
#define ES_Uri_mimeType                                                33
#define ES_Uri_normalize                                               34
#define ES_Uri_path                                                    35
#define ES_Uri_port                                                    36
#define ES_Uri_scheme                                                  37
#define ES_Uri_query                                                   38
#define ES_Uri_reference                                               39
#define ES_Uri_relative                                                40
#define ES_Uri_replaceExt                                              41
#define ES_Uri_same                                                    42
#define ES_Uri_startsWith                                              43
#define ES_Uri_trimEnd                                                 44
#define ES_Uri_trimExt                                                 45
#define ES_Uri_trimStart                                               46
#define ES_Uri_uri                                                     47
#define ES_Uri_NUM_INSTANCE_PROP                                       48

/*
    Local slots for methods in type "Uri" 
 */
#define ES_Uri_decode_str                                              0
#define ES_Uri_decodeComponent_str                                     0
#define ES_Uri_encode_str                                              0
#define ES_Uri_encodeComponent_str                                     0

#define ES_Void_NUM_CLASS_PROP                                         0

/*
   Prototype (instance) slots for "Void" type 
 */
#define ES_Void_NUM_INSTANCE_PROP                                      12


/*
    Class property slots for the "Worker" type 
 */
#define ES_Worker_exit                                                 0
#define ES_Worker_join                                                 1
#define ES_Worker_lookup                                               2

#define ES_Worker_NUM_CLASS_PROP                                       3

/*
   Prototype (instance) slots for "Worker" type 
 */
#define ES_Worker_Worker                                               12
#define ES_Worker_onclose                                              13
#define ES_Worker_onmessage                                            14
#define ES_Worker_onerror                                              15
#define ES_Worker_name                                                 16
#define ES_Worker_eval                                                 17
#define ES_Worker_load                                                 18
#define ES_Worker_preload                                              19
#define ES_Worker_preeval                                              20
#define ES_Worker_postMessage                                          21
#define ES_Worker_terminate                                            22
#define ES_Worker_waitForMessage                                       23
#define ES_Worker_NUM_INSTANCE_PROP                                    24

/*
    Local slots for methods in type "Worker" 
 */
#define ES_Worker_join_workers                                         0
#define ES_Worker_join_timeout                                         1
#define ES_Worker_lookup_name                                          0

#define ES_XML_NUM_CLASS_PROP                                          0

/*
   Prototype (instance) slots for "XML" type 
 */
#define ES_XML_XML                                                     12
#define ES_XML_load                                                    13
#define ES_XML_save                                                    14
#define ES_XML_appendChild                                             15
#define ES_XML_attribute                                               16
#define ES_XML_attributes                                              17
#define ES_XML_child                                                   18
#define ES_XML_childIndex                                              19
#define ES_XML_children                                                20
#define ES_XML_contains                                                21
#define ES_XML_copy                                                    22
#define ES_XML_descendants                                             23
#define ES_XML_elements                                                24
#define ES_XML_hasComplexContent                                       25
#define ES_XML_hasSimpleContent                                        26
#define ES_XML_length                                                  27
#define ES_XML_name                                                    28
#define ES_XML_parent                                                  29
#define ES_XML_NUM_INSTANCE_PROP                                       30


/*
    Class property slots for the "XMLHttp" type 
 */
#define ES_XMLHttp__initializer___XMLHttp_                             0
#define ES_XMLHttp_Uninitialized                                       1
#define ES_XMLHttp_Open                                                2
#define ES_XMLHttp_Sent                                                3
#define ES_XMLHttp_Receiving                                           4
#define ES_XMLHttp_Loaded                                              5

#define ES_XMLHttp_NUM_CLASS_PROP                                      6

/*
   Prototype (instance) slots for "XMLHttp" type 
 */
#define ES_XMLHttp_XMLHttp                                             12
#define ES_XMLHttp_hp                                                  13
#define ES_XMLHttp_state                                               14
#define ES_XMLHttp_response                                            15
#define ES_XMLHttp_onreadystatechange                                  16
#define ES_XMLHttp_abort                                               17
#define ES_XMLHttp_http                                                18
#define ES_XMLHttp_readyState                                          19
#define ES_XMLHttp_responseText                                        20
#define ES_XMLHttp_responseXML                                         21
#define ES_XMLHttp_responseBody                                        22
#define ES_XMLHttp_status                                              23
#define ES_XMLHttp_statusText                                          24
#define ES_XMLHttp_getAllResponseHeaders                               25
#define ES_XMLHttp_getResponseHeader                                   26
#define ES_XMLHttp_open                                                27
#define ES_XMLHttp_send                                                28
#define ES_XMLHttp_setRequestHeader                                    29
#define ES_XMLHttp_callback                                            30
#define ES_XMLHttp_notify                                              31
#define ES_XMLHttp_NUM_INSTANCE_PROP                                   32

#define ES_XMLList_NUM_CLASS_PROP                                      0

/*
   Prototype (instance) slots for "XMLList" type 
 */
#define ES_XMLList_XMLList                                             12
#define ES_XMLList_appendChild                                         13
#define ES_XMLList_attribute                                           14
#define ES_XMLList_attributes                                          15
#define ES_XMLList_child                                               16
#define ES_XMLList_childIndex                                          17
#define ES_XMLList_children                                            18
#define ES_XMLList_copy                                                19
#define ES_XMLList_descendants                                         20
#define ES_XMLList_elements                                            21
#define ES_XMLList_hasComplexContent                                   22
#define ES_XMLList_inScopeNamespaces                                   23
#define ES_XMLList_length                                              24
#define ES_XMLList_name                                                25
#define ES_XMLList_parent                                              26
#define ES_XMLList_NUM_INSTANCE_PROP                                   27

#define _ES_CHECKSUM_ejs   1284075

#endif
