#
#	Makefile for master includes
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 		.makedep

dependExtra:
	cp master/*slots.h $(BLD_INC_DIR)

cleanExtra:
	mkdir -p $(BLD_INC_DIR)
	cp master/*slots.h $(BLD_INC_DIR)

